#!/usr/bin/python
import time
import sys
import os
import socket
"""
Poller script which runs on ss and calculates the ul utilization of the ss connected from BS.

Poller script determines the uplink utilization of the ss.
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.1.4.1.21 from snmp agent of device at specific interval.
uplink utilization information is sent to device application 

"""
# ##################################################################
# Function : check_wimax_pmp2_dl_utilization_kpi
#
#  Parameters: info(SNMP output) ,params(parameters to check the service state) 
#
#  Output: service state,plugin output ,performance data
##################################################################




def extract_pmp2_bw_from_live(hostname,site):
        """
        Connects to a socket, checks for the WELCOME-MSG and closes the
        connection.
        Returns nothing.
    
        """
        pmp_bw = None
        query_string = "GET services\nColumns: plugin_output\nFilter: " + \
                        "service_description = %s\nFilter: host_name = %s\nOutputFormat: python\n" % ("wimax_pmp_bw_invent",hostname)

	try:
        	s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
		socket_path = "/omd/sites/%s/tmp/run/live" % site

		s.connect(socket_path)
		s.send(query_string)
       		s.shutdown(socket.SHUT_WR)
        	query_output = s.recv(100000000)
        	query_output.strip("\n")
		query_output = eval(query_output)
        	if query_output:
			query_output = query_output[0][0] 
			output = [entry for entry in query_output.split(' - ')[1].split()]
                	pmp_bw=output[0].split('=')[1]
	except Exception,e:
		pmp_bw=None

        return pmp_bw

def extract_pmp2_dl_util_from_live(hostname,site,dr_slave):
        """
        Connects to a socket, checks for the WELCOME-MSG and closes the
        connection.
        Returns nothing.
    
        """
	pmp2_dl = None
	dr_dl = None
	query = "GET services\nColumns: service_perf_data\n" + \
		"Filter: service_description = wimax_pmp2_dl_util_bgp\n" + \
		"Filter: host_name = %s\nFilter: host_name = %s\nOr: 2\nOutputFormat: python\n" % (hostname,dr_slave)
		
	try:
        	s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
		socket_path = "/omd/sites/%s/tmp/run/live" % site
        	s.connect(socket_path)
		s.send(query)
       		s.shutdown(socket.SHUT_WR)
        	query_output = s.recv(100000000)
        	query_output.strip("\n")
		query_output = eval(query_output)
		try:
        		if query_output[0][0]:
				pmp2_dl = query_output[0][0].split('=')[1].split(';',1)[0]
		except:
			pmp2_dl = None
		try:
			if dr_slave and query_output[1][0]:
					dr_dl = query_output[1][0].split('=')[1].split(';',1)[0]
		except:
			dr_dl = None
			
	except Exception ,e:
		pmp2_dl=None
		dr_dl=None

        return pmp2_dl,dr_dl


def live_query_pmp2_dl_util_kpi(hostname,site,war,crit,dr_slave):
    state = 3
    status_list = [] 
    pmp2_dl_kpi = ''
    perf = ''
    plugin_message = ''
    total_dl = None
    state_string = "unknown"
    try:
	pmp2_bw = extract_pmp2_bw_from_live(hostname,site)
	pmp2_dl,dr_dl= extract_pmp2_dl_util_from_live(hostname,site,dr_slave)
	if pmp2_dl != None and dr_dl != None:
		total_dl = eval(pmp2_dl) + eval(dr_dl)
	elif pmp2_dl != None:
		total_dl = eval(pmp2_dl)
	elif dr_dl != None:
		total_dl = eval(dr_dl)
	if pmp2_bw:
		pmp2_bw = eval(pmp2_bw)
	if pmp2_bw and total_dl != None:
		if pmp2_bw <= 3:
			pmp2_dl_kpi = (total_dl/4) *100
		elif pmp2_bw  > 3:
			pmp2_dl_kpi = (total_dl/8) *100
		else:
			pmp2_dl_kpi = ''
	

	if pmp2_dl_kpi != None:
                if pmp2_dl_kpi < war:
                        state = 0
                        state_string = "ok"
                elif pmp2_dl_kpi >= crit:
                        state = 2
                        state_string = "critical"
                else:
                        state = 1
                        state_string = "warning"

		
	perf += 'pmp2_dl_util_kpi' + "=%s;%s;%s " % (pmp2_dl_kpi,war,crit)
    except Exception ,e:
	perf = '' 
    plugin_message += "wimax_pmp2_dl_util_kpi %s - %s|%s" % (state_string,pmp2_dl_kpi,perf)
    sys.stdout.write(plugin_message)
    sys.exit((state))
		
def  main():

    state_string = "unknown"
    pmp2_dl=''
    plugin_message = ''
    try:
        host_name = sys.argv[1]
        site = sys.argv[2]
        war = sys.argv[3]
        crit = sys.argv[4]
	dr_slave = sys.argv[5]
    except:
        perf =''
        plugin_message += "wimax_pmp2_dl_util_kpi %s - %s|%s" % (state_string,pmp2_dl,perf)
        sys.exit((3))

    live_query_pmp2_dl_util_kpi(host_name,site,float(war),float(crit),dr_slave)
	

if __name__ == '__main__':
	main() 
