#!/usr/bin/python

"""
Link Distance Poller script.

This is part of device application. 
Poller script determines the link distance between BS. 
poller script takes the snmp value of OID .1.3.6.1.4.1.4458.1000.1.5.29 from snmp agent of device at specific interval.
Link distance informatio is sent to device application 

"""
# #######################################################################
# Function : check_radwin_link_distance_invent
#
# Parameters: info (SNMP Output ) _no_params (No parameters)
# 
# Output: service state ,plugin output
# ######################################################################
def check_radwin_link_distance_invent(item, _no_params, info):
    """
                check_radwin_link_distance_invent function calculates the link distance between BS.

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : Ok-2400

                        Raises:
                                ValueError ,Exception
    """
    state = 3
    infotext = "unknown_value"
    try:
        if info:
            link_distance = int(info[0][0])
            if link_distance == -1:
                infotext = "link_not_established"
                state = 0
            elif link_distance > 0:
                state = 0
                infotext = "%d" % link_distance
            else:
                infotext = "unknown_value"
                state = 0
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"
    return (state, infotext)


check_info["radwin_link_distance_invent"] = {
    'check_function': check_radwin_link_distance_invent,
    'service_description': 'radwin_link_distance_invent',
}

"""
	SNMP OID for the link distance 
"""

snmp_info["radwin_link_distance_invent"] = ( ".1.3.6.1.4.1.4458.1000.1", ["5.29"] )
