#!/usr/bin/python

"""
Downlink utilizationPoller script.

This is part of device application. 
Poller script determines the port current Downlink utilization in terms of number of octets in downlink direction.
poller script takes the snmp value of OID .1.3.6.1.2.1.2.2.1.16 from snmp agent of device at specific interval.
Total Downlink utilization is sent to device application 

"""
# #######################################################################
# Function : check_radwin_dl_utilization
#
# Parameters: info (SNMP otuput ,_no_params (NO parameters))
#
# Output: service state,plugin output and performance data
########################################################################
import logging

import os

try:
    log_file = "nocout/log_plugins.log"
    with open(log_file, 'a+') as f:
        pass
    logging.basicConfig(filename=log_file, level=logging.CRITICAL)
except:
    pass


def check_radwin_dl_utilization(item, _no_params, info):
    """
                check_radwin_dl_utilization function calculates the downlink utilization

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : OK - [Management_Port_on_Odu] dl_utilization:2994339289

                        performance_data  (list):
                                        performance data
                                        Example: Management_Port_on_Odu=2994339289;;;; Radio_Interface=;;;;
                        Raises:
                                ValueError ,Exception
    """
    state = 3
    infotext = "unknown output"
    status_list = ['']
    try:
        logging.debug("radwin_dl_utilization SNMP Output %s", info)
        status_list = []
        if not info[0]:
            raise ValueError
        infotext = ""
        for index in range(len(info)):
            link_out_octets = info[index][1]
            if_name = info[index][0]
            if if_name == None:
                if_name = "unknown interface name"
            if ' ' in if_name:
                if_name = str.replace(if_name, ' ', '_')
            status_list.append((if_name, link_out_octets))
        state = 0
        for name, out_octets, in status_list:
            infotext += "[%s] dl_utilization:%s" % (name, out_octets)
    except ValueError:
        infotext = "interface utilization type not correct"
        logging.critical("radwin_dl_utilization %s", infotext, exc_info=True)
    except:
        infotext = "unknown value"
        logging.critical("radwin_dl_utilization %s", infotext, exc_info=True)
    return (state, infotext, status_list)


check_info["radwin_dl_utilization"] = {
    'check_function': check_radwin_dl_utilization,
    'service_description': 'radwin_dl_utilization',
    'has_perfdata': True,
}

##############################################################################
#SNMP OID for the Downlink utilization
##############################################################################


snmp_info["radwin_dl_utilization"] = ( ".1.3.6.1.2.1.2.2.1", ["2", "16"] )
