#!/usr/bin/python

"""
SS ID Poller script.

Poller script determines the SS id.
poller script takes the snmp value of OID .1.3.6.1.4.1.4458.1000.1.5.3 from snmp agent of device at specific interval.
SS ID information is sent to device application 


"""
# #################################################################
# Function : check_radwin_ssid_invent
#
# Parameters : info (SNMP Output) ,_no_params(currently no available parameters )
#
# Output:     service state , plugin ouptut 
# ################################################################


def check_radwin_ssid_invent(item, _no_params, info):
    """
                check_radwin_ssid_invent function calculates the ssid of device

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : SELUCREHpondy to ngm

                        Raises:
                                Exception
    """
    state = 3
    infotext = "unknown_value"
    try:
        if info:
            if info[0][0]:
                ssid = info[0][0]
                state = 0
                infotext = "%s" % ssid
    except:
        infotext = "unknown_value"
    return (state, infotext)


check_info["radwin_ssid_invent"] = {
    'check_function': check_radwin_ssid_invent,
    'service_description': 'radwin_ssid_invent',
}

##########################################################################
#		SNMP OID
#########################################################################
snmp_info["radwin_ssid_invent"] = ( ".1.3.6.1.4.1.4458.1000.1", ["5.3"] )

