#!/usr/bin/python
import re
"""
Downlink utilizationPoller script.

This is part of device application. 
Poller script determines the port current Downlink utilization in terms of number of octets in downlink direction.
poller script takes the snmp value of OID .1.3.6.1.2.1.2.2.1.16 from snmp agent of device at specific interval.
Total Downlink utilization is sent to device application 

"""
# #######################################################################
# Function : check_radwin_dl_utilization
#
# Parameters: info (SNMP otuput ,_no_params (NO parameters))
#
# Output: service state,plugin output and performance data
# #######################################################################


def check_radwin_dl_utilization(item, _no_params, info):
    """
                check_radwin_dl_utilization function calculates the downlink utilization

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : OK - [Management_Port_on_Odu] dl_utilization:2994339289

                        performance_data  (list):
                                        performance data
                                        Example: Management_Port_on_Odu=2994339289;;;; Radio_Interface=;;;;
                        Raises:
                                ValueError ,Exception
    """
    state = 3
    infotext = "unknown_value"
    status_list = ['']
    try:
        if info:
            status_list = []
            infotext = ""
            for index in range(len(info)):
                link_out_octets = info[index][1]
                if_name = info[index][0]
                if if_name == None:
                    if_name = "unknown interface name"
		if_name = re.sub('[^0-9a-zA-Z-_]+', '_', if_name)
                status_list.append((if_name, saveint(link_out_octets)))
            for name, out_octets, in status_list:
                infotext += "[%s] dl_utilization:%s" % (name, out_octets)
            state = 0
    except ValueError:
        infotext = "type_mismatch_error"
    except:
        infotext = "unknown_value"
    return (state, infotext, status_list)


check_info["radwin_dl_utilization"] = {
    'check_function': check_radwin_dl_utilization,
    'service_description': 'radwin_dl_utilization',
    'has_perfdata': True,
}

##############################################################################
#SNMP OID for the Downlink utilization
##############################################################################


snmp_info["radwin_dl_utilization"] = ( ".1.3.6.1.2.1.2.2.1", ["2", "16"] )
