#!/usr/bin/python

import sys
from telnetlib import Telnet
import socket
import json
import os
import re
import mysql.connector
"""
operating Frequency of ss device  Poller script.

This is part of device application. 
Poller script determines the operating ptx of device. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.1.1.2.0 from snmp agent of device at specific interval.
Device on which Frequency operating is sent to device application 

"""
# ######################################################################
# Function: check_wimax_qos_invent
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################



def check_wimax_qos_invent(item, _no_params, info):
    """
            check_wimax_qos_invent function calcdlates the operating ptx

            Args:
                    item (str) Specific item on SNMP output on which we want to filter resdlts

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - 5835

                    Raises:
                            ValueError ,Exception
"""
    state = 3
    infotext = "unknown_value"
    dl_qos= None
    ul_qos = None
    try:
	mac_info = sum(info,[])
        mac_list=map(lambda x: convert(x),mac_info)
        if mac_list[1] != '00:00:00:00:00:00':
                ss_mac= mac_list[1]
                state = 0
        else:
                index =[i for i, e in enumerate(mac_list) if e != '00:00:00:00:00:00']
                index =index[0]
                ss_mac = mac_list[index]
	if ss_mac:
		if memc:
			key = ss_mac + "_params"
			value_list = memc.get(key)
			if value_list:
                		try:
					ul_qos = value_list[2]
					dl_qos = value_list[3]
				except:
					ul_qos = None
					dl_qos = None
		if dl_qos and ul_qos:
			dl_qos = float(dl_qos)/(1000.0*1000)
			ul_qos = float(ul_qos)/(1000.0*1000)
			infotext = "dl_qos=%s ul_qos=%s" % (dl_qos,ul_qos)
			state = 0
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"

    return (state, infotext,[("ul_qos",ul_qos),("dl_qos",dl_qos)])


check_info["wimax_qos_invent"] = {
    'check_function': check_wimax_qos_invent,
    'service_description': 'wimax_qos_invent',
    'has_perfdata':True,
}

#########################################################################
#	SNMP OID for the operating ptx
#########################################################################
snmp_info["wimax_qos_invent"] = ( ".1.3.6.1.2.1.10.184.1.3.1.1.1", ["17.1"] )
