#!/usr/bin/python

import sys
from telnetlib import Telnet
import socket
import json
import os
import binascii
import mysql.connector
"""
operating Frequency of ss device  Poller script.

This is part of device application. 
Poller script determines the operating ptx of device. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.1.1.2.0 from snmp agent of device at specific interval.
Device on which Frequency operating is sent to device application 

"""
# ######################################################################
# Function: check_wimax_bs_ss_vlantag
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################




def connection_telnet_for_ss_vlan(host_ip, port):
        """
        Connects to a socket, checks for the WELCOME-MSG and closes the
        connection.
        Returns nothing.
    
        """
	mac_address_list = []
	match_string = '([a-fA-F0-9]{2}[:|\-]?){6}'	
        try:
                tn = Telnet(host_ip,port,timeout=6)
        except socket.timeout:
		result = None
		return result
        tn.read_until("Login:")
        tn.write("wireless" + "\r\n")
        tn.read_until("Password:")
        tn.write("wirelessone" + "\r\n")
        tn.write("show connectivity-table ss\r\n" )
        tn.write("clear screen" + "\r\n")
	data1 = tn.read_until("clear screen" + "\r\n")
	for i,row in enumerate(data1.split("\n")):
		if re.search(match_string,row):
			params_list = [r for r in row.split()]
			mac = params_list[2]
			mac_address_list.append(mac)
	for mac in mac_address_list:
        	tn.write("show connectivity-table ss %s\r\n" % mac )
        tn.write("exit\r\n")
        data = tn.read_all()

	
	ss_vlan = "vlan_miss"
	result = ""
        try:
                for i,row in enumerate(data.split("\n")):
			if "SS Entry" in row:
				params_list = [r for r in row.split()]
				mac = params_list[2]
				mac = mac.lower().strip()
                        if "VlanTag" in row:
				params_list = [r for r in row.split(',')]
				vlan_row = params_list[1]
				ss_vlan  = vlan_row.split('=')[1].strip()
				result = result + mac +"=" + str(ss_vlan) + " "
				mac = ""
			
        except:
		result = None
	return result

def check_wimax_bs_ss_vlantag(item, _no_params, info):
    """
            check_wimax_bs_ss_vlantag function calcdlates the operating ptx

            Args:
                    item (str) Specific item on SNMP output on which we want to filter resdlts

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - 5835

                    Raises:
                            ValueError ,Exception
"""
    state = 3
    infotext = "unknown_value"
    ss_vlan_list= None
    try:
	if info[0][0]:
                bs_ip = info[0][0]
                if bs_ip:
                	ss_vlan_list =connection_telnet_for_ss_vlan(bs_ip, 23)
			infotext = "%s" % ss_vlan_list
			state = 0
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"

    return (state, infotext)


check_info["wimax_bs_ss_vlantag"] = {
    'check_function': check_wimax_bs_ss_vlantag,
    'service_description': 'wimax_bs_ss_vlantag',
}

#########################################################################
#	SNMP OID for the operating ptx
#########################################################################
snmp_info["wimax_bs_ss_vlantag"] = ( ".1.3.6.1.4.1.5812.2000.4.1.1", ["1.0"] )
