#!/usr/bin/python

import sys
from telnetlib import Telnet
import socket
import json
import os

"""
operating Frequency of ss device  Poller script.

This is part of device application. 
Poller script determines the operating ptx of device. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.1.1.2.0 from snmp agent of device at specific interval.
Device on which Frequency operating is sent to device application 

"""
# ######################################################################
# Function: check_wimax_idu_serial_invent
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################


def check_wimax_idu_serial_invent(item, _no_params, info):
    """
            check_wimax_idu_serial_invent function calcdlates the operating ptx

            Args:
                    item (str) Specific item on SNMP output on which we want to filter resdlts

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - 5835

                    Raises:
                            ValueError ,Exception
"""
    state = 3
    infotext = "unknown_value"
    idu_serial_1= ''
    idu_serial_2= ''
    try:
	    if memc:
		    value_list = memc.get('%s_bs_params' % g_hostname)
		    value_list = eval(value_list)
		    if value_list:
		    	idu_serial_1,idu_serial_2 = (value_list[2],value_list[3]) 
    except:
	    pass
    try:
        if idu_serial_1 or idu_serial_2:
		if idu_serial_1:
			idu_serial_1 = idu_serial_1.replace('-','_')
		if idu_serial_2:
			idu_serial_2 = idu_serial_2.replace('-','_')
                infotext = "Chassis=%s Carrier_Board=%s" % (idu_serial_1, idu_serial_2)
                state = 0

    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"

    return (state, infotext,[("Chassis",idu_serial_1),("Carrier_Board",idu_serial_2)])


check_info["wimax_idu_serial_invent"] = {
    'check_function': check_wimax_idu_serial_invent,
    'service_description': 'wimax_idu_serial_invent',
    'has_perfdata':True,
}

#########################################################################
#	SNMP OID for the operating ptx
#########################################################################
snmp_info["wimax_idu_serial_invent"] = ( ".1.3.6.1.4.1.5812.2000.4.1.1", ["1.0"] )
