#!/usr/bin/python

import sys
from telnetlib import Telnet
import socket
import json
import os
import binascii
import mysql.connector
"""
operating Frequency of ss device  Poller script.

This is part of device application. 
Poller script determines the operating ptx of device. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.1.1.2.0 from snmp agent of device at specific interval.
Device on which Frequency operating is sent to device application 

"""
# ######################################################################
# Function: check_wimax_ss_dl_utilization
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################


def live_query_for_dl_utilization(host_name,mac,site):
        """
        Connects to a socket, checks for the WELCOME-MSG and closes the
        connection.
        Returns nothing.

        """
        exit_value = 3
        dl_utilization = None
        try:
                machine_name = site.split('_')[0]
                socket_ip = _LIVESTATUS[machine_name]['host']
                socket_port = _LIVESTATUS[machine_name][site]['port']

                query_string = "GET services\nColumns: plugin_output\nFilter: " + \
                                "service_description = %s\nFilter: host_name = %s\nOutputFormat: python\n" % ("wimax_bs_ss_params",host_name)

                query_output = eval(get_from_socket(socket_ip,socket_port,query_string,site,machine_name).strip())
                if query_output[0][0]:
                        plugin_output = str(query_output[0][0].split('OK -')[1])
                        plugin_output = [entry for entry in plugin_output.split(' ')]
                        plugin_output = filter(lambda x: mac in x,plugin_output)
                        dl_utilization = plugin_output[0].split('=')[1].split(',')[1]

        except:
                dl_utilization = None
        return dl_utilization

                                

def check_wimax_ss_dl_utilization(item, _no_params, info):
    """
            check_wimax_ss_dl_utilization function calcdlates the operating ptx

            Args:
                    item (str) Specific item on SNMP output on which we want to filter resdlts

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - 5835

                    Raises:
                            ValueError ,Exception
    """
    state = 3
    infotext = "unknown_value"
    dl_throughput= None
    try:
	mac_info = sum(info,[])
        mac_list=map(lambda x: convert(x),mac_info)
        if mac_list[1] != '00:00:00:00:00:00':
                ss_mac= mac_list[1]
                state = 0
        else:
                index =[i for i, e in enumerate(mac_list) if e != '00:00:00:00:00:00']
                index =index[0]
                ss_mac = mac_list[index]
	if ss_mac:
		host_name = extract_host_name_from_wimax_topology(ss_mac)
		if host_name[0][0]:
			dl_throughput =live_query_for_dl_utilization(host_name[0][0],ss_mac,host_name[0][1])
			if dl_throughput:
				dl_throughput = float(dl_throughput)/1024.0
				infotext = "SS downlink utilization is %s" % dl_throughput
				state = 0
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"

    return (state, infotext,[("dl_utilization", dl_throughput)])


check_info["wimax_ss_dl_utilization"] = {
    'check_function': check_wimax_ss_dl_utilization,
    'service_description': 'wimax_ss_dl_utilization',
    'has_perfdata': True,
}

#########################################################################
#	SNMP OID for the operating ptx
#########################################################################
snmp_info["wimax_ss_dl_utilization"] = ( ".1.3.6.1.2.1.10.184.1.3.1.1.1", ["17.1"] )
