#!/usr/bin/python

import sys
from telnetlib import Telnet
import socket
import json
import os

"""
operating Frequency of ss device  Poller script.

This is part of device application. 
Poller script determines the operating ptx of device. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.1.1.2.0 from snmp agent of device at specific interval.
Device on which Frequency operating is sent to device application 

"""
# ######################################################################
# Function: check_wimax_p1_mrc_stc_invent
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################


def live_query_p1_mrc_stc(host_name):
        """
        Connects to a socket, checks for the WELCOME-MSG and closes the
        connection.
        Returns nothing.

        """
        exit_value = 3
        pmp1_mrc, pmp1_stc = '', ''
        try:
                query_string = "GET services\nColumns: plugin_output\nFilter: " + \
                                "service_description = %s\nFilter: host_name = %s\nOutputFormat: python\n" % ("wimax_aggregate_bs_params",host_name)

                query_output = eval(get_from_socket(None,None,query_string,nagios_user,None).strip())
                if query_output[0][0]:
                        plugin_output = str(query_output[0][0].split('OK - ')[1])
                        plugin_output = [entry for entry in plugin_output.split()]
                        pmp1_mrc, pmp1_stc = plugin_output[13].split('=')[1], plugin_output[14].split('=')[1]

        except:
                pass
        return pmp1_mrc, pmp1_stc


def check_wimax_p1_mrc_stc_invent(item, _no_params, info):
    """
            check_wimax_p1_mrc_stc_invent function calcdlates the operating ptx

            Args:
                    item (str) Specific item on SNMP output on which we want to filter resdlts

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - 5835

                    Raises:
                            ValueError ,Exception
"""
    state = 3
    infotext = "unknown_value"
    pmp1_mrc, pmp1_stc = '', ''
    try:
        pmp1_mrc, pmp1_stc = live_query_p1_mrc_stc(g_hostname)
	if pmp1_mrc or pmp1_stc:
		infotext = "pmp1_mrc=%s pmp1_stc=%s" % (pmp1_mrc,pmp1_stc)
		state = 0
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"

    return (state, infotext)


check_info["wimax_p1_mrc_stc_invent"] = {
    'check_function': check_wimax_p1_mrc_stc_invent,
    'service_description': 'wimax_p1_mrc_stc_invent',
}

#########################################################################
#	SNMP OID for the operating ptx
#########################################################################
snmp_info["wimax_p1_mrc_stc_invent"] = ( ".1.3.6.1.4.1.5812.2000.4.1.1", ["1.0"] )
