#!/usr/bin/python

import sys
import os

"""
# ######################################################################
# Function: wimax_ss_appln_version_invent
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################

"""

def wimax_ss_appln_version_invent(item, _no_params, info):
    """
            wimax_ss_appln_version_invent function calcdlates the operating ptx

            Args:
                    item (str) Specific item on SNMP output on which we want to filter resdlts

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - 5835

                    Raises:
                            ValueError ,Exception
"""
    state = 3
    infotext = "unknown_value"
    version= None
    try:
	version = info[0][0]
	if version:
		infotext = "%s" % version
		state = 0
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"

    return (state, infotext,[("ss_appln_version", version)])


check_info["wimax_ss_appln_version_invent"] = {
    'check_function': wimax_ss_appln_version_invent,
    'service_description': 'wimax_ss_appln_version_invent',
    'has_perfdata' : True,
}

#########################################################################
#	SNMP OID for the operating ptx
#########################################################################
snmp_info["wimax_ss_appln_version_invent"] = ( ".1.3.6.1.2.1.47.1.1.1.1.10", ["1"] )
