#!/usr/bin/python
"""
service on BS,which calculates the bs ip through which it is connected.

This is part of device application. 
Poller script determines the bs ip. 
poller script takes the snmp value of OID  1.3.6.1.4.1.161.19.3.3.1.13.0 from snmp agent of device at specific interval.
BS ip information is sent to device application 

"""
# ######################################################################
# Function : check_cambium_crc_errors
#
# Parameters: info (SNMP Output) _no_params(No Parameters)
#
# Output: service state and plugin output
# #####################################################################

def check_radwin_crc_errors(item, _no_params, info):
    """
                check_cambium_crc_errors function calculates the idu serial number

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : OK - BB1202020

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    crc_errors = None
    try:
        if info:
            if info[0][0]:
                crc_errors = info[0][0]
                state = 0
                infotext = "%s" % crc_errors
    except:
        infotext = "unknown_value"
    return (state, infotext,[("crc_errors",crc_errors)])


check_info["radwin_crc_errors"] = {
    'check_function': check_radwin_crc_errors,
    'service_description': 'radwin_crc_errors',
    'has_perfdata' : True,
}

#################################################################
#SNMP OID value for poller script
################################################################

snmp_info["radwin_crc_errors"] = ( ".1.3.6.1.2.1.2.2.1", ["14.1"] )
