#!/usr/bin/python
"""
Radwin ODU serial number type Poller script.

Poller script determines the radwin product type.
poller script takes the snmp value of OID .1.3.6.1.4.1.4458.1000.1.1.29 from snmp agent of device at specific interval.
Radwin ODU serial number information is sent to device application 

"""
# ####################################################################
# Function : check_radwin_odu_sn_invent
#
# Parameters: info (SNMP output ) _no_params (NO params)
#
# Output: service state and plugin output
# ###################################################################


def check_radwin_odu_sn_invent(item, _no_params, info):
    """
                check_radwin_odu_sn_invent function calculates the device odu serial number

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : BIN500I500000291
                        Raises:
                                Exception
    """
    state = 3
    infotext = "unknown_value"
    try:
        if info:
            if info[0][0]:
                odu_sn = info[0][0]
                state = 0
                infotext = "%s" % odu_sn
    except:
        infotext = "unknown value"
    return (state, infotext)


check_info["radwin_odu_sn_invent"] = {
    'check_function': check_radwin_odu_sn_invent,
    'service_description': 'radwin_odu_sn_invent',
}

####################################################################
#		SNMP OID
#####################################################################
snmp_info["radwin_odu_sn_invent"] = ( ".1.3.6.1.4.1.4458.1000.1", ["1.29"] )
