#!/usr/bin/python

"""
operating Frequency of device  Poller script.

This is part of device application. 
Poller script determines the operating frequency of device. 
poller script takes the snmp value of OID .1.3.6.1.4.1.4458.1000.1.5.16 from snmp agent of device at specific interval.
Device on which Frequency operating is sent to device application 

"""
# ######################################################################
# Function: check_radwin_frequency
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################


def check_radwin_frequency(item, _no_params, info):
    """
            check_radwin_frequency function calculates the operating frequency

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - 5835

                    Raises:
                            ValueError ,Exception
"""
    state = 3
    infotext = "unknown_value"
    frequency = None
    try:
        if info:
            if info[0][0]:
                frequency = int(info[0][0])
                if frequency < 0:
                    state = 0
                    infotext = "invalid_value_%d" % frequency
                else:
                    state = 0
                    infotext = "%.3f" % frequency
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"
    return (state, infotext,[("frequency",frequency)])


check_info["radwin_frequency"] = {
    'check_function': check_radwin_frequency,
    'service_description': 'radwin_frequency',
    'has_perfdata': True    
}

#########################################################################
#	SNMP OID for the operating frequency
#########################################################################
snmp_info["radwin_frequency"] = ( ".1.3.6.1.4.1.4458.1000.1", ["5.16"] )
