#!/usr/bin/python2
# -*- coding: utf-8 -*-
#~ Author: Silvio Knizek
#~ License: GPLv2
#~ Version: 1.0

import sys
from telnetlib import Telnet
import socket
import json
import os


import mysql.connector

def mysql_conn():
        db = mysql.connector.connect(
                        user='root',
                        host='10.133.12.163',
                        password='root',
                        database='nocout_24_09_14',
                        port=3200)

        return db

def extract_host_from_wimax_topology(ss_host_mac):
        query = """
        select device_name from performance_topology where connected_device_mac ='%s' """ %(ss_host_mac)
        db = mysql_conn()
        cur = db.cursor()
        cur.execute(query)
        data = cur.fetchall()
        cur.close()

        return data






def get_from_socket(socket_ip,socket_port ,query):
    """
    Function_name : get_from_socket (collect the query data from the socket)

    Args: site_name (poller on which monitoring data is to be collected)

    Kwargs: query (query for which data to be collectes from nagios.)

    Return : None

    raise 
         Exception: SyntaxError,socket error 
    """
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect((socket_ip,socket_port))
    s.send(query)
    s.shutdown(socket.SHUT_WR)
    output = s.recv(100000000)
    output.strip("\n")
    return output


def live_query_dl_cinr(socket_ip,socket_port,mac,warn,crit):
	"""
    	Connects to a socket, checks for the WELCOME-MSG and closes the
    	connection.
    	Returns nothing.
    
    	"""
	exit_value = 3
	plugin_message = ''
	dl_cinr_state = "UNKNOWN"
	dl_cinr = ''
	perf = ''
	host_name = extract_host_from_wimax_topology(mac)
	try:
		if host_name[0][0]:
			query_string = "GET services\nColumns: plugin_output\nFilter: " + \
                        	"service_description = %s\nFilter: host_name = %s\nOutputFormat: json\n" % ("wimax_topology",host_name[0][0])
        		query_output = json.loads(get_from_socket(socket_ip,socket_port,query_string).strip())
			if query_output[0][0]:
				plugin_output = str(query_output[0][0].split('OK-')[1])
				plugin_output = [entry for entry in plugin_output.split(' ')]
				entry=filter(lambda x: mac in x, plugin_output)
				dl_cinr = int(entry[0].split('=')[1].split(',')[2])
				if dl_cinr:
					perf += 'dl_cinr' + "=%s" %(dl_cinr)
					if dl_cinr  < crit:
                                        	exit_value = 2
						dl_cinr_state = "CRIT"
                                	elif dl_cinr >= crit and dl_cinr <= warn:
                                        	exit_value =1
						dl_cinr_state = "WARNING"
                                	else:
                                        	exit_value = 0
						dl_cinr_state = "OK"
 
	except:
		dl_cinr_state = "UNKNOWN1"

	plugin_message += "wimax_dl_cinr %s - %s |%s" % (dl_cinr_state,dl_cinr,perf) 
	sys.stdout.write(plugin_message)  
	sys.exit((exit_value))

def main():
    exit_value =3
    try:
	socket_ip = sys.argv[1]
	socket_port = sys.argv[2]
	mac = sys.argv[3]
	warn = sys.argv[4]
	crit =sys.argv[5]
        live_query_dl_cinr(socket_ip,int(socket_port),mac,int(warn),int(crit))
    except socket.error, message:
        sys.stdout.write("Could not open socket: " + message) 
        sys.exit((exit_value))


if __name__ == '__main__':
    main()
