#!/usr/bin/python

import sys
from telnetlib import Telnet
import socket
import json
import os

"""
operating Frequency of ss device  Poller script.

This is part of device application. 
Poller script determines the operating ptx of device. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.1.1.2.0 from snmp agent of device at specific interval.
Device on which Frequency operating is sent to device application 

"""
# ######################################################################
# Function: check_mrotek_port_speed_status
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################


def connection_telnet_for_port_speed_status(hostip, port,num_port):
        """
        Connects to a socket, checks for the WELCOME-MSG and closes the
        connection.
        Returns nothing.
    
        """
        try:
                tn = Telnet(hostip,port,timeout=3)
        except socket.timeout:
		pmp1_bw = None
		pmp2_bw = None
		return pmp1_bw,pmp2_bw
	tn.read_until("Login:")
        tn.write("admin" + "\r\n")
        tn.read_until("Password:")
        tn.write("admin" + "\r\n")
	for item in range(1,num_port):
        	tn.write("show interface client %s\r\n" % (item+1))
        tn.write("exit\r\n")
        data = tn.read_all()
	port_speed = None
	try:
		 for i,row in enumerate(data.split("\n")):
                        if "c:%s" % item in row:
				port_speed = int([r for r in row.split()])
				port_speed = port_speed[3].split('/')[0]
				break
        except:
		port_speed = None
	return port_speed
                                

def check_mrotek_port_speed_status(item, _no_params, info):
    """
            check_mrotek_port_speed_status function calcdlates the operating ptx

            Args:
                    item (str) Specific item on SNMP output on which we want to filter resdlts

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - 5835

                    Raises:
                            ValueError ,Exception
    """
    state = 3
    infotext = "unknown_value"
    port_speed = None
    status_list = []
    try:
	if info[0][0]:
                ip = info[0][0]
	        num_port = len(info)	
		status_list =connection_telnet_for_port_speed_status(ip, 23,num_port)
		for port,speed in status_list:
			infotext = "%s=%s" % (port,speed)
		state = 0
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"

    return (state, infotext,status_list)


check_info["mrotek_port_speed_status"] = {
    'check_function': check_mrotek_port_speed_status,
    'service_description': 'mrotek_port_speed_status',
    'has_perfdata' : True,
}

#########################################################################
#	SNMP OID for the operating ptx
#########################################################################
snmp_info["mrotek_port_speed_status"] = ( ".1.3.6.1", ["2.1.4.20.1.1","4.1.8886.6.1.4.1.1.6"] )

