#!/usr/bin/python
"""
IDU serial number Poller script.

This is part of device application. 
Poller script determines the serial number of IDU. 
poller script takes the snmp value of OID .1.3.6.1.4.1.4458.1000.2.1.6 from snmp agent of device at specific interval.
IDU serial number of IDU is sent to device application 

"""
# ######################################################################
# Function : check_mrotek_device_type
#
# Parameters: info (SNMP Output) _no_params(No Parameters)
#
# Output: service state and plugin output
# #####################################################################

def check_mrotek_device_type(item, _no_params, info):
    """
                check_mrotek_device_type function calculates the idu serial number

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : OK - BB1202020

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    try:
        if info:
            if info[0][0]:
                device_type = info[0][0]
                state = 0
                infotext = "%s" % device_type
    except:
        infotext = "unknown_value"
    return (state, infotext,[("device_type",device_type)])


check_info["mrotek_device_type"] = {
    'check_function': check_mrotek_device_type,
    'service_description': 'mrotek_device_type',
    'has_perfdata': True,
}

#################################################################
#SNMP OID value for poller script
################################################################

snmp_info["mrotek_device_type"] = ( ".1.3.6.1.2.1.1", ["1.0"] )
