#!/usr/bin/python

import sys
from telnetlib import Telnet
import socket
import json
import os

"""
operating Frequency of ss device  Poller script.

This is part of device application. 
Poller script determines the operating ptx of device. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.1.1.2.0 from snmp agent of device at specific interval.
Device on which Frequency operating is sent to device application 

"""
# ######################################################################
# Function: check_mrotek_port_duplex
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################


def connection_telnet_for_pmp_bw(hostip, port ,item):
        """
        Connects to a socket, checks for the WELCOME-MSG and closes the
        connection.
        Returns nothing.
    
        """
        try:
                tn = Telnet(hostip,port,timeout=3)
        except socket.timeout:
		pmp1_bw = None
		pmp2_bw = None
		return pmp1_bw,pmp2_bw
	tn.read_until("Login:")
        tn.write("admin" + "\r\n")
        tn.read_until("Password:")
        tn.write("admin" + "\r\n")
        tn.write("show interface client %s\r\n" % item)
        tn.write("exit\r\n")
        data = tn.read_all()
	port_duplex = None
	try:
		 for i,row in enumerate(data.split("\n")):
                        if "c:%s" % item in row:
				port_duplex = int([r for r in row.split()])
				port_duplex = port_duplex[3].split('/')[1]
				break
        except:
		port_duplex = None
	return port_duplex
                                

def check_mrotek_port_duplex(item, _no_params, info):
    """
            check_mrotek_port_duplex function calcdlates the operating ptx

            Args:
                    item (str) Specific item on SNMP output on which we want to filter resdlts

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - 5835

                    Raises:
                            ValueError ,Exception
    """
    state = 3
    infotext = "unknown_value"
    port_duplex = None
    try:
	if info[1]:
                ip = info[1][0]
                if bs_ip:
                	port_duplex =connection_telnet_for_port_duplex_status(ip, 23,item)
			if port_duplex:
				infotext = "port_duplex=%s" % (port_duplex)
				state = 0
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"

    return (state, infotext,[("duplex",port_duplex)])


check_info["mrotek_port_duplex"] = {
    'check_function': check_mrotek_port_duplex,
    'service_description': 'mrotek_port_duplex',
    'has_perfdata' : True,
}

#########################################################################
#	SNMP OID for the operating ptx
#########################################################################
snmp_info["mrotek_port_duplex"] = ( ".1.3.6.1.4.1.5812.2000.4.1.1", ["1.0"] )
