#!/usr/bin/python

import sys
from telnetlib import Telnet
import socket
import json
import os

import mysql.connector
"""
operating Frequency of ss device  Poller script.

This is part of device application. 
Poller script determines the operating ptx of device. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.1.1.2.0 from snmp agent of device at specific interval.
Device on which Frequency operating is sent to device application 

"""
# ######################################################################
# Function: check_wimax_dl_cinr
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################


def extract_host_from_wimax_topology(ss_host_mac):
        query = """
        select device_name,site_name from performance_topology where connected_device_mac ='%s' """ %(ss_host_mac)
        db = mysql_conn()
        cur = db.cursor()
        cur.execute(query)
        data = cur.fetchall()
        cur.close()

        return data



def live_query_dl_cinr(mac):
        """
        Connects to a socket, checks for the WELCOME-MSG and closes the
        connection.
        Returns nothing.
    
        """
        exit_value = 3
        dl_cinr = None
        host_name = extract_host_from_wimax_topology(mac)
        try:
                if host_name[0][0]:
                        query_string = "GET services\nColumns: plugin_output\nFilter: " + \
                                "service_description = %s\nFilter: host_name = %s\nOutputFormat: json\n" % ("wimax_topology",host_name[0][0])
			
			site = host_name[0][1]
                        machine_name = host_name[0][1].split('_')[0]
                        socket_ip = _LIVESTATUS[machine_name]['host']
                        socket_port = _LIVESTATUS[machine_name][site]['port']
                        
			query_output = json.loads(get_from_socket(socket_ip,socket_port,query_string).strip())
                        if query_output[0][0]:
                                plugin_output = str(query_output[0][0].split('OK-')[1])
                                plugin_output = [entry for entry in plugin_output.split(' ')]
                                entry=filter(lambda x: mac in x, plugin_output)
                                dl_cinr = int(entry[0].split('=')[1].split(',')[2])

	except:
                dl_cinr= None
        return dl_cinr



def check_wimax_dl_cinr(item, params, info):
    """
            check_wimax_dl_cinr function calcdlates the operating ptx

            Args:
                    item (str) Specific item on SNMP output on which we want to filter resdlts

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - 5835

                    Raises:
                            ValueError ,Exception
"""
    state = 3
    infotext = "unknown_value"
    warn,crit = params
    dl_cinr = None
    try:
	if info[0][2]:
                ss_mac = info[0][2]
		a=binascii.b2a_hex(ss_mac)
		n = 2
		ss_mac=(':').join([a[i:i+2] for i in range(0, len(a), n)])
                if ss_mac:
                        dl_cinr = live_query_dl_cinr(ss_mac )
                        if isinstance(dl_cinr,int):
                                if dl_cinr < crit:
                                        state  = 2
                                elif dl_cinr >= crit and dl_cinr <= warn:
                                        state = 1
                                else:
                                        state = 0
        			infotext = "Device downlink cinr  is %s " % dl_cinr
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"

    return (state, infotext, [("dl_cinr", dl_cinr, warn, crit)])


check_info["wimax_dl_cinr"] = {
    'check_function': check_wimax_dl_cinr,
    'service_description': 'wimax_dl_cinr',
    'has_perfdata' : True,
}

#########################################################################
#	SNMP OID for the operating ptx
#########################################################################
snmp_info["wimax_dl_cinr"] = ( ".1.3.6.1.2.1.10.184.1.3.1.1.1", ["17.1"] )
