#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def check_wimax_ss_sector_id_arguments(params):
    description,settings = params
    args =''
    if "socket_address" in settings:
        args += '%s ' % quote_shell_string(settings['socket_address'])
    if "socket_port" in settings:
        args += '%d ' % int(settings['socket_port'])
    if "mac" in settings:
        args += '%s ' % quote_shell_string(settings['mac'])


    return args

active_check_info['wimax_ss_sector_id'] = {
    "command_line"        : '$USER1$/check_wimax_ss_sector_id $ARG1$',
    "argument_function"   : check_wimax_ss_sector_id_arguments,
    "service_description" : lambda params: "%s" % params[0],
    "has_perfdata"        :True,
}

