#!/usr/bin/python2
# -*- coding: utf-8 -*-
#~ Author: Silvio Knizek
#~ License: GPLv2
#~ Version: 1.0

import sys
from telnetlib import Telnet
import socket

def connection_telnet(hostname, port,mac):
	"""
    	Connects to a socket, checks for the WELCOME-MSG and closes the
    	connection.
    	Returns nothing.
    
    	"""
	try:
    		tn = Telnet(hostname,port,timeout=3)
	except socket.timeout:
		exit_value = 3
                show_runnin_config_state = "show_runnin_config UNKNOWN"
		sys.stdout.write("UNKNOWN Output")
		sys.exit((exit_value))
    	tn.read_until("Login:")
    	tn.write("admin" + "\r\n")
    	tn.read_until("Password:")
    	tn.write("admin" + "\r\n")
    	tn.write("show connectivity ss %s\r\n" % mac)
    	tn.write("exit\r\n")
    	data = tn.read_all()
    	plugin_message= ""
    	exit_value = 3


	ss_ip_state = "UNKNOWN"
	try:
		for i,row in enumerate(data.split("\n")):
			if "IP Address:" in row:
				params_list = [r for r in row.split()]
				ss_ip = params_list[4]
				exit_value = 0
				ss_ip_state = "OK"
				break
	except:
		exit_value = 3		
	plugin_message += "wimax_ss_ip %s - %s " % (ss_ip_state,ss_ip)
	sys.stdout.write(plugin_message)  
	sys.exit((exit_value))

def main():
    """
    Parses the time it needs to got the WELCOME-MSG and returns:
    0:  all got well
    1:  connection is slow
    2:  nio connection at all (or really slow)
    3:  something really bad happend
    
    """
    exit_value =3
    try:
	host_name = sys.argv[1]
	mac= sys.argv[2]
        connection_telnet(host_name, 23,mac)
    except socket.error, message:
        sys.stdout.write("Could not open socket: " + message) 
        sys.exit((exit_value))


if __name__ == '__main__':
    main()
