#!/usr/bin/python2
# -*- coding: utf-8 -*-

import sys
from telnetlib import Telnet
import socket
import json
import os


def get_from_socket(socket_ip,socket_port, query):
    """
    Function_name : get_from_socket (collect the query data from the socket)

    Args: site_name (poller on which monitoring data is to be collected)

    Kwargs: query (query for which data to be collectes from nagios.)

    Return : None

    raise 
         Exception: SyntaxError,socket error 
    """
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect((socket_ip,socket_port))
    s.send(query)
    s.shutdown(socket.SHUT_WR)
    output = s.recv(100000000)
    output.strip("\n")
    return output


def live_query_ul_rssi(host_name, socket_ip,socket_port,mac,warn,crit):
	"""
    	Connects to a socket, checks for the WELCOME-MSG and closes the
    	connection.
    	Returns nothing.
    
    	"""
	exit_value = 3
	plugin_message = ''
	ul_rssi_state = "UNKNOWN"
	ul_rssi = ''
	perf = ''
	try:
		query_string = "GET services\nColumns: plugin_output\nFilter: " + \
                        "service_description = %s\nFilter: host_name = %s\nOutputFormat: json\n" % ("bs_show_ss",host_name)
        	query_output = json.loads(get_from_socket(socket_ip,socket_port,query_string).strip())
		if query_output[0][0]:
			plugin_output = str(query_output[0][0].split('OK-')[1])
			plugin_output = [entry for entry in plugin_output.split(' ')]
			entry=filter(lambda x: mac in x, plugin_output)
			ul_rssi = int(entry[0].split('=')[1].split(',')[1])
			if ul_rssi:
				perf += 'ul_rssi' + "=%s" %(ul_rssi) 
				if ul_rssi < crit:
					ul_rssi_state = "CRITICAL"
					exit_value  = 2 
                                elif ul_rssi > crit and ul_rssi < warn:
					ul_rssi_state = "WARNING"
					exit_value = 1
				else:
					ul_rssi_state = "OK"
					exit_value = 0	
	except:
		ul_rssi_state = "UNKNOWN1"

	plugin_message += "wimax_ul_rssi %s - %s |%s" % (ul_rssi_state,ul_rssi,perf) 
	sys.stdout.write(plugin_message)  
	sys.exit((exit_value))

def main():
    exit_value =3
    try:
	host_name = sys.argv[1]
	socket_ip = sys.argv[2]
        socket_port = sys.argv[3]
	mac = sys.argv[4]
	warn = sys.argv[5]
	crit =sys.argv[6]
        live_query_ul_rssi(host_name, socket_ip,int(socket_port),mac,int(warn),int(crit))
    except socket.error, message:
        sys.stdout.write("Could not open socket: " + message) 
        sys.exit((exit_value))


if __name__ == '__main__':
    main()
