#!/usr/bin/python

# ######################################################################
# Function: check_rad5k_dl_mod_invent
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################

def check_rad5k_dl_mod_invent(item, _no_params, info):
    """
            check_rad5k_dl_mod_invent function calculates the uplink utilization

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                                    3: unknown
                    infotext(string):
                                    plugin output
                                    Example :  OK - dl modulatino change: 107 

                    Raises:
                            ValueError ,Exception

    """ 

    state = 3
    infotext = "unknown_value"
    dl_mod = ""
        
    try:
        if info:
            if info[0][0]:
		dl_mod = int(info[0][0])
                state = 0
                infotext = "dl modulatino change: %d" % dl_mod                                
    except ValueError :
	infotext = "type_mismatch_value"
    except:
	infotext = "unknown_value"
		
    return (state,infotext,[("dl_modulation_change",dl_mod)])
                
check_info["rad5k_dl_mod_invent"] = {
    'check_function' :  check_rad5k_dl_mod_invent,
    'service_description' : "rad5k_dl_mod_invent",
    'has_perfdata': True
}
#########################################################################
#       SNMP OID for the downlink modulation
#########################################################################
snmp_info['rad5k_dl_mod_invent'] = (".1.3.6.1.4.1.4458.1000.1.5.9",["5.0"])

