#!/usr/bin/python
# ######################################################################
# Function: check_rad5k_odu_type_invent
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################

def check_rad5k_odu_type_invent(item, _no_params, info):
	
    """
            check_rad5k_odu_type_invent function calculates the uplink utilization

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                                    3: unknown
                    infotext(string):
                                    plugin output
                                    Example :  OK - odu_type: RW-5050-4B58

                    Raises:
                            ValueError ,Exception

    """ 
    state = 3
    infotext = "unknown_value"
    odu_type = ""        
    try:
        if info:
            if info[0][0]:
		str1 = info[0][0]
		str1 = str1.split(' - ')
		odu_type = str1[1]
		state = 0
                infotext = "odu_type: %s" % odu_type                                 
    except ValueError :
		infotext = "type_mismatch_value"
    except:
		infotext = "unknown_value"
		
    return (state,infotext,[("odu_type",odu_type)])
                
check_info["rad5k_odu_type_invent"] = {
    'check_function' :  check_rad5k_odu_type_invent,
    'service_description' : "rad5k_odu_type_invent",
    'has_perfdata': True
}
#########################################################################
#       SNMP OID for the ODU Type
#########################################################################
snmp_info['rad5k_odu_type_invent'] = (".1.3.6.1.4.1.4458.1000.1.1",["30.0"])
