#!/usr/bin/python
# ######################################################################
# Function: check_rad5k_ss_ip
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################

def check_rad5k_ss_ip(item, _no_params, info):
    """
            check_rad5k_ss_ip function calculates the uplink utilization

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                                    3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - ip: 10.169.241.16

                    Raises:
                            ValueError ,Exception

    """ 
    state = 3
    infotext = "unknown_value"
    ip = ""        
    try:
        if info:
            if info[0][0]:
		string = info[0][0]
		string =  string.split("|")
		ip = string[0]
                state = 0
                infotext = "ip: %s" % ip                                
    except ValueError :
	infotext = "type_mismatch_value"
    except:
	infotext = "unknown_value"
		
    return (state,infotext,[("ss_ip",ip)])
                
check_info["rad5k_ss_ip"] = {
    'check_function' :  check_rad5k_ss_ip,
    'service_description' : "rad5k_ss_ip",
    'has_perfdata': True
}
#########################################################################
#       SNMP OID for HSU IP
#########################################################################
snmp_info['rad5k_ss_ip'] = (".1.3.6.1.4.1.4458.1000.1.1",["26.0"])
