#!/usr/bin/python
import time
import memcache 
import binascii
from mysql_connection import memc

# ##################################################################
# Function : check_rad5k_bs_dl_utilization
#
#  Parameters: info(SNMP output) ,params(parameters to check the service state) 
#
#  Output: service state,plugin output ,performance data
##################################################################


def check_rad5k_bs_dl_utilization(item, _no_params, info):
	"""
            check_rad5k_bs_dl_utilization function calculates the downlink utilization

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                		    3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - Downlink utilization 0.06

                    Raises:
                            ValueError ,Exception
	"""
	state = 3
	infotext = "unknown_value"
	status_list = [] 
	rate = None
	wrapped =False
	try:
		if info:
			status_list = []
			if info[0][0]:
				#print  info[0][0]
				dl_utilization = int(info[0][0]) / (1024.0)
				status_list.append(("dl_utilization", "%.2f" % (dl_utilization)))
                                infotext = "Downlink utilization %.2f " % (dl_utilization)
                                state= 0
				key = g_hostname + "_dl"
				try:
					if memc:
						memc.set(key,"%.2f" % dl_utilization)
				except :
					pass
					

		else:
	    		infotext = "No interface present"
	    
	except ValueError:
		infotext = "type_mismatch_value"
	except:
        	infotext = "unknown_value"
	if wrapped:
        	infotext = "Counter wrapped"
    
	return (state, infotext, status_list)


check_info["rad5k_bs_dl_utilization"] = {
    'check_function': check_rad5k_bs_dl_utilization,
    'service_description': 'rad5k_bs_dl_utilization',
    'has_perfdata': True,
}

#######################################################################
#	SNMP OID FOR BS DOWNLINK UTILIZATION
#######################################################################
snmp_info["rad5k_bs_dl_utilization"] = ( ".1.3.6.1.4.1.4458.1000.3.1", ["16.0"] ) 
