#!/usr/bin/python
# ######################################################################
# Function: check_rad5k_ss_dl_uas
#
# Parameters: info (SNMP Ouput) params (1,5)
#
# Output: service state ,plugin output
# ######################################################################

def check_rad5k_ss_dl_uas(item, params, info):
    """
            check_rad5k_ss_dl_uas function calculates the uplink utilization

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                                    3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - seconds: 0

                    Raises:
                            ValueError ,Exception

    """ 
    state = 3
    infotext = "unknown_value"
    seconds = ""
    try:
        war , crit = params
    except ValueError :
    	war = 1
	crit = 5
    try:
        if info:
            if info[0][0]:
		seconds = int(info[0][0])
		if seconds > war and seconds < crit:
			state = 1
			infotext = "seconds: %d" % seconds   
		elif seconds > crit:
			state = 2
			infotext = "seconds: %d" % seconds  
		elif seconds == 0 :
	               state = 0
	               infotext = "seconds: %d" % seconds                             
    except ValueError :
	infotext = "type_mismatch_value"
    except:
	infotext = "unknown_value"
		
    return (state,infotext,[("dl_uas",seconds,war,crit)])
                
check_info["rad5k_ss_dl_uas"] = {
    'check_function' :  check_rad5k_ss_dl_uas,
    'service_description' : "rad5k_ss_dl_uas",
    'has_perfdata': True
}
#########################################################################
#       SNMP OID for the downlink Uas
#########################################################################
snmp_info['rad5k_ss_dl_uas'] = (".1.3.6.1.4.1.4458.1000.1.6.1.1",["1.1"])
