#!/usr/bin/python

# ######################################################################
# Function: check_rad5k_ss_transmit_power
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################

def check_rad5k_ss_transmit_power(item, _no_params, info):
    """
            check_rad5k_ss_transmit_power function calculates the uplink utilization

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                                    3: unknown
                    infotext(string):
                                    plugin output
                                    Example :  OK - transmit_power: 15

                    Raises:
                            ValueError ,Exception

    """ 
    state = 3
    infotext = "unknown_value"
    transmit_power = ""
        
    try:
        if info:
            if info[0][0]:
                transmit_power = int(info[0][0])                      
                state = 0
                infotext = "transmit_power: %d" % transmit_power
    except ValueError :
	infotext = "type_mismatch_value"
    except:
	infotext = "unknown_value"
		
    return (state,infotext,[("transmit_power",transmit_power)])
                
check_info["rad5k_ss_transmit_power"] = {
    'check_function' :  check_rad5k_ss_transmit_power,
    'service_description' : "rad5k_ss_transmit_power",
    'has_perfdata': True
}
#########################################################################
#       SNMP OID for the Transmit power
#########################################################################
snmp_info['rad5k_ss_transmit_power'] = (".1.3.6.1.4.1.4458.1000.1.5",["12.0"])

