#!/usr/bin/python

# ######################################################################
# Function: check_rad5k_bs_crc_error_invnet
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################

def check_rad5k_ss_crc_error_status(item, _no_params, info):
    """
            check_rad5k_ss_crc_error_status function calculates the uplink utilization

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                                    3: unknown
                    infotext(string):
                                    plugin output
                                    Example :  OK - crc errors: 5

                    Raises:
                            ValueError ,Exception

    """ 
    state = 3
    infotext = "unknown_value"
    crc_errors = ""

        
    try:
        if info:
            if info[0][0]:
		crc_errors = info[0][0]
                state = 0
                infotext = "crc errors: %s"%crc_errors                                
    except ValueError :
	infotext = "type_mismatch_value"
    except:
	infotext = "unknown_value"
		
    return (state,infotext,[("crc_errors",crc_errors)])
                
check_info["rad5k_ss_crc_error_status"] = {
    'check_function' :  check_rad5k_ss_crc_error_status,
    'service_description' : "rad5k_ss_crc_error_status",
    'has_perfdata': True
}
#########################################################################
#       SNMP OID for the Crc Error
#########################################################################

snmp_info['rad5k_ss_crc_error_status'] = (".1.3.6.1.2.1.2.2.1",["14.1"])
