#!/usr/bin/python

# ######################################################################
# Function: check_rad5k_bs_sync_vlan_invent
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################

def check_rad5k_bs_sync_vlan_invent(item, _no_params, info):
    """
            check_rad5k_ss_man_vlan function calculates the uplink utilization

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                                    3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - port: 2309 

                    Raises:
                            ValueError ,Exception

    """ 

    state = 3
    infotext = "unknown_value"
    port = ""
        
    try:
        if info:
            if info[0][0]:
		port = info[0][0]
		port = port[0:4]
                state = 0
                infotext = "port: %s" % port                                
    except ValueError :
	infotext = "type_mismatch_value"
    except:
	infotext = "unknown_value"
		
    return (state,infotext,[("bs_sync_vlan",port)])
                
check_info["rad5k_bs_sync_vlan_invent"] = {
    'check_function' :  check_rad5k_bs_sync_vlan_invent,
    'service_description' : "rad5k_bs_sync_vlan_invent",
    'has_perfdata': True
}
#########################################################################
#       SNMP OID for the Management Vlan port
#########################################################################
snmp_info['rad5k_bs_sync_vlan_invent'] = (".1.3.6.1.4.1.4458.1000.1.5.40.31",["0"])

