#!/usr/bin/python

import sys
import os
from mysql_connection import memc
"""
# ######################################################################
# Function: radwin_bs_software_dl_modulation_invent
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################

"""

def rad5k_ss_dl_modulation(item, _no_params, info):
    """
            radwin_bs_software_dl_modulation_invent function calcdlates the operating ptx

            Args:
                    item (str) Specific item on SNMP output on which we want to filter resdlts

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - 5835

                    Raises:
                            ValueError ,Exception
"""
    state = 3
    infotext = "unknown_value"
    dl_modulation= None
    rad5k_dl_mod_invent_convert_dict = {007:'64QAM-FEC-5/6', 107:'64QAM-FEC-5/6', 207:'64QAM-FEC-5/6', 006: '64QAM-FEC-3/4', 106: '64QAM-FEC-3/4', 206: '64QAM-FEC-3/4', 005: '64QAM-FEC-2/3', 105:'64QAM-FEC-2/3', 205:'64QAM-FEC-2/3', 004:'16QAM-FEC-3/4', 104: '16QAM-FEC-3/4', 204: '16QAM-FEC-3/4', 003:'16QAM-FEC-1/2', 103:'16QAM-FEC-1/2', 203:'16QAM-FEC-1/2',002:'QPSK-FEC-3/4', 102:'QPSK-FEC-3/4', 202:'QPSK-FEC-3/4', 001:'QPSK-FEC-1/2', 101:'QPSK-FEC-1/2', 201:'QPSK-FEC-1/2', 000:'BPSK-FEC-1/2', 100:'BPSK-FEC-1/2', 200:'BPSK-FEC-1/2' }
    try:
	serial_number = info[0][0]
	if serial_number:
	        if memc:
	                key = serial_number + "_param"
        	        value_list = memc.get(key)
                	if value_list:
                        	try:
                                	dl_mod = value_list[15]
                                	dl_modulation = rad5k_dl_mod_invent_convert_dict.get(int(dl_mod),'')
                        	except:
                                	dl_modulation = None

		infotext = "DL Modulation is %s" % dl_modulation
		state = 0
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"

    return (state, infotext,[("dl_modulation", dl_modulation)])


check_info["rad5k_ss_dl_modulation"] = {
    'check_function': rad5k_ss_dl_modulation,
    'service_description': 'rad5k_ss_dl_modulation',
    'has_perfdata' : True,
}

#########################################################################
#	SNMP OID for the operating ptx
#########################################################################
snmp_info["rad5k_ss_dl_modulation"] = ( ".1.3.6.1.4.1.4458.1000.1.1", ["29.0"] )
