#!/usr/bin/python
# ######################################################################
# Function: check_rad5k_gps_sync_invent
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################
dic_sync = { 
	1 : 'notSupported',
	2 : 'independentUnin',
	3 : 'hubSyncMaster',
	4 : 'hubSyncClientContinueTx',
	5 : 'hubSyncClientDisableTx',
	6 : 'gpsSync',
	7: 'independentSyncUnit-ISU'}
		
def check_rad5k_gps_sync_invent(item, _no_params, info):
    """
            check_rad5k_gps_sync_invent function calculates the uplink utilization

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                                    3: unknown
                    infotext(string):
                                    plugin output
                                    Example :  OK - gps sync : hubSyncClientContinueTx

                    Raises:
                            ValueError ,Exception

    """
    state = 3
    infotext = "unknown_value"
    sync = ""        
    try:
        if info:
            if info[0][0]:
		x = int(info[0][0])
		if dic_sync.get(x):					
			sync = dic_sync.get(x)
			state = 0
			infotext = "gps sync : %s " % sync
    except ValueError :
	infotext = "type_mismatch_value"
    except:
	infotext = "unknown_value"
		
    return (state,infotext,[("site_sync_state",sync)])
                
check_info["rad5k_gps_sync_invent"] = {
    'check_function' :  check_rad5k_gps_sync_invent,
    'service_description' : "rad5k_gps_sync_invent",
    'has_perfdata': True
}
#########################################################################
#       SNMP OID for the MASTER-SLAVE GPS SYNC	
#########################################################################
snmp_info['rad5k_gps_sync_invent'] = (".1.3.6.1.4.1.4458.1000.1.5.40",["2.0"])
