#!/usr/bin/python

import sys
import os
from mysql_connection import memc
"""
# ######################################################################
# Function: radwin_bs_software_ul_2rssi_invent
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################

"""

def rad5k_ss2_ul_rssi(item, _no_params, info):
    """
            radwin_bs_software_ul_2rssi_invent function calcdlates the operating ptx

            Args:
                    item (str) Specific item on SNMP output on which we want to filter resdlts

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - 5835

                    Raises:
                            ValueError ,Exception
"""
    state = 3
    infotext = "unknown_value"
    ul_2rssi= None
    try:
	serial_number = info[0][0]
	if serial_number:
	        if memc:
	                key = serial_number + "_param"
        	        value_list = memc.get(key)
                	if value_list:
                        	try:
                                	ul_2rssi = value_list[19]
                        	except:
                                	ul_2rssi = None

		infotext = "RSSI UL is %s" % ul_2rssi
		state = 0
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"

    return (state, infotext,[("ul_2rssi", ul_2rssi)])


check_info["rad5k_ss2_ul_rssi"] = {
    'check_function': rad5k_ss2_ul_rssi,
    'service_description': 'rad5k_ss2_ul_rssi',
    'has_perfdata' : True,
}

#########################################################################
#	SNMP OID for the operating ptx
#########################################################################
snmp_info["rad5k_ss2_ul_rssi"] = ( ".1.3.6.1.4.1.4458.1000.1.1", ["29.0"] )
