#!/usr/bin/python

# ######################################################################
# Function: check_rad5k_ss_link_dist_invent
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################

def check_rad5k_ss_link_dist_invent(item, _no_params, info):
    """
            check_rad5k_ss_link_dist_invent function calculates the uplink utilization

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                                    3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK -  link distance: 600

                    Raises:
                            ValueError ,Exception

    """ 
    state = 3
    infotext = "unknown_value"
    link_distance = ""
        
    try:
        if info:
            if info[0][0]:
                link_distance = int(info[0][0])                        
                state = 0
                infotext = "link distance: %d" % link_distance
    except ValueError :
	infotext = "type_mismatch_value"
    except:
	infotext = "unknown_value"
	
    return (state,infotext,[("link_distance",link_distance)])
                
check_info["rad5k_ss_link_dist_invent"] = {
    'check_function' :  check_rad5k_ss_link_dist_invent,
    'service_description' : "rad5k_ss_link_dist_invent",
    'has_perfdata': True
}
#########################################################################
#       SNMP OID for the Link Distance
#########################################################################
snmp_info['rad5k_ss_link_dist_invent'] = (".1.3.6.1.4.1.4458.1000.1.5",["29.0"])

