#!/usr/bin/python




"""
# ######################################################################
# Function: rad5k_bs_prod_type_invent
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################

"""

def rad5k_bs_prod_type_invent(item, _no_params, info):
    """
            rad5k_bs_prod_type_invent function calcdlates the operating ptx

            Args:
                    item (str) Specific item on SNMP output on which we want to filter resdlts

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - 5835

                    Raises:
                            ValueError ,Exception
"""
    state = 3
    infotext = "unknown_value"
    prod_type= None
    try:
	prod_type = info[0][0]
	prod_type = prod_type.replace(" ","")
	if prod_type:
		infotext = "%s" % prod_type
		state = 0
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"

    return (state, infotext,[("software_prod_type", prod_type)])


check_info["rad5k_bs_prod_type_invent"] = {
    'check_function': rad5k_bs_prod_type_invent,
    'service_description': 'rad5k_bs_prod_type_invent',
    'has_perfdata' : True,
}

#########################################################################
#	SNMP OID for the operating ptx
#########################################################################
snmp_info["rad5k_bs_prod_type_invent"] = ( ".1.3.6.1.4.1.4458.1000.1.1.30", ["0"] )
