#!/usr/bin/python

# ##################################################################
# Function : check_rad5k_channel_bw_invent
#
#  Parameters: info(SNMP output) ,params(parameters to check the service state) 
#
#  Output: service state,plugin output ,performance data
##################################################################
from mysql_connection import memc

def check_rad5k_channel_bw_invent(item, _no_params, info):
	"""
            check_rad5k_channel_bw_invent function calculates the BS Channel Bandwidth

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                                    3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - channel_bandwidth=1000

                    Raises:
                            ValueError ,Exception
	"""
	#print info
	state = 3
	infotext = "unknown_value"
	channel_bandwidth = 0
	try:
		if info:
			channel_bandwidth = 0
			if info[0][0]:
				channel_bandwidth = saveint(info[0][0])
				infotext = "cbw=%d" % channel_bandwidth
				state= 0

                                key = g_hostname + "_cbw"
                                try:
                                        if memc:
                                                memc.set(key, channel_bandwidth)
						memc.get(key)
                                except :
                                        pass



	except:
        	infotext = "unknown_value"
   
	return (state, infotext,[("cbw",channel_bandwidth)])


check_info["rad5k_channel_bw_invent"] = {
    'check_function': check_rad5k_channel_bw_invent,
    'service_description': 'rad5k_channel_bw_invent',
    'has_perfdata': True,
}

#######################################################################
#	SNMP OID FOR BS CHANNEL BANDWIDTH
#######################################################################
snmp_info["rad5k_channel_bw_invent"] = ( ".1.3.6.1.4.1.4458.1000.1.5", ["24.0"] ) 

