#!/usr/bin/python

import sys
import os
from mysql_connection import memc
"""
# ######################################################################
# Function: radwin_bs_software_ss_mir_invent
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################

"""

def rad5k_ss_mir_ul_invent(item, _no_params, info):
    """
            radwin_bs_software_ss_mir_invent function calcdlates the operating ptx

            Args:
                    item (str) Specific item on SNMP output on which we want to filter resdlts

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - 5835

                    Raises:
                            ValueError ,Exception
"""
    state = 3
    infotext = "unknown_value"
    ss_mir= None
    try:
	serial_number = info[0][0]
	if serial_number:
	        if memc:
	                key = serial_number + "_param"
        	        value_list = memc.get(key)
                	if value_list:
                        	try:
                                	ss_mir = value_list[17]
                        	except:
                                	ss_mir = None

		infotext = "MIR UL is %s" % ss_mir
		state = 0
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"

    return (state, infotext,[("ss_mir_ul", ss_mir)])


check_info["rad5k_ss_mir_ul_invent"] = {
    'check_function': rad5k_ss_mir_ul_invent,
    'service_description': 'rad5k_ss_mir_ul_invent',
    'has_perfdata' : True,
}

#########################################################################
#	SNMP OID for the operating ptx
#########################################################################
snmp_info["rad5k_ss_mir_ul_invent"] = ( ".1.3.6.1.4.1.4458.1000.1.1", ["29.0"] )
