#!/usr/bin/python
"""
Link Ethernet Poller script.

This is part of device application. 
Poller script determines the all ports ethernet status. 
poller script takes the snmp value of OID .1.3.6.1.2.1.2.2.1.8 from snmp agent of device at specific interval.
all ports status are sent to device application 

"""

# ####################################################################################
# Function : check_cambium_port_speed_status
#
#Parameters: info (SNMP output ) _no_params ( No Parameters)
#
#Output: plugin output ,service state,performance data
#####################################################################################
def get_num(x):
    return ''.join(ele for ele in x if ele.isdigit())


def check_cambium_port_speed_status(item, _no_params, info):
    """
                check_cambium_port_speed_status function calculates the link ethernet status of the port 

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : [Management_Port_on_Odu]up [Radio_Interface]up

                        performance_data  (list):
                                        performance data
                                        Example: Management_Port_on_Odu=up;;;; Radio_Interface=up;;;;
                        Raises:
                                ValueError ,Exception
    """
    state = 3
    port_stats = None
    port_speed_value = None
    infotext = "unknown_value"
    try:
	if info[0][0]:
	    port_stats = info[0][0]
	    if port_stats.lower() == 'No Link'.lower():
		port_speed_value = "0 "
	    else:
		port_speed_value = get_num(port_stats)
	    if port_speed_value:
	    	port_speed_value = port_speed_value + "Mbps"
            	state = 0
            	infotext = "%s" % (port_speed_value)

    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"

    return (state, infotext, [("ss_speed",port_speed_value)])


check_info["cambium_port_speed_status"] = {
    'check_function': check_cambium_port_speed_status,
    'service_description': 'cambium_port_speed_status',
    'has_perfdata': True,
}

#####################################################################
#snmp OID corrosponding to ports ethernet status.
######################################################################

snmp_info["cambium_port_speed_status"] = ( ".1.3.6.1.4.1.161.19.3.3.1", ["9.0"] )
