#!/usr/bin/python

"""
Poller script which calculates the data rate of the ss connected to BS.

Poller script determines the data rate of ss.
poller script takes the snmp value of 1.3.6.1.4.1.161.19.3.1.4.1.40.2 from snmp agent of device at specific interval.
Data rate information is sent to device application 

"""
# ##################################################################
# Function : check_cambium_data_rate_invent
#
#  Parameters: info(SNMP output) ,params(parameters to check the service state) 
#
#  Output: service state,plugin output ,performance data
##################################################################



def check_cambium_data_rate_invent(item, _no_params, info):
    """
        Check_cambium_data_rate_invent function calcaulates the received signal strength indication

        Args:
            item (str) Specific item on SNMP output on which we want to filter results

        Kwargs:
            params (tuple) Check parameters for critical and warning state of service

        Returns:
            state (int) :
                    0: OK
                    1: Warning
                    2: Critical
                    3: unknown
            infotext(string):
                    plugin output
                    Example : Device received signal strength indication is -76

            performance_data  (list):
                    performance data
                    Example: cambium_data_rate_invent=-76;-50;-80;;;
            Raises:
                ValueError ,Exception
    """
    state = 3
    infotext = "unknown_value"
    data_rate = None

    try:
        if info:
	    for entry in info:
		if item in entry:
			data_rate = entry[1]
			state =0
            		infotext = "Data rate of ss device %s is %s " % (item,data_rate)
			break
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"
    return (state, infotext, [("data_rate",saveint(data_rate))])


check_info["cambium_data_rate_invent"] = {
    'check_function': check_cambium_data_rate_invent,
    'service_description': 'cambium_data_rate_invent',
    'has_perfdata': True,
}

#######################################################################
#	SNMP OID
#######################################################################
snmp_info["cambium_data_rate_invent"] = ( ".1.3.6.1.4.1.161.19.3.1.4.1", ["3","40"] )
