#!/usr/bin/python
import binascii
import sys
from telnetlib import Telnet
import socket
import json
import os
import mysql.connector
"""
service on SS,which calculates the ss mac.

This is part of device application. 
Poller script determines the ss ip. 
poller script takes the snmp value of OID  1.3.6.1.4.1.161.19.3.3.1.13.0 from snmp agent of device at specific interval.
SS mac information is sent to device application 

"""
# ######################################################################
# Function : check_cambium_ss_mac_invent
#
# Parameters: info (SNMP Output) _no_params(No Parameters)
#
# Output: service state and plugin output
# #####################################################################

def get_from_socket(socket_ip,socket_port, query,site,machine):
    """
    Function_name : get_from_socket (collect the query data from the socket)

    Args: site_name (poller on which monitoring data is to be collected)

    Kwargs: query (query for which data to be collectes from nagios.)

    Return : None

    raise
         Exception: SyntaxError,socket error
    """

    my_machine = nagios_user.split('_')[0]
    if site == nagios_user:
        s=socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        s.connect(livestatus_unix_socket)
    elif machine == my_machine:
        socket_path = "/omd/sites/%s/tmp/run/live" % site
        s=socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        s.connect(socket_path)
    else:
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.connect((socket_ip,socket_port))
    s.settimeout(60.0)
    s.send(query)
    s.shutdown(socket.SHUT_WR)
    try:
        output = s.recv(100000000)
        output.strip("\n")
    except:
        output=None
    return output

def live_query_ul_rssi(mac):
        """
        Connects to a socket, checks for the WELCOME-MSG and closes the
        connection.
        Returns nothing.
    
        """
        exit_value = 3
        plugin_message = ''
        ul_rssi_state = "UNKNOWN"
        ul_rssi = None
	ss_params = None
	if memc:
		value_list = memc.get(mac)
		if value_list:
			try:
				ul_rssi = int(value_list[0])
			except:
				ul_rssi = None
		if ul_rssi is None:
			try:
				key1 = mac + "_topology"
				ss_params = memc.get(key1)
			except:
				pass
	if ul_rssi is None:
		if not ss_params: 
        	    host_name = extract_host_from_cambium_topology(mac)
		    try:
			bs_hostname = host_name[0][0]
			bs_site = host_name[0][1]
		    except:
			bs_hostname = None
		    if memc:
			if bs_hostname:
			    try:
				arg_list = []
				arg_list.append(bs_hostname)
				arg_list.append(bs_site)
				key = mac + "_topology"
				memc.set(key,arg_list,360)
			    except:
				pass
		else:
		    bs_hostname = ss_params[0]
		    bs_site = ss_params[1]			
		try:
		    if bs_hostname:
			query_string = "GET services\nColumns: plugin_output\nFilter: " + \
				"service_description = %s\nFilter: host_name = %s\nOutputFormat: json\n" % ("cambium_topology_discover",bs_hostname)
			site = bs_site
			machine_name = site.split('_')[0]
			socket_ip = _LIVESTATUS[machine_name]['host']
			socket_port = _LIVESTATUS[machine_name][site]['port']
			query_output = json.loads(get_from_socket(socket_ip,int(socket_port),query_string,site,machine_name).strip())
			if query_output[0][0]:
				plugin_output = str(query_output[0][0].split('- ')[1])
				plugin_output = [entry for entry in plugin_output.split(' ')]
				ss_params = filter(lambda x: '/' in x,plugin_output)
				ss_matched_params = filter(lambda x: mac in x,ss_params)
				ul_rssi= map(lambda x: x.split('/')[2],ss_matched_params)
				if ((ul_rssi != 'None') and (ul_rssi != None)):
					ul_rssi= int(ul_rssi[0])
						
		except:
			ul_rssi= None	
	return ul_rssi	



def check_cambium_ul_rssi(item, params, info):
    """
                check_cambium_ss_mac_invent function calculates the mac of ss

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : OK - BB1202020

                        Raises:
                               Exception
    """
    state = 3
    ul_rssi = None
    infotext = "unknown_value"
    warn,crit = params
    this_time = datetime.now()
    t_stmp = this_time + timedelta(minutes=-(this_time.minute % 5))
    t_stmp = t_stmp.replace(second=0,microsecond=0)
    current_time =int(time.mktime(t_stmp.timetuple()))
    try:
        if info:
            if info[0][0]:
                ss_mac = info[0][0]
		a=binascii.b2a_hex(ss_mac)
                n = 2
                ss_mac=(':').join([a[i:i+2] for i in range(0, len(a), n)])
		if ss_mac:
			ul_rssi = live_query_ul_rssi(ss_mac )
			if ul_rssi != None:
				if ul_rssi < crit:
					state  = 2
				elif ul_rssi > crit and ul_rssi < warn:
					state = 1
				else:
					state = 0
				if memc:
					key1 = str(g_hostname) + "_ul_rssi" + "_" + str(current_time)
					memc.set(key1,ul_rssi,600)
	infotext = "Device uplink signal strength indication is %s " % ul_rssi
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown"
    return (state, infotext, [("ul_rssi", ul_rssi, warn, crit)])


check_info["cambium_ul_rssi"] = {
    'check_function': check_cambium_ul_rssi,
    'service_description': 'cambium_ul_rssi',
    'has_perfdata': True,
}

#################################################################
#SNMP OID value for poller script
################################################################

snmp_info["cambium_ul_rssi"] = ( ".1.3.6.1.2.1.2.2.1", ["6.1"] )
