#!/usr/bin/python
"""
IDU serial number Poller script.

This is part of device application. 
Poller script determines the connected AP IP with the SS. 
poller script takes the snmp value of OID 1.3.6.1.4.1.161.19.3.3.1.13.0 from snmp agent of device at specific interval.
IP information is sent to device application 

"""
# ######################################################################
# Function : check_cambium_ss_connected_bs_ip_invent
#
# Parameters: info (SNMP Output) _no_params(No Parameters)
#
# Output: service state and plugin output
# #####################################################################


def extract_host_ip_from_cambium_topology(ss_host_ip):
    data = None
    try:
        if memc:
	    key = ss_host_ip+ "_t_discover"
            data = memc.get(key)   
    except:
        data = None
        pass
    return data


def check_cambium_ss_connected_bs_ip_invent(item, _no_params, info):
    """
                check_cambium_ss_connected_bs_ip_invent function calculates the ap ip

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : OK - BB1202020

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    bs_ip = ''
    try:
        if info:
            if info[0][0]:
                connected_bs_ip = info[0][0]
		bs_ip=extract_host_ip_from_cambium_topology(connected_bs_ip)
		#bs_ip =bs_ip[0][0]
                state = 0
                infotext = "%s" % bs_ip
    except:
        infotext = "unknown_value"
    return (state, infotext,[("ss_connected_bs_ip",bs_ip)])


check_info["cambium_ss_connected_bs_ip_invent"] = {
    'check_function': check_cambium_ss_connected_bs_ip_invent,
    'service_description': 'cambium_ss_connected_bs_ip_invent',
    'has_perfdata' : True
}

#################################################################
#SNMP OID value for poller script
################################################################

snmp_info["cambium_ss_connected_bs_ip_invent"] = ( ".1.3.6.1.4.1.161.19.3.3.1", ["13.0"] )
