#!/usr/bin/python
import binascii
import sys
from telnetlib import Telnet
import socket
import json
import os
import mysql.connector
"""
service on SS,which calculates the ss mac.

This is part of device application. 
Poller script determines the ss ip. 
poller script takes the snmp value of OID  1.3.6.1.4.1.161.19.3.3.1.13.0 from snmp agent of device at specific interval.
SS mac information is sent to device application 

"""
# ######################################################################
# Function : check_cambium_ss_mac_invent
#
# Parameters: info (SNMP Output) _no_params(No Parameters)
#
# Output: service state and plugin output
# #####################################################################

def live_query_reg_count(mac):
        """
        Connects to a socket, checks for the WELCOME-MSG and closes the
        connection.
        Returns nothing.
    
        """
        exit_value = 3
        plugin_message = ''
        reg_count_state = "UNKNOWN"
        reg_count = None
	ss_params = None
	if memc:
		value_list = memc.get(mac)
		if value_list:
			try:
				reg_count = int(value_list[4])
			except:
				reg_count = None
		if not reg_count:
			try:
				key1 = mac + "_topology"
				ss_params = memc.get(key1)
			except:
				pass
	if not reg_count:
		if not ss_params: 
        	    host_name = extract_host_from_cambium_topology(mac)
		    try:
			bs_hostname = host_name[0][0]
			bs_site = host_name[0][1]
		    except:
			bs_hostname = None
		    if memc:
			if bs_hostname:
			    try:
				arg_list = []
				arg_list.append(bs_hostname)
				arg_list.append(bs_site)
				key = mac + "_topology"
				memc.set(key,arg_list,360)
			    except:
				pass
		else:
		    bs_hostname = ss_params[0]
		    bs_site = ss_params[1]			
        	try:
                    if bs_hostname:
                        query_string = "GET services\nColumns: plugin_output\nFilter: " + \
                                "service_description = %s\nFilter: host_name = %s\nOutputFormat: json\n" % ("cambium_topology_discover",bs_hostname)
			site = bs_site
                        machine_name = site.split('_')[0]
                        socket_ip = _LIVESTATUS[machine_name]['host']
                        socket_port = _LIVESTATUS[machine_name][site]['port']

                        query_output = json.loads(get_from_socket(socket_ip,int(socket_port),query_string,site,machine_name).strip())
                        if query_output[0][0]:
                                plugin_output = str(query_output[0][0].split('- ')[1])
                                plugin_output = [entry for entry in plugin_output.split(' ')]
                                ss_params = filter(lambda x: '/' in x,plugin_output)
                                ss_matched_params = filter(lambda x: mac in x,ss_params)
                                reg_count= map(lambda x: x.split('/')[4],ss_matched_params)
				if ((reg_count != 'None') and (reg_count != None)):
                                	reg_count= int(reg_count[0])
        	except:
			reg_count= None	
	return reg_count	



def check_cambium_reg_count(item, params, info):
    """
                check_cambium_ss_mac_invent function calculates the mac of ss

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : OK - BB1202020

                        Raises:
                               Exception
    """
    state = 3
    reg_count = None
    infotext = "unknown_value"
    warn,crit = params
    try:
        if info:
            if info[0][0]:
                ss_mac = info[0][0]
		a=binascii.b2a_hex(ss_mac)
                n = 2
                ss_mac=(':').join([a[i:i+2] for i in range(0, len(a), n)])
		if ss_mac:
			reg_count = live_query_reg_count(ss_mac )
			if reg_count != None:
				if reg_count > crit:
					state  = 2
				elif reg_count <= crit and reg_count >= warn:
					state = 1
				else:
					state = 0
	infotext = "Device reg_count is %s " % reg_count
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"
    return (state, infotext, [("reg_count", reg_count, warn, crit)])


check_info["cambium_reg_count"] = {
    'check_function': check_cambium_reg_count,
    'service_description': 'cambium_reg_count',
    'has_perfdata': True,
}

#################################################################
#SNMP OID value for poller script
################################################################

snmp_info["cambium_reg_count"] = ( ".1.3.6.1.2.1.2.2.1", ["6.1"] )
