#!/usr/bin/python
import re
import time
"""
Downlink utilizationPoller script.

This is part of device application. 
Poller script determines the port current Downlink utilization in terms of number of octets in downlink direction.
poller script takes the snmp value of OID .1.3.6.1.2.1.2.2.1.16 from snmp agent of device at specific interval.
Total Downlink utilization is sent to device application 

"""
# #######################################################################
# Function : check_mrotek_ul_utilization
#
# Parameters: info (SNMP otuput ,_no_params (NO parameters))
#
# Output: service state,plugin output and performance data
# #######################################################################


def check_mrotek_ul_utilization(item, _no_params, info):
    """
                check_mrotek_ul_utilization function calculates the downlink utilization

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : OK - [Management_Port_on_Odu] ul_utilization:2994339289

                        performance_data  (list):
                                        performance data
                                        Example: Management_Port_on_Odu=2994339289;;;; Radio_Interface=;;;;
                        Raises:
                                ValueError ,Exception
    """
    state = 3
    rate = None
    link_out_octets = None
    wrapped = False
    infotext = "unknown_value"
    status_list = []
    key = "master_ua" + "_switch"  # key of memcache configured ports
    try :
       memcache_switch = memc.get(key)
       host_name = str(g_hostname)
       conf_port =  memcache_switch.get(host_name,"") #conf_port contain back_hual configured port like  ge-0_0_1
       index1 = int(conf_port[4])
       index2 = index-1
    except:
       index2 = 0
    try:
        if info[index2][0]:
		link_out_octets = int(info[index2][0])
		this_time = int(time.time())
		try:
			timedif, rate = get_counter("mrotek_ul_utilization" , this_time, saveint(link_out_octets))
			rate = (rate * 8)/(1024.0 * 1024)
    			state = 0
			try:
				if memc:
					key = str(g_hostname) + "_ul"
					rate1 = str(round(rate,2))+","+str(index1)   # to send port number to KPI with rate
					memc.set(key,rate1,900)
			except:
				pass
		except MKCounterWrapped:
			wrapped=True
                d_source = "fe_"+str(index1)
                status_list.append((d_source,"%.2f" % rate))
                infotext = "ul_utilization: [time=%s count=%s]" % (this_time,link_out_octets)
    except ValueError:
        infotext = "type_mismatch_error"
    except:
	infotext = "unknown_value"
    if wrapped:
        infotext = "Counter wrapped"
    return (state, infotext, status_list)


check_info["mrotek_ul_utilization"] = {
    'check_function': check_mrotek_ul_utilization,
    'service_description': 'mrotek_ul_utilization',
    'has_perfdata': True,
}

##############################################################################
#SNMP OID for the Downlink utilization
##############################################################################


snmp_info["mrotek_ul_utilization"] = ( ".1.3.6.1.2.1.2.2.1", ["10"] )
