#!/usr/bin/python

import sys
from telnetlib import Telnet
import socket
import json
import os

"""
operating Frequency of ss device  Poller script.

This is part of device application. 
Poller script determines the operating ptx of device. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.1.1.2.0 from snmp agent of device at specific interval.
Device on which Frequency operating is sent to device application 

"""
# ######################################################################
# Function: check_mrotek_port_values
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################


def connection_telnet_for_mrotek_port_state(hostip, port):
        """
        Connects to a socket, checks for the WELCOME-MSG and closes the
        connection.
        Returns nothing.
    
        """
        try:
                tn = Telnet(hostip,port,timeout=3)
        except socket.timeout:
		plugin_message = ""
		return plugin_message
	tn.read_until("Login:")
	tn.write("switch" + "\r\n")
	tn.read_until("Password:")
	tn.write("switch" + "\r\n")
	tn.write("enable" + "\r\n")
	tn.read_until("Password:")
	tn.write("switch" + "\r\n")
	tn.write("show interface client \r\n" )
	tn.write("exit\r\n")
	data = tn.read_all()
	plugin_message = ""
	index = 0
	port_duplex_list = []
	port_speed_list = []
	port_up_list = []
	port_auto_list = []
	port_params = []
	try:
		for i,row in enumerate(data.split("\n")):
			if "C:" in row:
				index = index+1
				port_row = [r for r in row.split()]
				try:
					port_duplex = port_row[3].split('/')[1]
					port_speed = port_row[3].split('/')[0]
				except Exception ,e:
					port_speed =  port_row[3]
					port_duplex =  port_row[3]
				port_up = port_row[2].split('(')[0]
				port_auto = port_row[1]
				plugin_message += "%s=%s,%s,%s,%s " % (index,port_duplex,port_speed,port_up,port_auto)
				port_duplex_list.append(port_duplex)
				port_speed_list.append(port_speed)
				port_up_list.append(port_up)
				port_auto_list.append(port_auto)

		try:
			port_params.append(port_duplex)
			port_params.append(port_speed)
			port_params.append(port_up)
			port_params.append(port_auto)
			key = g_hostname + "_port_params"
			memc.set(key,port_params,300)
		except:
			pass
					
        except:
		plugin_message = ""
	return plugin_message
                                

def check_mrotek_port_values(item, _no_params, info):
    """
            check_mrotek_port_values function calcdlates the operating ptx

            Args:
                    item (str) Specific item on SNMP output on which we want to filter resdlts

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - 5835

                    Raises:
                            ValueError ,Exception
    """
    state = 3
    infotext = "unknown_value"
    try:
	ip = ipaddresses.get(g_hostname)
	plugin_message =connection_telnet_for_mrotek_port_state(ip, 23)
	if plugin_message:
		infotext = "%s" % (plugin_message)
		state = 0
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"

    return (state, infotext)


check_info["mrotek_port_values"] = {
    'check_function': check_mrotek_port_values,
    'service_description': 'mrotek_port_values',
}

#########################################################################
#	SNMP OID for the operating ptx
#########################################################################
snmp_info["mrotek_port_values"] = ( ".1.3.6.1", ["4.1.8886.6.1.1.4.1.1.6"] )

