#!/usr/bin/python

"""
Poller script which runs on ss and calculates the ul jitter from connected BS type.

Poller script determines the received signal strength indication.
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.1.4.1.21 from snmp agent of device at specific interval.
RSSI information is sent to device application 

"""
# ##################################################################
# Function : check_cambium_ss_bs_jitter_ul
#
#  Parameters: info(SNMP output) ,params(parameters to check the service state) 
#
#  Output: service state,plugin output ,performance data
##################################################################



def check_cambium_ss_bs_jitter_ul(item, _no_params, info):
    """
        Check_cambium_ss_bs_jitter_ul function calcaulates the received signal strength indication

        Args:
            item (str) Specific item on SNMP output on which we want to filter results

        Kwargs:
            params (tuple) Check parameters for critical and warning state of service

        Returns:
            state (int) :
                    0: OK
                    1: Warning
                    2: Critical
                    3: unknown
            infotext(string):
                    plugin output
                    Example : Device received signal strength indication is -76

            performance_data  (list):
                    performance data
                    Example: cambium_ss_bs_jitter_ul=-76;-50;-80;;;
            Raises:
                ValueError ,Exception
    """
    state = 3
    infotext = "unknown_value"
    jitter_ul = None

    try:
        if info:
	    for entry in info:
		if item in entry:
			jitter_ul = entry[1]
			state =0
			break
            infotext = "Device received signal strength indication is %s " % jitter_ul
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"
    return (state, infotext, [("jitter_ul", saveint(jitter_ul))])


check_info["cambium_ss_bs_jitter_ul"] = {
    'check_function': check_cambium_ss_bs_jitter_ul,
    'service_description': 'cambium_ss_bs_jitter_ul',
    'has_perfdata': True,
}

#######################################################################
#	SNMP OID
#######################################################################
snmp_info["cambium_ss_bs_jitter_ul"] = ( ".1.3.6.1.4.1.161.19.3.1.4.1", ["3","22"] )
