#!/usr/bin/python
import binascii
"""
service on SS,which calculates the ss ip.

This is part of device application. 
Poller script determines the bs ip. 
poller script takes the snmp value of OID  1.3.6.1.4.1.161.19.3.3.1.13.0 from snmp agent of device at specific interval.
SS ip information is sent to device application 

"""
# ######################################################################
# Function : check_cambium_serial_number_invent
#
# Parameters: info (SNMP Output) _no_params(No Parameters)
#
# Output: service state and plugin output
# #####################################################################

def check_cambium_serial_number_invent(item, _no_params, info):
    """
                check_cambium_serial_number_invent function calculates the idu serial number

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : OK - BB1202020

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    serial_number_list = []
    try:
        if info:
            if info[0][0]:
		infotext = ""
		for index in range(len(info)):
                	serial_number = info[index][1]
			# Check_mk gives the HEX-STRING value in binary format.Required conversion to convert in to string
			serial_number = binascii.b2a_hex(serial_number)
                	n = 2
                	new_serial_number = (':').join([serial_number[i:i+2] for i in range(0, len(serial_number), n)])
			serial_name = info[index][0]
			serial_name = re.sub('[^0-9a-zA-Z-_]+', '_', serial_name)
                	serial_number_list.append((serial_name,new_serial_number))
                	state = 0
			break
		for name, serial in serial_number_list:
                	infotext += "[%s]%s " % (name, serial)
    except:
        infotext = "unknown_value"
    return (state, infotext)


check_info["cambium_serial_number_invent"] = {
    'check_function': check_cambium_serial_number_invent,
    'service_description': 'cambium_serial_number_invent',
}

#################################################################
#SNMP OID value for poller script
################################################################

snmp_info["cambium_serial_number_invent"] = ( ".1.3.6.1.2.1.2.2.1", ["2","6"] )
