#!/usr/bin/python

"""
Master slave sync state Poller script.

Poller script determines the sync state of slave odu with master.
poller script takes the snmp value of OID .1.3.6.1.4.1.4458.1000.1.5.40.2.0 from snmp agent of device at specific interval.
Master slave sync state information is sent to device application 

"""
# ###################################################################
# Function: check_cambium_sync_state_invent
#
# Parameters : info (SNMP output of OID) _no_params(currently no params supported)
#
# Ouptut : service state ,plugin output and performance_data
# ###################################################################


def check_cambium_sync_state_invent(item, _no_params, info):
    """
            check_cambium_sync_state_invent function calculates the master slave sync state

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : site sync state is independentUnit

                    performance_data  (list):
                                    performance data
                                    Example: site_sync_state=independentUnit;;;;
                    Raises:
                            ValueError ,Exception
    """
    state = 3
    infotext = "unknown_value"
    try:
        if info:
            if info[0][0]:
                sync_state = info[0][0]
                state = 0
                infotext = "%s" % (sync_state)
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"

    return (state, infotext)


check_info["cambium_sync_state_invent"] = {
    'check_function': check_cambium_sync_state_invent,
    'service_description': 'cambium_sync_state_invent',
}

####################################################################
#	SNMP OID
####################################################################
snmp_info["cambium_sync_state_invent"] = ( ".1.3.6.1.4.1.161.19.3.1.7", ["2.0"] )

