#!/usr/bin/python
import time
import binascii
"""
Poller script which runs on ss and calculates the ul utilization of the ss connected from BS.

Poller script determines the uplink utilization of the ss.
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.1.4.1.21 from snmp agent of device at specific interval.
uplink utilization information is sent to device application 

"""
# ##################################################################
# Function : check_cambium_ul_utilization_kpi
#
#  Parameters: info(SNMP output) ,params(parameters to check the service state) 
#
#  Output: service state,plugin output ,performance data
##################################################################


def check_cambium_ul_utilization_kpi(item, _no_params, info):
    """
        Check_cambium_ul_utilization_kpi function calcaulates the upliknk utilization

        Args:
            item (str) Specific item on SNMP output on which we want to filter results

        Kwargs:
            params (tuple) Check parameters for critical and warning state of service

        Returns:
            state (int) :
                    0: OK
                    1: Warning
                    2: Critical
                    3: unknown
            infotext(string):
                    plugin output
                    Example : Device received signal strength indication is -76

            performance_data  (list):
                    performance data
                    Example: cambium_ul_utilization_kpi=-76;-50;-80;;;
            Raises:
                ValueError ,Exception
    """
    state = 3
    infotext = "unknown_value"
    status_list = [] 
    rate = None
    wrapped =False
    try:
        if info:
		status_list = []
		if info[0][2]:
			ul_utilization = info[0][2]
			bs_ip = info[0][0]
			color_code = info[0][1]
			sector_id= bs_ip + ":" +color_code
			this_time = int(time.time())
			try:
                        	timedif, rate = get_counter("cambium_ul_utilization_kpi", this_time, saveint(ul_utilization))
				rate = (rate*8)/(1024*1024)
				rate = (rate/2.24)*100
                		status_list.append(("ul_utilization", "%f" % (rate)))
                		status_list.append(("sector_id", sector_id))
				infotext = "Uplink utilization kpi %s " % (rate)
				state= 0
                	except MKCounterWrapped:
                        	wrapped=True
	else:
	    infotext = "No interface present"
	    
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"
    if wrapped:
        infotext = "Counter wrapped"
    
    return (state, infotext, status_list)


check_info["cambium_ul_utilization_kpi"] = {
    'check_function': check_cambium_ul_utilization_kpi,
    'service_description': 'cambium_ul_utilization_kpi',
    'has_perfdata': True,
}

#######################################################################
#	SNMP OID
#######################################################################
snmp_info["cambium_ul_utilization_kpi"] = ( ".1.3.6.1", ["4.1.161.19.3.3.1.13.0","4.1.161.19.3.3.2.2.0","2.1.2.2.1.10.1"]) 
