#!/usr/bin/python

import binascii

"""
Poller script which runs on ss and calculates the Rereg count for SS.

Poller script determines the rereg count for ss.
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.1.4.1.21 from snmp agent of device at specific interval.
RSSI information is sent to device application 

"""
# ##################################################################
# Function : check_cambium_reg_count
#
#  Parameters: info(SNMP output) ,params(parameters to check the service state) 
#
#  Output: service state,plugin output ,performance data
##################################################################


def inventory_cambium_reg_count(info):
	print info
	for entry in info:
		print entry
                a=binascii.b2a_hex(entry[0])
                n = 2
                entry[0]=(':').join([a[i:i+2] for i in range(0, len(a), n)])
def check_cambium_reg_count(item, params, info):
    """
        Check_cambium_reg_count function calcaulates the received signal strength indication

        Args:
            item (str) Specific item on SNMP output on which we want to filter results

        Kwargs:
            params (tuple) Check parameters for critical and warning state of service

        Returns:
            state (int) :
                    0: OK
                    1: Warning
                    2: Critical
                    3: unknown
            infotext(string):
                    plugin output
                    Example : Device received signal strength indication is -76

            performance_data  (list):
                    performance data
                    Example: cambium_reg_count=-76;-50;-80;;;
            Raises:
                ValueError ,Exception
    """
    state = 3
    infotext = "unknown_value"
    status_list = []
    warn ,crit = params
    try:
        if info:
	    status_list = []
	    for entry in info:
                a=binascii.b2a_hex(entry[0])
                n = 2
                entry[0]=(':').join([a[i:i+2] for i in range(0, len(a), n)])
		if item in entry:
			reg_count = int(entry[1])
			if reg_count > crit:
				state = 3
			elif reg_count <= crit and reg_count >= warn:
				state = 2
			else:
				state = 0
            		infotext = "Reg count value is %s" % (reg_count)
			status_list.extend([("reg_count",reg_count)])
			break
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "u_value"
    return (state, infotext,status_list)


check_info["cambium_reg_count"] = {
    'check_function': check_cambium_reg_count,
    'inventory_function': inventory_cambium_reg_count,
    'service_description': 'cambium_reg_count',
    'has_perfdata': True,
}

#######################################################################
#	SNMP OID
#######################################################################
snmp_info["cambium_reg_count"] = ( ".1.3.6.1.4.1.161.19.3.1.4.1", ["3","25"] )
