#!/usr/bin/python

"""
Color code of BS Poller script.

This is part of device application. 
Poller script determines the sector id of BS. 
poller script takes the snmp value of OID 1.3.6.1.4.1.161.19.3.2.2.65.0 from snmp agent of device at specific interval.
Sector ID of BS is sent to device application 

"""
# ######################################################################
# Function: check_cambium_ss_sector_id_invent
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################


def check_cambium_ss_sector_id_invent(item, _no_params, info):
    """
            check_cambium_ss_sector_id_invent function calculates the sector id of BS

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - 1222

                    Raises:
                            ValueError ,Exception
"""
    state = 3
    infotext = "unknown_value"
    try:
        if info:
            if info[0][0]:
                color_code = int(info[0][1])
		bs_ip = info[0][0]
                state = 0
                infotext = "%s:%s" % (color_code,bs_ip)
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"
    return (state, infotext)


check_info["cambium_ss_sector_id_invent"] = {
    'check_function': check_cambium_ss_sector_id_invent,
    'service_description': 'cambium_ss_sector_id_invent',
}

#########################################################################
#	SNMP OID for the operating frequency
#########################################################################
snmp_info["cambium_ss_sector_id_invent"] = ( ".1.3.6.1.4.1.161.19.3", ["3.1.13.0","2.2.65.0"] )
