#!/usr/bin/python

"""
Ethernet port speed Poller script.

Poller script determines the cambium devices port speed.
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.3.2.80.0 from snmp agent of device at specific interval.
Ethernet port speed information is sent to device application 

"""

# ######################################################################
# Function : check_cambium_port_speed_status
#
# Parameters : info(SNMP output) _no_params (No parameters)
#
# Output: Plugin output ,service state and performance data
# ####################################################################

def port_speed(st):
    names = {'1': 'notConnected', '10': '10Mbps',
             '11': '10Mbps', '15': '100Mbps',
             '16': '100Mbps', '6556': 'unknown'}
    return names.get(st)


def check_cambium_port_speed_status(item, _no_params, info):
    """
                check_cambium_port_speed_status function calculates the port status

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : [port port_1] 100Mbps

                        performance_data  (list):
                                        performance data
                                        Example: port_1 = 100Mbps;;;;
                        Raises:
                                ValueError ,Exception
    """
    state = 3
    infotext = "unknown_value"
    port_status_list = ['']
    try:
        if info:
            port_status_list = []
            infotext = ""
	    port_speed_value = info[index][0]
            port_speed_value = port_speed(str(port_speed_value))
            if port_speed_value == None:
		port_speed_value = "unknown_port_speed"
            port_status_list.append(("port_speed", port_speed_value))

            infotext += "port_speed %s" % (port_speed_value)
            state = 0
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"
    return (state, infotext, port_status_list)


check_info["cambium_port_speed_status"] = {
    'check_function': check_cambium_port_speed_status,
    'service_description': 'cambium_port_speed_status',
    'has_perfdata': True,
}
#################################################################
#	SNMP OID
#################################################################
snmp_info["cambium_port_speed_status"] = ( ".1.3.6.1.4.1.161.19.3.3.2", ["80.0"] )
                                                                                         

