#!/usr/bin/python

"""
Tranmitted power Poller script.

This is part of device application. 
Poller script determines the transmitted power of device. 
poller script takes the snmp value of OID 1.3.6.1.4.1.161.19.3.3.2.23.0 from snmp agent of device at specific interval.
Device on which Frequency operating is sent to device application 

"""
# ######################################################################
# Function: check_cambium_transmit_power_invent
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################


def check_cambium_transmit_power_invent(item, _no_params, info):
    """
            check_cambium_transmit_power_invent function calculates the transmitted power

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - 1222

                    Raises:
                            ValueError ,Exception
"""
    state = 3
    infotext = "unknown_value"
    try:
        if info:
            if info[0][0]:
                transmit_power = int(info[0][0])
                state = 0
                infotext = "%d" % transmit_power
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"
    return (state, infotext)


check_info["cambium_transmit_power_invent"] = {
    'check_function': check_cambium_transmit_power_invent,
    'service_description': 'cambium_transmit_power_invent',
}

#########################################################################
#	SNMP OID for the operating frequency
#########################################################################
snmp_info["cambium_transmit_power_invent"] = ( ".1.3.6.1.4.1.161.19.3.3.2", ["23.0"] )
