#!/usr/bin/python
"""
Poller script for commanded rx power in SS of cambium device type.

This is part of device application. 
Poller script determines the commanded rx power. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.1.1.73.0 from snmp agent of device at specific interval.
commanded rx power information is sent to device application 

"""
# ######################################################################
# Function : check_cambium_commanded_rx_power_invent
#
# Parameters: info (SNMP Output) _no_params(No Parameters)
#
# Output: service state and plugin output
# #####################################################################

def check_cambium_commanded_rx_power_invent(item, _no_params, info):
    """
                check_cambium_commanded_rx_power_invent function calculates the idu serial number

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : OK - BB1202020

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    try:
        if info:
            if info[0][0]:
                rx_power = info[0][0]
                state = 0
                infotext = "%s" % rx_power
    except:
        infotext = "unknown_value"
    return (state, infotext)


check_info["cambium_commanded_rx_power_invent"] = {
    'check_function': check_cambium_commanded_rx_power_invent,
    'service_description': 'cambium_commanded_rx_power_invent',
}

#################################################################
#SNMP OID value for poller script
################################################################

snmp_info["cambium_commanded_rx_power_invent"] = ( ".1.3.6.1.4.1.161.19.3.1.1", ["73.0"] )
