#!/usr/bin/python
"""
Link Ethernet Poller script.

This is part of device application. 
Poller script determines the all ports ethernet status. 
poller script takes the snmp value of OID .1.3.6.1.2.1.2.2.1.8 from snmp agent of device at specific interval.
all ports status are sent to device application 

"""


def if_statename(st):
    """
	utility function for mapping the interget OID value to string status.
    """
    names = {'1': 'up', '2': 'down',
             '3': 'testing', '4': 'unknown',
             '5': 'dormant', '6': 'notPresent',
             '7': 'lowerLayerDown'}
    return names.get(st)

# ####################################################################################
# Function : check_cambium_link_ethernet_status
#
#Parameters: info (SNMP output ) _no_params ( No Parameters)
#
#Output: plugin output ,service state,performance data
#####################################################################################



def check_cambium_link_ethernet_status(item, _no_params, info):
    """
                check_cambium_link_ethernet_status function calculates the link ethernet status of the port 

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : [Management_Port_on_Odu]up [Radio_Interface]up

                        performance_data  (list):
                                        performance data
                                        Example: Management_Port_on_Odu=up;;;; Radio_Interface=up;;;;
                        Raises:
                                ValueError ,Exception
    """
    state = 3
    status_list = ['']
    infotext = "unknown_value"
    try:
        if info:
            status_list = []
            infotext = ""
            for index in range(len(info)):
                link_state = info[index][1]
                if_name = info[index][0]
                if if_name == None:
                    if_name = "unknown_name"
                state = if_statename(str(link_state))
                if state == None:
                    state = "unknown"
                if ' ' in if_name:
                    if_name = str.replace(if_name, ' ', '_')
                status_list.append((if_name, state))
            state = 0
            for name, status in status_list:
                infotext += "[%s]%s " % (name, status)

    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"

    return (state, infotext, status_list)


check_info["cambium_link_ethernet_status"] = {
    'check_function': check_cambium_link_ethernet_status,
    'service_description': 'cambium_link_ethernet_status',
    'has_perfdata': True,
}

#####################################################################
#snmp OID corrosponding to ports ethernet status.
######################################################################

snmp_info["cambium_link_ethernet_status"] = ( ".1.3.6.1.2.1.2.2.1", ["2", "8"] )
