#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def check_cambium_ul_jitter_arguments(params):
    description, settings = params
    args =''
    if "socket_address" in settings:
        args += '%s ' % quote_shell_string(settings['socket_address'])
    if "socket_port" in settings:
        args += '%d ' % int(settings['socket_port'])

    if "mac" in settings:
        args += '%s ' % quote_shell_string(settings['mac'])
    if "jitter_warning" in settings:
        args += '%d ' % int(settings['jitter_warning'])

    if "jitter_critical" in settings:
        args += '%d ' % int(settings['jitter_critical'])


    return args

active_check_info['cambium_ul_jitter'] = {
    "command_line"        : '$USER1$/check_cambium_ul_jitter $ARG1$',
    "argument_function"   : check_cambium_ul_jitter_arguments,
    "service_description" : lambda params: "%s" % params[0],
    "has_perfdata"        :True,
}

