#!/usr/bin/python
import time
import sys
import os
import socket
import pymongo
from datetime import datetime ,timedelta
"""
Poller script which runs on ss and calculates the ul utilization of the ss connected from BS.

Poller script determines the uplink utilization of the ss.
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.1.4.1.21 from snmp agent of device at specific interval.
uplink utilization information is sent to device application 

"""
# ##################################################################
# Function : check_cambium_pmp1_dl_utilization_kpi
#
#  Parameters: info(SNMP output) ,params(parameters to check the service state) 
#
#  Output: service state,plugin output ,performance data
##################################################################



try:
    import nocout_settings
    from nocout_settings import _DATABASES, _LIVESTATUS
except Exception as exp:
    print exp



def extract_cambium_ss_state(hostname,site):
    state = 3
    ul_issue = ''
    perf = ''
    plugin_message = ''
    DB = None
    state_string = "unknown"
    machine_name = site.split('_')[0]
    mongo_port = _LIVESTATUS[machine_name][site]['mongo_port']
    mongo_host = _LIVESTATUS[machine_name][site]['mongo_host']
    mongo_db = _LIVESTATUS[machine_name][site]['db']
    try:
	CONN = pymongo.Connection(host=mongo_host, port=int(mongo_port))
	db = CONN[mongo_db]
    except pymongo.errors.PyMongoError, e:
	perf = '' 
    	plugin_message += "cambium_ss_ul_issue_kpi %s - %s|%s" % (state_string,ul_issue,perf)
    	sys.stdout.write(plugin_message)
    	sys.exit((state))

    end_time = datetime.now()
    ul_issue =1
    start_time = end_time - timedelta(minutes=10)
    cur = db.service_perf.find({"local_timestamp" : { "$gt": start_time, "$lt": end_time},"host":hostname,
	"$or":[{"service":"cambium_ul_jitter"},{"service":"cambium_rereg_count"}]})
   
    service_state_out = []
    service_state_type = ["warning","critical"]
    try:
        for doc in cur:
		if doc.get('service') == 'cambium_ul_jitter':
			service_state_out.append(doc.get('severity'))
		if doc.get('service') == 'cambium_rereg_count':
			service_state_out.append(doc.get('severity'))
		
	if len(service_state_out) == 4:
		state_string = "ok"
		for entry in service_state_out:
			if str(entry) in service_state_type:
				continue
			else:
				ul_issue = 0
				break
				
		  


    	perf += 'ul_issue' + "=%s " % (ul_issue)
    except Exception ,e:
	perf = '' 
    plugin_message += "cambium_ss_ul_issue_kpi %s - %s|%s" % (state_string,ul_issue,perf)
    sys.stdout.write(plugin_message)
    sys.exit((state))
		
def  main():

    state_string = "unknown"
    ul_issue=''
    try:
        host_name = sys.argv[1]
        site = sys.argv[2]
    except:
        perf =''
        plugin_message += "cambium_ss_ul_issue_kpi %s - %s|%s" % (state_string,ul_issue,perf)
        sys.exit((3))

    extract_cambium_ss_state(host_name,site)
	

if __name__ == '__main__':
	main() 
