#!/usr/bin/python
import time
import binascii
"""
Poller script which runs on ss and calculates the ul utilization of the ss connected from BS.

Poller script determines the uplink utilization of the ss.
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.1.4.1.21 from snmp agent of device at specific interval.
uplink utilization information is sent to device application 

"""
# ##################################################################
# Function : check_wimax_pmp1_ul_utilization_kpi
#
#  Parameters: info(SNMP output) ,params(parameters to check the service state) 
#
#  Output: service state,plugin output ,performance data
##################################################################

def check_wimax_pmp1_ul_utilization_kpi(item, _no_params, info):
    """
        Check_wimax_pmp1_ul_utilization_kpi function calcaulates the upliknk utilization

        Args:
            item (str) Specific item on SNMP output on which we want to filter results

        Kwargs:
            params (tuple) Check parameters for critical and warning state of service

        Returns:
            state (int) :
                    0: OK
                    1: Warning
                    2: Critical
                    3: unknown
            infotext(string):
                    plugin output
                    Example : Device received signal strength indication is -76

            performance_data  (list):
                    performance data
                    Example: wimax_pmp1_ul_utilization_kpi=-76;-50;-80;;;
            Raises:
                ValueError ,Exception
    """
    state = 3
    infotext = "unknown_value"
    status_list = [] 
    rate = None
    sec_id = None
    wrapped =False
    try:
        if info:
		status_list = []
		if info[0][1]:
			ul_utilization = info[0][1]
			sec_id = info[0][0]
                        sec_id = binascii.b2a_hex(sec_id)
                        n = 2
                        sec_id=(':').join([sec_id[i:i+2] for i in range(0, len(sec_id), n)])
                        sec_id = sec_id.lower()
			this_time = int(time.time())

			try:
                        	timedif, rate = get_counter("wimax_pmp1_ul_utilization_kpi", this_time, saveint(ul_utilization))
				rate = (rate*8)/(1024*1024)
				pmp1_bw = extract_pmp1_bw_from_live(g_hostname)
				if pmp1_bw:
					if int(pmp1_bw) <= 3:
						rate = (rate/2) *100
                				status_list.append(("pmp1_ul_utilization", "%f" % (rate)))
						status_list.append(("sector_id", sec_id ))
						state= 0
					elif int(pmp1_bw) > 3:
						rate = (rate/4) *100
                				status_list.append(("pmp1_ul_utilization", "%f" % (rate)))
						status_list.append(("sector_id", sec_id ))
						state= 0
					else:
						rate = None
					infotext = "pmp1 ul utilization %s " % (rate)
			
                	except MKCounterWrapped:
                        	wrapped=True
	else:
	    infotext = "No interface present"
	    
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"
    if wrapped:
        infotext = "Counter wrapped"
    
    return (state, infotext, status_list)


check_info["wimax_pmp1_ul_utilization_kpi"] = {
    'check_function': check_wimax_pmp1_ul_utilization_kpi,
    'service_description': 'wimax_pmp1_ul_utilization_kpi',
    'has_perfdata': True,
}

#######################################################################
#	SNMP OID
#######################################################################
snmp_info["wimax_pmp1_ul_utilization_kpi"] = ( ".1.3.6.1", ["4.1.5812.2000.11.2.1.4.100","2.1.2.2.1.10.150"] )
