#!/usr/bin/python

import sys
from telnetlib import Telnet
import socket
import json
import os
import binascii
import mysql.connector
"""
operating Frequency of ss device  Poller script.

This is part of device application. 
Poller script determines the operating ptx of device. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.1.1.2.0 from snmp agent of device at specific interval.
Device on which Frequency operating is sent to device application 

"""
# ######################################################################
# Function: check_wimax_ss_mac
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################



def extract_host_from_wimax_topology(ss_host_mac):
        query = """
        select device_name from performance_topology where connected_device_mac ='%s' """ %(ss_host_mac)
        db = mysql_conn()
        cur = db.cursor()
        cur.execute(query)
        data = cur.fetchall()
        cur.close()

        return data


def connection_telnet_ss_mac(host_name, port,mac):
        """
        Connects to a socket, checks for the WELCOME-MSG and closes the
        connection.
        Returns nothing.
    
        """
        try:
                tn = Telnet(host_name,port,timeout=3)
        except socket.timeout:
                exit_value = 3
                ss_mac_state = "UNKNOWN"
                sys.stdout.write("UNKNOWN Output")
                sys.exit((exit_value))
        tn.read_until("Login:")
        tn.write("admin" + "\r\n")
        tn.read_until("Password:")
        tn.write("admin" + "\r\n")
        tn.write("show connectivity-table ss %s\r\n" % mac)
        tn.write("exit\r\n")
        data = tn.read_all()

	ss_mac = None
        try:
                for i,row in enumerate(data.split("\n")):
                        if "SS-VLAN:" in row:
                                params_list = [r for r in row.split()]
                                ss_mac = int(params_list[1])
                                break
        except:
		ss_mac = None
	return ss_mac

def check_wimax_ss_mac(item, params, info):
    """
            check_wimax_ss_mac function calcdlates the operating ptx

            Args:
                    item (str) Specific item on SNMP output on which we want to filter resdlts

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - 5835

                    Raises:
                            ValueError ,Exception
"""
    state = 3
    infotext = "unknown_value"
    ss_mac =None
    try:
	if info[1]:
                ss_mac = info[1][0]
		a=binascii.b2a_hex(ss_mac)
		n = 2
		ss_mac=(':').join([a[i:i+2] for i in range(0, len(a), n)])
        	infotext = "%s" % ss_mac
		state = 0
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"

    return (state, infotext,[("ss_mac",ss_mac)])


check_info["wimax_ss_mac"] = {
    'check_function': check_wimax_ss_mac,
    'service_description': 'wimax_ss_mac',
    'has_perfdata' : True,
}

#########################################################################
#	SNMP OID for the operating ptx
#########################################################################
snmp_info["wimax_ss_mac"] = ( ".1.3.6.1.2.1.10.184.1.3.1.1.1", ["17.1"] )
