#!/usr/bin/python

import sys
from telnetlib import Telnet
import socket
import json
import os
import binascii
import mysql.connector
"""
operating Frequency of ss device  Poller script.

This is part of device application. 
Poller script determines the operating ptx of device. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.1.1.2.0 from snmp agent of device at specific interval.
Device on which Frequency operating is sent to device application 

"""
# ######################################################################
# Function: check_wimax_modulation_dl_fec
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################



def extract_host_from_wimax_topology(ss_host_mac):
        query = """
        select device_name,site_name from performance_topology where connected_device_mac ='%s' """ %(ss_host_mac)
        db = mysql_conn()
        cur = db.cursor()
        cur.execute(query)
        data = cur.fetchall()
        cur.close()

        return data



def live_query_modulation_dl_fec(mac):
        """
        Connects to a socket, checks for the WELCOME-MSG and closes the
        connection.
        Returns nothing.
    
        """
        modulation_dl_fec = None
        host_name = extract_host_from_wimax_topology(mac)
        try:
                if host_name[0][0]:
                        query_string = "GET services\nColumns: plugin_output\nFilter: " + \
                                "service_description = %s\nFilter: host_name = %s\nOutputFormat: json\n" % ("wimax_topology",host_name[0][0])
			site = host_name[0][1]
                        machine_name = host_name[0][1].split('_')[0]
                        socket_ip = _LIVESTATUS[machine_name]['host']
                        socket_port = _LIVESTATUS[machine_name][site]['port']

                        query_output = json.loads(get_from_socket(socket_ip,socket_port,query_string).strip())
                        if query_output[0][0]:
                                plugin_output = str(query_output[0][0].split('OK -')[1])
                                plugin_output = [entry for entry in plugin_output.split(' ')]
                                entry=filter(lambda x: mac.upper() in x , plugin_output)
                                modulation_dl_fec = entry[0].split('=')[1].split(',')[6]

	except:
                modulation_dl_fec= None
        return modulation_dl_fec



def check_wimax_modulation_dl_fec(item, _no_params, info):
    """
            check_wimax_modulation_dl_fec function calcdlates the operating ptx

            Args:
                    item (str) Specific item on SNMP output on which we want to filter resdlts

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - 5835

                    Raises:
                            ValueError ,Exception
"""
    state = 3
    infotext = "unknown_value"
    modulation_dl_fec =None
    dl_fec_normal =  ["qam16-3/4", "qam64-2/3","qam64-3/4"]
    dl_fec_warning = ["qpsk3/4","qam16 1/2"]
    dl_fec_critical = ["bpsk1/2", "qpsk1/2"]

    try:
	if info[1]:
                ss_mac = info[1][0]
		a=binascii.b2a_hex(ss_mac)
		n = 2
		ss_mac=(':').join([a[i:i+2] for i in range(0, len(a), n)])
                if ss_mac:
                        modulation_dl_fec = live_query_modulation_dl_fec(ss_mac )
			if modulation_dl_fec:
				if modulation_dl_fec in dl_fec_normal:
					state  = 0
				elif modulation_dl_fec in dl_fec_warning:
					state  = 1
				else:
					state  = 2
				infotext = "Device downlink modulation FEC is %s " % modulation_dl_fec	
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"

    return (state, infotext, [("modulation_dl_fec", modulation_dl_fec)])


check_info["wimax_modulation_dl_fec"] = {
    'check_function': check_wimax_modulation_dl_fec,
    'service_description': 'wimax_modulation_dl_fec',
    'has_perfdata': True,
}

#########################################################################
#	SNMP OID for the operating ptx
#########################################################################
snmp_info["wimax_modulation_dl_fec"] = ( ".1.3.6.1.2.1.10.184.1.3.1.1.1", ["17.1"] )

