#!/usr/bin/python

import sys
from telnetlib import Telnet
import socket
import json
import os

"""
operating Frequency of ss device  Poller script.

This is part of device application. 
Poller script determines the operating ptx of device. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.1.1.2.0 from snmp agent of device at specific interval.
Device on which Frequency operating is sent to device application 

"""
# ######################################################################
# Function: check_wimax_p1_mrc_stc_invent
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################


def connection_telnet_bs_for_p1_mrc_stc(hostip, port):
        """
        Connects to a socket, checks for the WELCOME-MSG and closes the
        connection.
        Returns nothing.
    
        """
        try:
                tn = Telnet(hostip,port,timeout=3)
        except socket.timeout:
		pmp1_mrc = None
		pmp1_stc = None
		return pmp1_mrc,pmp1_stc

        tn.read_until("Login:")
        tn.write("admin" + "\r\n")
        tn.read_until("Password:")
        tn.write("admin" + "\r\n")
        tn.write("show interface wimax config\r\n")
        tn.write("exit\r\n")
        data = tn.read_all()
	pmp1_mrc = None
	pmp1_stc = None
	if data:
		params =[row for row in data.split("\n")]
		try:
			pmp1_mrc = params[9]
			pmp1_mrc  = pmp1_mrc.split(':')[1]
		except:
			pmp1_mrc = None
		try:
			pmp1_stc=params[12]
                        pmp1_stc  = pmp1_stc.split(':')[1]
		except:
			pmp1_stc = None
	return pmp1_mrc,pmp1_stc
                                

def check_wimax_p1_mrc_stc_invent(item, _no_params, info):
    """
            check_wimax_p1_mrc_stc_invent function calcdlates the operating ptx

            Args:
                    item (str) Specific item on SNMP output on which we want to filter resdlts

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - 5835

                    Raises:
                            ValueError ,Exception
"""
    state = 3
    infotext = "unknown_value"
    duplex_value= None
    try:
	if info[0][0]:
                bs_ip = info[0][0]
                if bs_ip:
                	pmp1_mrc,pmp1_stc =connection_telnet_bs_for_p1_mrc_stc(bs_ip, 23)
			if pmp1_mrc or pmp1_src:
				infotext = "%s %s" % (pmp1_mrc,pmp1_stc)
				state = 0
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"

    return (state, infotext)


check_info["wimax_p1_mrc_stc_invent"] = {
    'check_function': check_wimax_p1_mrc_stc_invent,
    'service_description': 'wimax_p1_mrc_stc_invent',
}

#########################################################################
#	SNMP OID for the operating ptx
#########################################################################
snmp_info["wimax_p1_mrc_stc_invent"] = ( ".1.3.6.1.4.1.5812.2000.4.1.1", ["1.0"] )
