#!/usr/bin/python

import sys
from telnetlib import Telnet
import socket
import json
import os

"""
operating Frequency of ss device  Poller script.

This is part of device application. 
Poller script determines the operating ptx of device. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.1.1.2.0 from snmp agent of device at specific interval.
Device on which Frequency operating is sent to device application 

"""
# ######################################################################
# Function: check_wimax_odu_serial_invent
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################


def connection_telnet_bs_for_odu_serial(hostip, port):
        """
        Connects to a socket, checks for the WELCOME-MSG and closes the
        connection.
        Returns nothing.
    
        """
        try:
                tn = Telnet(hostip,port,timeout=3)
        except socket.timeout:
		idu_type = None
		return idu_type
	tn.read_until("Login:")
        tn.write("admin" + "\r\n")
        tn.read_until("Password:")
        tn.write("admin" + "\r\n")
        tn.write("show fru\r\n")
        tn.write("exit\r\n")
        data = tn.read_all()
	odu_serial_1 = None
	odu_serial_2 = None
	try:
                for i,row in enumerate(data.split("\n")):
                        if "ODU1" in row:
                                odu_serial_1 = [r for r in row.split()]
                                odu_serial_1 = odu_serial_1[1]
			if "ODU2" in row:
                                odu_serial_2 = [r for r in row.split()]
                                odu_serial_2 = odu_serial_2[1]
                                break
        except:
		odu_serial_1 = None
		odu_serial_2 = None
	return odu_serial_1,odu_serial_2
                                

def check_wimax_odu_serial_invent(item, _no_params, info):
    """
            check_wimax_odu_serial_invent function calcdlates the operating ptx

            Args:
                    item (str) Specific item on SNMP output on which we want to filter resdlts

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - 5835

                    Raises:
                            ValueError ,Exception
"""
    state = 3
    infotext = "unknown_value"
    odu_serial_1= None
    odu_serial_2= None
    try:
	if info[0][0]:
                bs_ip = info[0][0]
                if bs_ip:
                	odu_serial_1,odu_serial_2 =connection_telnet_bs_for_odu_serial(bs_ip, 23)
			if idu_serial_1 or odu_serial_2:
				infotext = "%s=%s %s=%s" % ("odu1",odu_serial_1,"odu2",odu_serial_2)
				state = 0
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"

    return (state, infotext)


check_info["wimax_odu_serial_invent"] = {
    'check_function': check_wimax_odu_serial_invent,
    'service_description': 'wimax_odu_serial_invent',
}

#########################################################################
#	SNMP OID for the operating ptx
#########################################################################
snmp_info["wimax_odu_serial_invent"] = ( ".1.3.6.1.4.1.5812.2000.4.1.1", ["1.0"] )
