#!/usr/bin/python
import time
import binascii
"""
Poller script which runs on ss and calculates the ul utilization of the ss connected from BS.

Poller script determines the uplink utilization of the ss.
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.1.4.1.21 from snmp agent of device at specific interval.
uplink utilization information is sent to device application 

"""
# ##################################################################
# Function : check_wimax_pmp2_dl_utilization_kpi
#
#  Parameters: info(SNMP output) ,params(parameters to check the service state) 
#
#  Output: service state,plugin output ,performance data
##################################################################

def extract_pmp2_bw_from_live(hostname):
        """
        Connects to a socket, checks for the WELCOME-MSG and closes the
        connection.
        Returns nothing.
    
        """
        pmp_bw = None
        query_string = "GET services\nColumns: plugin_output\nFilter: " + \
                        "service_description = %s\nFilter: host_name = %s\nOutputFormat: json\n"    % ("wimax_pmp_bw_invent",hostname)

        s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        s.connect(livestatus_unix_socket)
	s.send(query_string)
        s.shutdown(socket.SHUT_WR)
        query_output = s.recv(100000000)
        query_output.strip("\n")
	try:
        	if query_output:
			output = json.loads(query_output)
			output = [entry for entry in output[0][0].split('- ')[1].split()]
                	pmp_bw=output[1].split('=')[1]
	except:
		pmp_bw=None

        return pmp_bw


def check_wimax_pmp2_dl_utilization_kpi(item, _no_params, info):
    """
        Check_wimax_pmp2_dl_utilization_kpi function calcaulates the upliknk utilization

        Args:
            item (str) Specific item on SNMP output on which we want to filter results

        Kwargs:
            params (tuple) Check parameters for critical and warning state of service

        Returns:
            state (int) :
                    0: OK
                    1: Warning
                    2: Critical
                    3: unknown
            infotext(string):
                    plugin output
                    Example : Device received signal strength indication is -76

            performance_data  (list):
                    performance data
                    Example: wimax_pmp2_dl_utilization_kpi=-76;-50;-80;;;
            Raises:
                ValueError ,Exception
    """
    state = 3
    infotext = "unknown_value"
    status_list = [] 
    rate = None
    wrapped =False
    try:
        if info:
		status_list = []
		if info[0][1]:
			dl_utilization = info[0][1]
			sec_id = info[0][0]
                        sec_id = binascii.b2a_hex(sec_id)
                        n = 2
                        sec_id=(':').join([sec_id[i:i+2] for i in range(0, len(sec_id), n)])
                        sec_id = sec_id.lower()

			this_time = int(time.time())
			try:
                        	timedif, rate = get_counter("wimax_pmp2_dl_utilization_kpi", this_time, saveint(dl_utilization))
				rate = (rate*8)/(1024*1024)
				pmp2_bw = extract_pmp2_bw_from_live(g_hostname)
				if pmp2_bw:
					if int(pmp2_bw) <= 3:
						rate = (rate/4) *100
                				status_list.append(("pmp2_dl_utilization", "%f" % (rate)))
						status_list.append(("sector_id", sec_id ))
						state= 0
					elif int(pmp2_bw) > 3:
						rate = (rate/8) *100
                				status_list.append(("pmp2_dl_utilization", "%f" % (rate)))
						status_list.append(("sector_id", sec_id ))
						state= 0
					else:
						rate = None
					infotext = "pmp2 dl utilization %s " % (rate)
			
                	except MKCounterWrapped:
                        	wrapped=True
	else:
	    infotext = "No interface present"
	    
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"
    if wrapped:
        infotext = "Counter wrapped"
    
    return (state, infotext, status_list)


check_info["wimax_pmp2_dl_utilization_kpi"] = {
    'check_function': check_wimax_pmp2_dl_utilization_kpi,
    'service_description': 'wimax_pmp2_dl_utilization_kpi',
    'has_perfdata': True,
}

#######################################################################
#	SNMP OID
#######################################################################
snmp_info["wimax_pmp2_dl_utilization_kpi"] = ( ".1.3.6.1", ["4.1.5812.2000.11.2.1.4.200","2.1.2.2.1.16.250"] )
