#!/usr/bin/python

"""
operating Frequency of ss device  Poller script.

This is part of device application. 
Poller script determines the operating ptx of device. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.1.1.2.0 from snmp agent of device at specific interval.
Device on which Frequency operating is sent to device application 

"""
# ######################################################################
# Function: check_wimax_ss_ptx_invent
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################


def check_wimax_ss_ptx_invent(item, params, info):
    """
            check_wimax_ss_ptx_invent function calculates the operating ptx

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - 5835

                    Raises:
                            ValueError ,Exception
"""
    state = 3
    infotext = "unknown_value"
    warn,crit = params
    try:
        if info:
            if info[0][0]:
                ptx = int(info[0][0])
		if ptx > crit:
			state = 2
		elif ptx >= warn and ptx < crit:
			state = 1
		else:
			state = 0 
                infotext = "%d" % ptx
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"
    return (state, infotext)


check_info["wimax_ss_ptx_invent"] = {
    'check_function': check_wimax_ss_ptx_invent,
    'service_description': 'wimax_ss_ptx_invent',
}

#########################################################################
#	SNMP OID for the operating ptx
#########################################################################
snmp_info["wimax_ss_ptx_invent"] = ( ".1.3.6.1.4.1.5812.2000.6.1.1.5", ["11.0"] )
