#!/usr/bin/python

import sys
from telnetlib import Telnet
import socket
import json
import os

import mysql.connector
"""
operating Frequency of ss device  Poller script.

This is part of device application. 
Poller script determines the operating ptx of device. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.1.1.2.0 from snmp agent of device at specific interval.
Device on which Frequency operating is sent to device application 

"""
# ######################################################################
# Function: check_wimax_ss_speed_status
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################

def extract_hostip_from_wimax_topology(ss_host_mac):
        query = """
        select connected_device_ip from performance_topology where connected_device_mac ='%s' """ %(ss_host_mac)
        db = mysql_conn()
        cur = db.cursor()
        cur.execute(query)
        data = cur.fetchall()
        cur.close()

        return data


def connection_telnet_for_speed_status(hostip, port):
        """
        Connects to a socket, checks for the WELCOME-MSG and closes the
        connection.
        Returns nothing.
    
        """
        try:
                tn = Telnet(hostip,port,timeout=3)
        except socket.timeout:
		ss_speed = None
        tn.read_until("Login:")
        tn.write("admin" + "\r\n")
        tn.read_until("Password:")
        tn.write("admin" + "\r\n")
        tn.write("show interface ethernet phy\r\n")
        tn.write("exit\r\n")
        data = tn.read_all()
        ss_speed= None

        try:
                for i,row in enumerate(data.split("\n")):
                        if "Speed" in row:
                                ss_speed = row.split(':')[1]
                                break
        except:
                ss_speed = None
	return ss_speed
                                

def check_wimax_ss_speed_status(item, _no_params, info):
    """
            check_wimax_ss_speed_status function calcdlates the operating ptx

            Args:
                    item (str) Specific item on SNMP output on which we want to filter resdlts

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - 5835

                    Raises:
                            ValueError ,Exception
    """
    state = 3
    infotext = "unknown_value"
    ss_speed= None
    try:
	if info[1]:
                ss_mac = info[1][0]
		a=binascii.b2a_hex(ss_mac)
		n = 2
		ss_mac=(':').join([a[i:i+2] for i in range(0, len(a), n)])
                if ss_mac:
			host_ip = extract_hostip_from_wimax_topology(ss_mac)
			if host_ip[0][0]:
                		ss_speed =connection_telnet_for_speed_status(host_ip[0][0], 23)
				if ss_speed:
					infotext = "SS ethernet speed is %s" % ss_speed
					state = 0
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"

    return (state, infotext,[("ss_speed", ss_speed)])


check_info["wimax_ss_speed_status"] = {
    'check_function': check_wimax_ss_speed_status,
    'service_description': 'wimax_ss_speed_status',
    'has_perfdata' : True,
}

#########################################################################
#	SNMP OID for the operating ptx
#########################################################################
snmp_info["wimax_ss_speed_status"] = ( ".1.3.6.1.2.1.10.184.1.3.1.1.1", ["17.1"] )
