#!/usr/bin/python

import sys
from telnetlib import Telnet
import socket
import json
import os
import binascii
import mysql.connector
"""
operating Frequency of ss device  Poller script.

This is part of device application. 
Poller script determines the operating ptx of device. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.1.1.2.0 from snmp agent of device at specific interval.
Device on which Frequency operating is sent to device application 

"""
# ######################################################################
# Function: check_wimax_ss_session_uptime
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################

def extract_bs_ip_from_wimax_topology(ss_host_mac):
        query = """
        select ip_address from performance_topology where connected_device_mac ='%s' """ %(ss_host_mac)
        db = mysql_conn()
        cur = db.cursor()
        cur.execute(query)
        data = cur.fetchall()
        cur.close()

        return data


def connection_telnet_for_session_uptime(host_name, port,mac):
        """
        Connects to a socket, checks for the WELCOME-MSG and closes the
        connection.
        Returns nothing.
    
        """
        try:
                tn = Telnet(host_name,port,timeout=3)
        except socket.timeout:
		uptime = None
		return uptime
        tn.write("admin" + "\r\n")
        tn.read_until("Password:")
        tn.write("admin" + "\r\n")
        tn.write("show ss uptime\r\n")
        tn.write("exit\r\n")
        data = tn.read_all()
	uptime = None
        try:
                for i,row in enumerate(data.split("\n")):
                        if ":" in row and mac.upper() in row:
                                params_list = [r for r in row.split()]
                                year =  int(params_list[2])
                                day = int(params_list[4])
                                hour = int(params_list[6])
                                minutes = int(params_list[8])
                                seconds = int(params_list[11])
                                uptime = ((year*365*24*60) + (day*24*60) + (hour*60) + minutes) * 60 + seconds
                                break
        except:
		uptime= None
        return uptime



def check_wimax_ss_session_uptime(item, _no_params, info):
    """
            check_wimax_ss_session_uptime function calcdlates the operating ptx

            Args:
                    item (str) Specific item on SNMP output on which we want to filter resdlts

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - 5835

                    Raises:
                            ValueError ,Exception
"""
    state = 3
    infotext = "unknown_value"
    ss_session_uptime =None
    try:
	if info[1]:
                ss_mac = info[1][0]
		a=binascii.b2a_hex(ss_mac)
		n = 2
		ss_mac=(':').join([a[i:i+2] for i in range(0, len(a), n)])
                if ss_mac:
			host_ip = extract_bs_ip_from_wimax_topology(ss_mac)
			if host_ip[0][0]:
                		ss_session_uptime = connection_telnet_for_session_uptime(host_ip[0][0], 23,ss_mac)
				if ss_session_uptime:
        				infotext = "Device session uptime is %s " % ss_session_uptime
					state = 0
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"

    return (state, infotext, [("session_uptime", ss_session_uptime)])


check_info["wimax_ss_session_uptime"] = {
    'check_function': check_wimax_ss_session_uptime,
    'service_description': 'wimax_ss_session_uptime',
    'has_perfdata': True,
}

#########################################################################
#	SNMP OID for the operating ptx
#########################################################################
snmp_info["wimax_ss_session_uptime"] = ( ".1.3.6.1.2.1.10.184.1.3.1.1.1", ["17.1"] )
