dashboards = [
    {
        "page_name": "rf_dashboard",
        "technology": "WiMAX",
        "dashboard_name" : "ul_modulation",
        "dashboard_type" : "string",
        "is_bh": False,
    },
    {
        "page_name": "rf_dashboard",
        "technology": "WiMAX",
        "dashboard_name" : "dl_modulation",
        "dashboard_type" : "string",
        "is_bh": False,
    },
    {
        "page_name": "rf_dashboard",
        "technology": "WiMAX",
        "dashboard_name" : "ul_cinr",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "rf_dashboard",
        "technology": "WiMAX",
        "dashboard_name" : "dl_cinr",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "rf_dashboard",
        "technology": "WiMAX",
        "dashboard_name" : "ul_rssi",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "rf_dashboard",
        "technology": "WiMAX",
        "dashboard_name" : "dl_rssi",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "rf_dashboard",
        "technology": "PMP",
        "dashboard_name" : "ul_jitter",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "rf_dashboard",
        "technology": "PMP",
        "dashboard_name" : "dl_jitter",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "rf_dashboard",
        "technology": "PMP",
        "dashboard_name" : "rereg_count",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "rf_dashboard",
        "technology": "PMP",
        "dashboard_name" : "ul_rssi",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "rf_dashboard",
        "technology": "PMP",
        "dashboard_name" : "dl_rssi",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "rf_dashboard",
        "technology": "P2P",
        "dashboard_name" : "rssi",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "rf_dashboard",
        "technology": "P2P",
        "dashboard_name" : "uas",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "rf_dashboard",
        "technology": "P2P",
        "dashboard_name" : "rssi",
        "dashboard_type" : "numeric",
        "is_bh": True,
    },
    {
        "page_name": "rf_dashboard",
        "technology": "P2P",
        "dashboard_name" : "availability",
        "dashboard_type" : "numeric",
        "is_bh": True,
    },
    {
        "page_name": "rf_dashboard",
        "technology": "P2P",
        "dashboard_name" : "uas",
        "dashboard_type" : "numeric",
        "is_bh": True,
    },
]
