dashboards = [
    {
        "page_name": "rf_dashboard",
        "technology": "WiMAX",
        "dashboard_name" : "ul_modulation",
        "dashboard_type" : "string",
        "is_bh": False,
    },
    {
        "page_name": "rf_dashboard",
        "technology": "WiMAX",
        "dashboard_name" : "dl_modulation",
        "dashboard_type" : "string",
        "is_bh": False,
    },
    {
        "page_name": "rf_dashboard",
        "technology": "WiMAX",
        "dashboard_name" : "ul_cinr",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "rf_dashboard",
        "technology": "WiMAX",
        "dashboard_name" : "dl_cinr",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "rf_dashboard",
        "technology": "WiMAX",
        "dashboard_name" : "ul_rssi",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "rf_dashboard",
        "technology": "WiMAX",
        "dashboard_name" : "dl_rssi",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "rf_dashboard",
        "technology": "PMP",
        "dashboard_name" : "ul_jitter",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "rf_dashboard",
        "technology": "PMP",
        "dashboard_name" : "dl_jitter",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "rf_dashboard",
        "technology": "PMP",
        "dashboard_name" : "rereg_count",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "rf_dashboard",
        "technology": "PMP",
        "dashboard_name" : "ul_rssi",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "rf_dashboard",
        "technology": "PMP",
        "dashboard_name" : "dl_rssi",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "rf_dashboard",
        "technology": "P2P",
        "dashboard_name" : "rssi",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "rf_dashboard",
        "technology": "P2P",
        "dashboard_name" : "uas",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "rf_dashboard",
        "technology": "P2P",
        "dashboard_name" : "rssi",
        "dashboard_type" : "numeric",
        "is_bh": True,
    },
    {
        "page_name": "rf_dashboard",
        "technology": "P2P",
        "dashboard_name" : "availability",
        "dashboard_type" : "numeric",
        "is_bh": True,
    },
    {
        "page_name": "rf_dashboard",
        "technology": "P2P",
        "dashboard_name" : "uas",
        "dashboard_type" : "numeric",
        "is_bh": True,
    },
    {
        "page_name": "main_dashboard",
        "technology": "WiMAX",
        "dashboard_name" : "temperature",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "main_dashboard",
        "technology": "P2P",
        "dashboard_name" : "latency-p2p-bh",
        "dashboard_type" : "numeric",
        "is_bh": True,
    },
    {
        "page_name": "main_dashboard",
        "technology": "PMP",
        "dashboard_name" : "latency-pmp",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "main_dashboard",
        "technology": "WiMAX",
        "dashboard_name" : "latency-wimax",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "main_dashboard",
        "technology": "All",
        "dashboard_name" : "latency-network",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "main_dashboard",
        "technology": "PMP",
        "dashboard_name" : "topology-pmp",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "main_dashboard",
        "technology": "WiMAX",
        "dashboard_name" : "topology-wimax",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "main_dashboard",
        "technology": "PMP",
        "dashboard_name" : "packetloss-pmp",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "main_dashboard",
        "technology": "WiMAX",
        "dashboard_name" : "packetloss-wimax",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "main_dashboard",
        "technology": "All",
        "dashboard_name" : "packetloss-network",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "main_dashboard",
        "technology": "WiMAX",
        "dashboard_name" : "down-wimax",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "main_dashboard",
        "technology": "PMP",
        "dashboard_name" : "down-pmp",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
    {
        "page_name": "main_dashboard",
        "technology": "All",
        "dashboard_name" : "down-network",
        "dashboard_type" : "numeric",
        "is_bh": False,
    },
]
