#!/usr/bin/python

"""
operating Frequency of ss device  Poller script.

This is part of device application. 
Poller script determines the operating frequency of device. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.1.1.2.0 from snmp agent of device at specific interval.
Device on which Frequency operating is sent to device application 

"""
# ######################################################################
# Function: check_wimax_bs_frequency_pmp2_invent
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################


def check_wimax_bs_frequency_pmp2_invent(item, _no_params, info):
    """
            check_wimax_bs_frequency_pmp2_invent function calculates the operating frequency

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - 5835

                    Raises:
                            ValueError ,Exception
"""
    state = 3
    infotext = "unknown_value"
    try:
        if info:
            if info[0][0]:
                frequency = int(info[0][0])
                if frequency < 0:
                    state = 0
                    infotext = "invalid_value_%d" % frequency
                else:
                    state = 0
                    infotext = "%d" % frequency
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"
    return (state, infotext)


check_info["wimax_bs_frequency_pmp2_invent"] = {
    'check_function': check_wimax_bs_frequency_pmp2_invent,
    'service_description': 'wimax_bs_frequency_pmp2_invent',
}

#########################################################################
#	SNMP OID for the operating frequency
#########################################################################
snmp_info["wimax_bs_frequency_pmp2_invent"] = ( ".1.3.6.1.4.1.5812.2000.11.1.1", ["1.200"] )
