#!/usr/bin/python
import binascii
import sys
from telnetlib import Telnet
import socket
import json
import os
import mysql.connector
"""
service on SS,which calculates the ss mac.

This is part of device application. 
Poller script determines the ss ip. 
poller script takes the snmp value of OID  1.3.6.1.4.1.161.19.3.3.1.13.0 from snmp agent of device at specific interval.
SS mac information is sent to device application 

"""
# ######################################################################
# Function : check_cambium_ss_mac_invent
#
# Parameters: info (SNMP Output) _no_params(No Parameters)
#
# Output: service state and plugin output
# #####################################################################




def check_cambium_reg_count(item, params, info):
    """
                check_cambium_ss_mac_invent function calculates the mac of ss

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : OK - BB1202020

                        Raises:
                               Exception
    """
    state = 3
    reg_count = None
    infotext = "unknown_value"
    warn,crit = params
    try:
        if info:
            if info[0][0]:
                ss_mac = info[0][0]
		a=binascii.b2a_hex(ss_mac)
                n = 2
                ss_mac=(':').join([a[i:i+2] for i in range(0, len(a), n)])
		if ss_mac:
			try:
				if memc:
					ss_list=memc.get(ss_mac)
					if ss_list:
						reg_count = int(ss_list[4])
			except:
				pass
			if reg_count != None:
				if reg_count > crit:
					state  = 2
				elif reg_count <= crit and reg_count >= warn:
					state = 1
				else:
					state = 0
	infotext = "Device reg_count is %s " % reg_count
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"
    return (state, infotext, [("reg_count", reg_count, warn, crit)])


check_info["cambium_reg_count"] = {
    'check_function': check_cambium_reg_count,
    'service_description': 'cambium_reg_count',
    'has_perfdata': True,
}

#################################################################
#SNMP OID value for poller script
################################################################

snmp_info["cambium_reg_count"] = ( ".1.3.6.1.2.1.2.2.1", ["6.1"] )
