#!/usr/bin/python
import binascii
import sys
from telnetlib import Telnet
import socket
import json
import os
import mysql.connector
from datetime import datetime
"""
service on SS,which calculates the ss mac.

This is part of device application. 
Poller script determines the ss ip. 
poller script takes the snmp value of OID  1.3.6.1.4.1.161.19.3.3.1.13.0 from snmp agent of device at specific interval.
SS mac information is sent to device application 

"""
# ######################################################################
# Function : check_cambium_ss_mac_invent
#
# Parameters: info (SNMP Output) _no_params(No Parameters)
#
# Output: service state and plugin output
# #####################################################################

def get_from_socket(socket_ip,socket_port, query,site,machine):
    """
    Function_name : get_from_socket (collect the query data from the socket)

    Args: site_name (poller on which monitoring data is to be collected)

    Kwargs: query (query for which data to be collectes from nagios.)

    Return : None

    raise
         Exception: SyntaxError,socket error
    """




    #my_machine = nagios_user.split('_')[0]
    my_site  = var_dir.split('/')[3]
    if site == my_site:
        socket_path = "/omd/sites/dev_slave/slave_2/var/run/live" 
        s=socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        s.connect(socket_path)
    else:
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.connect((socket_ip,socket_port))
    s.settimeout(60.0)
    s.send(query)
    s.shutdown(socket.SHUT_WR)
    output = ''
    while True:
    	try:
        	out = s.recv(100000000)
	except socket.timeout ,e:
		break
        out.strip()
	if not len(out):
		break
        output += out
    return output

def check_cambium_ul_rssi(item, params, info):
    """
                check_cambium_ss_mac_invent function calculates the mac of ss

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : OK - BB1202020

                        Raises:
                               Exception
    """
    state = 3
    ul_rssi = None
    infotext = "unknown_value"
    warn,crit = params
    ss_list = []
    this_time = datetime.now()
    t_stmp = this_time + timedelta(minutes=-(this_time.minute % 5))
    t_stmp = t_stmp.replace(second=0,microsecond=0)
    current_time =int(time.mktime(t_stmp.timetuple()))
    try:
        if info:
            if info[0][0]:
                ss_mac = info[0][0]
		a=binascii.b2a_hex(ss_mac)
                n = 2
                ss_mac=(':').join([a[i:i+2] for i in range(0, len(a), n)])
		
		if ss_mac:
			try:
				if memc:
					ss_list=memc.get(ss_mac)
					if ss_list:
						ul_rssi = int(ss_list[2])
			except:
				pass
			if ul_rssi != None:
				if ul_rssi < crit:
					state  = 2
				elif ul_rssi > crit and ul_rssi < warn:
					state = 1
				else:
					state = 0
				if memc:
					key1 = str(g_hostname) + "_ul_rssi" + "_" + str(current_time)
					memc.set(key1,ul_rssi,600)
	infotext = "Device uplink signal strength indication is %s" % (ul_rssi)
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown"
    return (state, infotext, [("ul_rssi", ul_rssi, warn, crit)])


check_info["cambium_ul_rssi"] = {
    'check_function': check_cambium_ul_rssi,
    'service_description': 'cambium_ul_rssi',
    'has_perfdata': True,
}

#################################################################
#SNMP OID value for poller script
################################################################

snmp_info["cambium_ul_rssi"] = ( ".1.3.6.1.2.1.2.2.1", ["6.1"] )
