#!/usr/bin/python

import sys
from telnetlib import Telnet
import socket
import json
import os

"""
operating Frequency of ss device  Poller script.

This is part of device application. 
Poller script determines the operating ptx of device. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.1.1.2.0 from snmp agent of device at specific interval.
Device on which Frequency operating is sent to device application 

"""
# ######################################################################
# Function: check_mrotek_port_autonegotiation
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################


def connection_telnet_for_pmp_bw(hostip, port ,item):
        """
        Connects to a socket, checks for the WELCOME-MSG and closes the
        connection.
        Returns nothing.
    
        """
        try:
                tn = Telnet(hostip,port,timeout=3)
        except socket.timeout:
		pmp1_bw = None
		pmp2_bw = None
		return pmp1_bw,pmp2_bw
	tn.read_until("Login:")
        tn.write("admin" + "\r\n")
        tn.read_until("Password:")
        tn.write("admin" + "\r\n")
        tn.write("show interface client %s\r\n" % item)
        tn.write("exit\r\n")
        data = tn.read_all()
	pmp1_bw = None
	pmp2_bw = None
	try:
		 for i,row in enumerate(data.split("\n")):
			try:
                        	if "c:%s" % item in row:
                                	pmp1_bw = int([r for r in row.split()][-1])
			except:
				pmp1_bw = None
			try:
                        	if "1/2 bandwidth" in row:
                                	pmp2_bw = int([r for r in row.split()][-1])
					break
			except:
				pmp2_bw = None
        except:
		pmp1_bw = None
		pmp2_bw = None
	return pmp1_bw ,pmp2_bw
                                

def check_mrotek_port_autonegotiation(item, _no_params, info):
    """
            check_mrotek_port_autonegotiation function calcdlates the operating ptx

            Args:
                    item (str) Specific item on SNMP output on which we want to filter resdlts

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - 5835

                    Raises:
                            ValueError ,Exception
    """
    state = 3
    infotext = "unknown_value"
    try:
	if info[1]:
                bs_ip = info[1][0]
                if bs_ip:
                	pmp1_bw,pmp2_bw =connection_telnet_for_port_status(bs_ip, 23)
			if pmp1_bw or pmp2_bw:
				infotext = "pmp1_bw=%s pmp2_bw=%s" % (pmp1_bw,pmp2_bw)
				state = 0
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"

    return (state, infotext)


check_info["mrotek_port_autonegotiation"] = {
    'check_function': check_mrotek_port_autonegotiation,
    'service_description': 'mrotek_port_autonegotiation',
}

#########################################################################
#	SNMP OID for the operating ptx
#########################################################################
snmp_info["mrotek_port_autonegotiation"] = ( ".1.3.6.1.4.1.5812.2000.4.1.1", ["1.0"] )
