#!/usr/bin/python
# ######################################################################
# Function: check_rad5k_ss_ul_utilization
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################

def live_query_for_rad5k_ss_ul_utilization(serial_number):
        """
            live_query_for_rad5k_ss_ul_utilization function calculates the SS UpLink Utilization
            by extracting data from memory using SS Serial number as key from memcache;
            if data is not present in memcache it retrieves the data from Livestatus by making a socket
            connection and reading plugin output of 'rad5k_topology_discover' through the details
            of its corresponded Base Station whose details are fetched from memcache or MySQL DB(if not present in memcache)

            Args:
                    ss_host_serial_number(str) Sub Station Serial Number

            Returns:

                    ul_utilization(string): SS UpLink Utilization

            Raises:
                    Exception


        """

        exit_value = 3
        ul_utilization = None
        bs_params = None
        if memc:
                key = serial_number + "_param"
                value_list = memc.get(key)
                if value_list:
			#print value_list
                        try:
                                ul_utilization = value_list[3]
                        except:
				pass
        return ul_utilization
def check_rad5k_ss_ul_utilization(item, _no_params, info):
	"""
            check_rad5k_ss_ul_utilization function calculates the SS Uplink Utilization

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                                    3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - SS uplink utilization is 0.04

                    Raises:
                            ValueError ,Exception
	"""
	state = 3
	infotext = "unknown_value"
	ul_utilization= None
	try:
		if info :
			ss_serial_number = info[0][0]
			#print ss_serial_number
	        	if ss_serial_number:
        	        	ul_utilization =live_query_for_rad5k_ss_ul_utilization(ss_serial_number)
	                	if ul_utilization is not None:
	                        	infotext = "SS uplink utilization is %s" % ul_utilization
	                        	state = 0
				else:
					infotext = "SS uplink utilization not available"
					state = 3
					ul_utilization = None
	except ValueError:
        	infotext = "type_mismatch_value"
	except Exception,e:
	        infotext = "unknown_value"

	return (state, infotext,[("ul_utilization", ul_utilization)])



check_info["rad5k_ss_ul_utilization"] = {
    'check_function': check_rad5k_ss_ul_utilization,
    'service_description': 'rad5k_ss_ul_utilization',
    'has_perfdata': True,
}

#########################################################################
#       SNMP OID for the uplink utilization
#########################################################################
snmp_info["rad5k_ss_ul_utilization"] = ( ".1.3.6.1.4.1.4458.1000.1.1", ["29.0"] )
#.1.3.6.1.4.1.4458.1000.1.1.29.0

