#!/usr/bin/python

# ##################################################################
# Function : check_rad5k_data_rate_invent
#
#  Parameters: info(SNMP output) ,params(parameters to check the service state) 
#
#  Output: service state,plugin output ,performance data
##################################################################


def check_rad5k_data_rate_invent(item, _no_params, info):
	"""
            check_rad5k_data_rate_invent function calculates the BS Transmission Ratio/Data Rate

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                                    3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - data_rate=50.0

                    Raises:
                            ValueError ,Exception

	"""
	#print info
	state = 3
	infotext = "unknown_value"
	data_rate = 0
	try:
		if info:
			data_rate = 0
			if info[0][0]:
				data_rate = saveint(info[0][0]) / 10.0
				infotext = "data_rate=%.2f" % (data_rate)
				state= 0
	except:
        	infotext = "unknown_value"
   
	return (state, infotext,[("data_rate","%.2f" % data_rate)])


check_info["rad5k_data_rate_invent"] = {
    'check_function': check_rad5k_data_rate_invent,
    'service_description': 'rad5k_data_rate_invent',
    'has_perfdata': True,
}

#######################################################################
#	SNMP OID FOR BS DATA RATE
#######################################################################
snmp_info["rad5k_data_rate_invent"] = ( ".1.3.6.1.4.1.4458.1000.1.5.60", ["2.0"] ) 

