#!/usr/bin/python
# ######################################################################
# Function: check_rad5k_ss_dl_utilization
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################
def live_query_for_rad5k_ss_dl_utilization(serial_number):
        """
            live_query_for_rad5k_ss_dl_utilization function calculates the SS DownLink Utilization
            by extracting data from memory using SS Serial number as key from memcache;
            if data is not present in memcache it retrieves the data from Livestatus by making a socket
            connection and reading plugin output of 'rad5k_topology_discover' through the details
            of its corresponded Base Station whose details are fetched from memcache or MySQL DB(if not present in memcache)

            Args:
                    ss_host_serial_number(str) Sub Station Serial Number

            Returns:

                    dl_utilization(string): SS DownLink Utilization

            Raises:
                    Exception


        """
        exit_value = 3
        dl_utilization = None
	bs_params = None
        if memc:
                key = "%s_param" % serial_number
                value_list = memc.get(key)
		#print value_list
                if value_list:
                        try:
                                dl_utilization = value_list[2]
                        except:
                                dl_utilization = None
        return dl_utilization

def check_rad5k_ss_dl_utilization(item, _no_params, info):
	"""
           check_rad5k_ss_dl_utilization function calculates the SS Downlink Utilization

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                                    3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - SS downlink utilization is 0.04

            Raises:
                    ValueError ,Exception
	"""
	state = 3
	infotext = "unknown_value"
	dl_utilization= None
	if info :
		try:
        		ss_serial_number = info[0][0]
	        	if ss_serial_number:
        	        	dl_utilization =live_query_for_rad5k_ss_dl_utilization(ss_serial_number)
	                	if dl_utilization is not None :
        	                	infotext = "SS downlink utilization is %s" % dl_utilization
                	        	state = 0
				else:
					infotext = "SS downlink utilization not available"
					dl_utilization = None
					state = 3
		except ValueError:
        		infotext = "type_mismatch_value"
		except:
        		infotext = "unknown_value"

	return (state, infotext,[("dl_utilization", dl_utilization)])

check_info["rad5k_ss_dl_utilization"] = {
    'check_function': check_rad5k_ss_dl_utilization,
    'service_description': 'rad5k_ss_dl_utilization',
    'has_perfdata': True,
}

#########################################################################
#       SNMP OID for the downlink utilization
#########################################################################
snmp_info["rad5k_ss_dl_utilization"] = (  ".1.3.6.1.4.1.4458.1000.1.1", ["29.0"] )


