#!/usr/bin/python
# ######################################################################
# Function: check_rad5k_bs_ip_invent
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################
def check_rad5k_bs_ip_invent(item, _no_params, info):
	
    """
            check_rad5k_bs_ip_invent function calculates the uplink utilization

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                                    3: unknown
                    infotext(string):
                                    plugin output
                                    Example :  OK - bs ip: 10.169.241.3

                    Raises:
                            ValueError ,Exception

    """ 
    state = 3
    infotext = "unknown_value"
    bs_ip = ""        
    try:
        if info:
            if info[0][0]:
		bs_ip = info[0][0]
		state = 0
                infotext = "bs ip: %s" % bs_ip                                
    except ValueError :
	infotext = "type_mismatch_value"
    except:
	infotext = "unknown_value"
		
    return (state,infotext,[("bs_ip",bs_ip)])
                
check_info["rad5k_bs_ip_invent"] = {
    'check_function' :  check_rad5k_bs_ip_invent,
    'service_description' : "rad5k_bs_ip_invent",
    'has_perfdata': True
}
#########################################################################
#       SNMP OID for the HBS IP
#########################################################################
snmp_info['rad5k_bs_ip_invent'] = (".1.3.6.1.4.1.4458.1000.1.1",["6.0"])
