#!/usr/bin/python
# ######################################################################
# Function: check_rad5k_mimo_diversity_invent
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################
dic_type = { 
	1 : 'mimo',
	2 : 'diversity',
	3 : 'auto'}

def check_rad5k_mimo_diversity_invent(item, _no_params, info):
	
    """
            check_rad5k_mimo_diversity_invent function calculates the uplink utilization

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                                    3: unknown
                    infotext(string):
                                    plugin output
                                    Example :  OK - MIMO/Diversity/Auto : mimo

                    Raises:
                            ValueError ,Exception

    """ 
    state = 3
    infotext = "unknown_value"
    type = ""        
    try:
        if info:
            if info[0][0]:
		x = int(info[0][0])
		if dic_type.get(x):					
			type = dic_type.get(x)
			state = 0
			infotext = "MIMO/Diversity/Auto : %s " % type                            
    except ValueError :
	infotext = "type_mismatch_value"
    except:
	infotext = "unknown_value"
		
    return (state,infotext,[("mimo_diversity",type)])
                
check_info["rad5k_mimo_diversity_invent"] = {
    'check_function' :  check_rad5k_mimo_diversity_invent,
    'service_description' : "rad5k_mimo_diversity_invent",
    'has_perfdata': True
}
#########################################################################
#       SNMP OID for MIMO/DIVERSITY/AUTO
#########################################################################
snmp_info['rad5k_mimo_diversity_invent'] = (".1.3.6.1.4.1.4458.1000.1",["5.58"])
