#!/usr/bin/python

# ######################################################################
# Function: check_rad5k_eth_link_status
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################

link_state = {
	1 : 'up',
	2 : 'down',
	3 : 'testing'}

def check_rad5k_eth_link_status(item, _no_params, info):
    """
            check_rad5k_eth_link_status function calculates the uplink utilization

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                                    3: unknown
                    infotext(string):
                                    plugin output
                                    Example :  OK - ethernet link status: up

                    Raises:
                            ValueError ,Exception

    """ 
    state = 3
    infotext = "unknown_value"
    state_type = ""  
    try:
        if info:
            if info[0][0]:
                x = int(info[0][0])
		if link_state.get(x):
			state_type = link_state.get(x)
			state = 0
			infotext = "ethernet link status: %s " % state_type
    except ValueError :
	infotext = "type_mismatch_value"
    except:
	infotext = "unknown_value"
		
    return (state,infotext,[("link_state",state_type)])
                
check_info["rad5k_eth_link_status"] = {
    'check_function' :  check_rad5k_eth_link_status,
    'service_description' : "rad5k_eth_link_status",
    'has_perfdata': True
}
#########################################################################
#       SNMP OID for the Ethernet Link Status
#########################################################################
snmp_info['rad5k_eth_link_status'] = (".1.3.6.1.2.1.2.2",["1.8"])
