#!/usr/bin/python

# ######################################################################
# Function: check_rad5k_ss_serial_no_invent
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################

def check_rad5k_ss_serial_no_invent(item, _no_params, info):
    """
            check_rad5k_ss_srial_no_invent function calculates the uplink utilization

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                                    3: unknown
                    infotext(string):
                                    plugin output
                                    Example :  OK - serial number: P11190I100A009A5 

                    Raises:
                            ValueError ,Exception

    """ 
    state = 3
    infotext = "unknown_value"
    serial_number = ""
        
    try:
        if info:
            if info[0][0]:
		serial_number = info[0][0]
                state = 0
                infotext = "serial number: %s" % serial_number                                
    except ValueError :
	infotext = "type_mismatch_value"
    except:
	infotext = "unknown_value"
		
    return (state,infotext,[("serial_number",serial_number)])
                
check_info["rad5k_ss_serial_no_invent"] = {
    'check_function' :  check_rad5k_ss_serial_no_invent,
    'service_description' : "rad5k_ss_serial_no_invent",
    'has_perfdata': True
}
#########################################################################
#       SNMP OID for the Serial Number
#########################################################################
snmp_info['rad5k_ss_serial_no_invent'] = (".1.3.6.1.4.1.4458.1000.1.1",["29.0"])

