#!/usr/bin/python

import sys
from telnetlib import Telnet
import socket
import json
import os
import binascii
import mysql.connector
"""
operating Frequency of ss device  Poller script.

This is part of device application. 
Poller script determines the operating ptx of device. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.1.1.2.0 from snmp agent of device at specific interval.
Device on which Frequency operating is sent to device application 

"""
# ######################################################################
# Function: check_wimax_ss_sector_id
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################




def live_query_ss_sector_id(mac):
        """
        Connects to a socket, checks for the WELCOME-MSG and closes the
        connection.
        Returns nothing.
    
        """
	ss_sector_id = None
	ss_params = None
	if memc:
		value_list = memc.get(mac)
		if value_list:
			try:
				ss_sector_id = value_list[9]
			except:
				ss_sector_id = None
		
        return ss_sector_id



def check_wimax_ss_sector_id(item, _no_params, info):
    """
            check_wimax_ss_sector_id function calcdlates the operating ptx

            Args:
                    item (str) Specific item on SNMP output on which we want to filter resdlts

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - 5835

                    Raises:
                            ValueError ,Exception
"""
    state = 3
    infotext = "unknown_value"
    ss_sector_id =None
    try:
	if info[1]:
                ss_mac = info[1][0]
		a=binascii.b2a_hex(ss_mac)
		n = 2
		ss_mac=(':').join([a[i:i+2] for i in range(0, len(a), n)])
                if ss_mac:
                        ss_sector_id = live_query_ss_sector_id(ss_mac )
                        state = 0
        		infotext = "Device sector_id is %s " % ss_sector_id
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"

    return (state, infotext, [("ss_sector_id", ss_sector_id)])


check_info["wimax_ss_sector_id"] = {
    'check_function': check_wimax_ss_sector_id,
    'service_description': 'wimax_ss_sector_id',
    'has_perfdata': True,
}

#########################################################################
#	SNMP OID for the operating ptx
#########################################################################
snmp_info["wimax_ss_sector_id"] = ( ".1.3.6.1.2.1.10.184.1.3.1.1.1", ["17.1"] )
