#!/usr/bin/python

import sys
from telnetlib import Telnet
import socket
import json
import os
import binascii
import mysql.connector
"""
operating Frequency of ss device  Poller script.

This is part of device application. 
Poller script determines the operating ptx of device. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.1.1.2.0 from snmp agent of device at specific interval.
Device on which Frequency operating is sent to device application 

"""
# ######################################################################
# Function: check_wimax_ss_duplex_status
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################


def check_wimax_ss_duplex_status(item, _no_params, info):
    """
            check_wimax_ss_duplex_status function calcdlates the operating ptx

            Args:
                    item (str) Specific item on SNMP output on which we want to filter resdlts

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - 5835

                    Raises:
                            ValueError ,Exception
    """
    state = 3
    infotext = "unknown_value"
    duplex_value= ''
    try:
	    if memc:
		    value_list = memc.get('%s_ss_port_params' % g_hostname)
		    if value_list:
		    	duplex_value = value_list[2]
    except:
	    pass
    try:
	if duplex_value:
		duplex_value = duplex_value.strip('\r')
		duplex_value = duplex_value.replace(' ','_')
		infotext = "SS ethernet duples status is %s" % duplex_value
		state = 0
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"

    return (state, infotext,[("duplex", duplex_value)])


check_info["wimax_ss_duplex_status"] = {
    'check_function': check_wimax_ss_duplex_status,
    'service_description': 'wimax_ss_duplex_status',
    'has_perfdata' : True,
}

#########################################################################
#	SNMP OID for the operating ptx
#########################################################################
snmp_info["wimax_ss_duplex_status"] = ( ".1.3.6.1.2.1.10.184.1.3.1.1.1", ["17.1"] )
