#!/usr/bin/python

import sys
from telnetlib import Telnet
import socket
import json
import os
import binascii
import mysql.connector
"""
operating Frequency of ss device  Poller script.

This is part of device application. 
Poller script determines the operating ptx of device. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.1.1.2.0 from snmp agent of device at specific interval.
Device on which Frequency operating is sent to device application 

"""
# ######################################################################
# Function: check_wimax_ul_intrf
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################



def live_query_ul_intrf(mac):
        """
        Connects to a socket, checks for the WELCOME-MSG and closes the
        connection.
        Returns nothing.
    
        """
	ul_intrf = None
	if memc:
		value_list = memc.get(mac)
		if value_list:
			try:
				ul_intrf = value_list[6]
			except:
				ul_intrf = None
        return ul_intrf



def check_wimax_ul_intrf(item, params, info):
    """
            check_wimax_ul_intrf function calculates the operating ptx

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - 5835

                    Raises:
                            ValueError ,Exception
"""
    state = 3
    infotext = "unknown_value"
    ul_intrf = None
    warn,crit = params
    try:
	mac_info = sum(info,[])
        mac_list=map(lambda x: convert(x),mac_info)
        if mac_list[1] != '00:00:00:00:00:00':
                ss_mac= mac_list[1]
        else:
                index =[i for i, e in enumerate(mac_list) if e != '00:00:00:00:00:00']
                index =index[0]
                ss_mac = mac_list[index]
	if ss_mac:
		ul_intrf = live_query_ul_intrf(ss_mac )
		if ul_intrf:
			if ul_intrf.lower()  == crit.lower():
				state  = 2
				state_string = "critical"
			elif ul_intrf.lower()  == warn.lower():
				state = 1
				state_string = "warning"
			elif ul_intrf.lower() == "Norm".lower():
				state = 0
				state_string = "ok"
        		infotext = "Device ul intrf is %s " % ul_intrf
			try:
				if memc:
					value_list= []
					key = g_hostname + "_wimax_ul_intrf_sev"
					value = memc.get(key)
					if value and type(value) is list and len(value) == 1:
						value_list.append(value[0])	
						value_list.append(state_string)	
					elif value and type(value) is list and len(value) == 2:
						value_list.append(value[1])
						value_list.append(state_string)
					elif not value:
						value_list.append(state_string)
					memc.set(key,value_list,360)
			except:
				pass
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"

    return (state, infotext, [("ul_intrf", ul_intrf)])


check_info["wimax_ul_intrf"] = {
    'check_function': check_wimax_ul_intrf,
    'service_description': 'wimax_ul_intrf',
    'has_perfdata': True,
}

#########################################################################
#	SNMP OID for the operating ptx
#########################################################################
snmp_info["wimax_ul_intrf"] = ( ".1.3.6.1.2.1.10.184.1.3.1.1.1", ["17.1"] )
