#!/usr/bin/python

import sys
from telnetlib import Telnet
import socket
import json
import os

"""
operating Frequency of ss device  Poller script.

This is part of device application. 
Poller script determines the operating ptx of device. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.1.1.2.0 from snmp agent of device at specific interval.
Device on which Frequency operating is sent to device application 

"""
# ######################################################################
# Function: check_wimax_p2_cmd_rx_pwr_invent
#
# Parameters: info (SNMP Ouput) _no_params (No Parameters)
#
# Output: service state ,plugin output
# ######################################################################


def check_wimax_p2_cmd_rx_pwr_invent(item, params, info):
    """
            check_wimax_p2_cmd_rx_pwr_invent function calcdlates the operating ptx

            Args:
                    item (str) Specific item on SNMP output on which we want to filter resdlts

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                    state (int) :
                                    0 : OK
                                    1 : Warning
                                    2: Critical
                3: unknown
                    infotext(string):
                                    plugin output
                                    Example : OK - 5835

                    Raises:
                            ValueError ,Exception
"""
    state = 3
    infotext = "unknown_value"
    warn,crit =params
    p2_rx_pwr = ''
    try:
	    if memc:
		    value_list = memc.get('%s_bs_params' % g_hostname)
		    if value_list:
		    	p2_rx_pwr = value_list[10]
    except:
	    pass
    try:
	if p2_rx_pwr:
		p2_rx_pwr = int(p2_rx_pwr)
		if p2_rx_pwr  == -75:
			state = 0	
		elif p2_rx_pwr < crit:
			state = 2
		elif (p2_rx_pwr == crit) or (p2_rx_pwr == warn):
			state = 1
		infotext = "%s" % (p2_rx_pwr)
    except ValueError:
        infotext = "type_mismatch_value"
    except:
        infotext = "unknown_value"

    return (state, infotext,[("p2_cmd_rx_pwr",p2_rx_pwr,warn,crit)])


check_info["wimax_p2_cmd_rx_pwr_invent"] = {
    'check_function': check_wimax_p2_cmd_rx_pwr_invent,
    'service_description': 'wimax_p2_cmd_rx_pwr_invent',
    'has_perfdata':True,
}

#########################################################################
#	SNMP OID for the operating ptx
#########################################################################
snmp_info["wimax_p2_cmd_rx_pwr_invent"] = ( ".1.3.6.1.4.1.5812.2000.4.1.1", ["1.0"] )
