# File containing default checks to be added into rules.mk
default_extra_service_conf = {}

default_checks = [
		(['Radwin2KBS'], ['@all'], 'radwin_rssi', None, (-50, -60)),
		(['Radwin2KBS'], ['@all'], 'radwin_uptime', None, ()),
		(['Radwin2KBS'], ['@all'], 'radwin_uas', None, ()),
		(['Radwin2KBS'], ['@all'], 'radwin_dl_utilization', None, ()),
		(['Radwin2KBS'], ['@all'], 'radwin_ul_utilization', None, ()),
		(['Radwin2KBS'], ['@all'], 'radwin_cbw_invent', None, ()),
		(['Radwin2KBS'], ['@all'], 'radwin_frequency_invent', None, ()),
		(['Radwin2KBS'], ['@all'], 'radwin_idu_sn_invent', None, ()),
		(['Radwin2KBS'], ['@all'], 'radwin_odu_sn_invent', None, ()),
		(['Radwin2KBS'], ['@all'], 'radwin_link_distance_invent', None, ()),
		(['Radwin2KBS'], ['@all'], 'radwin_mimo_diversity_invent', None, ()),
		(['Radwin2KBS'], ['@all'], 'radwin_producttype_invent', None, ()),
		(['Radwin2KBS'], ['@all'], 'radwin_service_throughput', None, ()),
		(['Radwin2KBS'], ['@all'], 'radwin_ssid_invent', None, ()),
		(['Radwin2KBS'], ['@all'], 'radwin_autonegotiation_status', None, ()),
		(['Radwin2KBS'], ['@all'], 'radwin_link_ethernet_status', None, ()),
		(['Radwin2KBS'], ['@all'], 'radwin_port_mode_status', None, ()),
		(['Radwin2KBS'], ['@all'], 'radwin_port_speed_status', None, ()),
		(['Radwin2KBS'], ['@all'], 'radwin_sync_state_status', None, ()),
		(['Radwin2KSS'], ['@all'], 'radwin_rssi', None, (-50, -60)),
		(['Radwin2KSS'], ['@all'], 'radwin_uptime', None, ()),
		(['Radwin2KSS'], ['@all'], 'radwin_uas', None, ()),
		(['Radwin2KSS'], ['@all'], 'radwin_dl_utilization', None, ()),
		(['Radwin2KSS'], ['@all'], 'radwin_ul_utilization', None, ()),
		(['Radwin2KSS'], ['@all'], 'radwin_cbw_invent', None, ()),
		(['Radwin2KSS'], ['@all'], 'radwin_frequency_invent', None, ()),
		(['Radwin2KSS'], ['@all'], 'radwin_idu_sn_invent', None, ()),
		(['Radwin2KSS'], ['@all'], 'radwin_odu_sn_invent', None, ()),
		(['Radwin2KSS'], ['@all'], 'radwin_link_distance_invent', None, ()),
		(['Radwin2KSS'], ['@all'], 'radwin_mimo_diversity_invent', None, ()),
		(['Radwin2KSS'], ['@all'], 'radwin_producttype_invent', None, ()),
		(['Radwin2KSS'], ['@all'], 'radwin_service_throughput', None, ()),
		(['Radwin2KSS'], ['@all'], 'radwin_ssid_invent', None, ()),
		(['Radwin2KSS'], ['@all'], 'radwin_autonegotiation_status', None, ()),
		(['Radwin2KSS'], ['@all'], 'radwin_link_ethernet_status', None, ()),
		(['Radwin2KSS'], ['@all'], 'radwin_port_mode_status', None, ()),
		(['Radwin2KSS'], ['@all'], 'radwin_port_speed_status', None, ()),
		(['Radwin2KSS'], ['@all'], 'radwin_sync_state_status', None, ()),
		]

default_snmp_ports = [
		(161, ['Radwin2KBS'], ['@all']),
		(161, ['Radwin2KSS'], ['@all']),
		]

default_snmp_communities = [
		('public', ['Radwin2KBS'], ['@all']),
		('public', ['Radwin2KSS'], ['@all']),
		]

default_extra_service_conf['normal_check_interval'] = [
		(5, [], ['@all'], 'Check_MK'),
		(5, ['Radwin2KBS'], ['@all'], 'radwin_rssi'),
		(5, ['Radwin2KBS'], ['@all'], 'radwin_uptime'),
		(5, ['Radwin2KBS'], ['@all'], 'radwin_uas'),
		(5, ['Radwin2KBS'], ['@all'], 'radwin_dl_utilization'),
		(5, ['Radwin2KBS'], ['@all'], 'radwin_ul_utilization'),
		(5, ['Radwin2KBS'], ['@all'], 'radwin_cbw_invent'),
		(5, ['Radwin2KBS'], ['@all'], 'radwin_frequency_invent'),
		(5, ['Radwin2KBS'], ['@all'], 'radwin_idu_sn_invent'),
		(5, ['Radwin2KBS'], ['@all'], 'radwin_odu_sn_invent'),
		(5, ['Radwin2KBS'], ['@all'], 'radwin_link_distance_invent'),
		(5, ['Radwin2KBS'], ['@all'], 'radwin_mimo_diversity_invent'),
		(5, ['Radwin2KBS'], ['@all'], 'radwin_producttype_invent'),
		(5, ['Radwin2KBS'], ['@all'], 'radwin_service_throughput'),
		(5, ['Radwin2KBS'], ['@all'], 'radwin_ssid_invent'),
		(5, ['Radwin2KBS'], ['@all'], 'radwin_autonegotiation_status'),
		(5, ['Radwin2KBS'], ['@all'], 'radwin_link_ethernet_status'),
		(5, ['Radwin2KBS'], ['@all'], 'radwin_port_mode_status'),
		(5, ['Radwin2KBS'], ['@all'], 'radwin_port_speed_status'),
		(5, ['Radwin2KSS'], ['@all'], 'radwin_rssi'),
		(5, ['Radwin2KSS'], ['@all'], 'radwin_uptime'),
		(5, ['Radwin2KSS'], ['@all'], 'radwin_uas'),
		(5, ['Radwin2KSS'], ['@all'], 'radwin_dl_utilization'),
		(5, ['Radwin2KSS'], ['@all'], 'radwin_ul_utilization'),
		(5, ['Radwin2KSS'], ['@all'], 'radwin_cbw_invent'),
		(5, ['Radwin2KSS'], ['@all'], 'radwin_frequency_invent'),
		(5, ['Radwin2KSS'], ['@all'], 'radwin_idu_sn_invent'),
		(5, ['Radwin2KSS'], ['@all'], 'radwin_odu_sn_invent'),
		(5, ['Radwin2KSS'], ['@all'], 'radwin_link_distance_invent'),
		(5, ['Radwin2KSS'], ['@all'], 'radwin_mimo_diversity_invent'),
		(5, ['Radwin2KSS'], ['@all'], 'radwin_producttype_invent'),
		(5, ['Radwin2KSS'], ['@all'], 'radwin_service_throughput'),
		(5, ['Radwin2KSS'], ['@all'], 'radwin_ssid_invent'),
		(5, ['Radwin2KSS'], ['@all'], 'radwin_autonegotiation_status'),
		(5, ['Radwin2KSS'], ['@all'], 'radwin_link_ethernet_status'),
		(5, ['Radwin2KSS'], ['@all'], 'radwin_port_mode_status'),
		(5, ['Radwin2KSS'], ['@all'], 'radwin_port_speed_status'),
		(5, ['Radwin2KSS'], ['@all'], 'radwin_sync_state_status'),
		(5, ['Radwin2KSS'], ['@all'], 'radwin_sync_state_status'),
		]
