# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import download_center.models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('download_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSOutageFaultDaily',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('organization', models.CharField(max_length=150, verbose_name=b'Organization')),
                ('city', models.CharField(max_length=200, verbose_name=b'City')),
                ('fault_type', models.CharField(max_length=100, verbose_name=b'Type of Fault')),
                ('outage_min_per_site', models.CharField(max_length=100, verbose_name=b'Outage Per Site(Min.)')),
                ('outage_count', models.IntegerField(default=0, verbose_name=b'Outage Count')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name=b'Uploaded At')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BSOutageFaultMonthly',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('organization', models.CharField(max_length=150, verbose_name=b'Organization')),
                ('city', models.CharField(max_length=200, verbose_name=b'City')),
                ('fault_type', models.CharField(max_length=100, verbose_name=b'Type of Fault')),
                ('outage_min_per_site', models.CharField(max_length=100, verbose_name=b'Outage Per Site(Min.)')),
                ('outage_count', models.IntegerField(default=0, verbose_name=b'Outage Count')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name=b'Uploaded At')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BSOutageFaultWeekly',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('organization', models.CharField(max_length=150, verbose_name=b'Organization')),
                ('city', models.CharField(max_length=200, verbose_name=b'City')),
                ('fault_type', models.CharField(max_length=100, verbose_name=b'Type of Fault')),
                ('outage_min_per_site', models.CharField(max_length=100, verbose_name=b'Outage Per Site(Min.)')),
                ('outage_count', models.IntegerField(default=0, verbose_name=b'Outage Count')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name=b'Uploaded At')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BSOutageMainDaily',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('organization', models.CharField(max_length=150, verbose_name=b'Organization')),
                ('week_number', models.CharField(max_length=100, verbose_name=b'Week of the Year')),
                ('ticket_number', models.CharField(max_length=150, verbose_name=b'Trouble Ticket Number')),
                ('total_affected_bs', models.IntegerField(default=0, verbose_name=b'Number of BS Affected')),
                ('city', models.CharField(max_length=200, verbose_name=b'City')),
                ('type_of_city', models.CharField(max_length=100, verbose_name=b'Type of City')),
                ('bs_name', models.CharField(max_length=255, verbose_name=b'BaseStation Name')),
                ('bs_type', models.CharField(max_length=100, verbose_name=b'BaseStation Type')),
                ('fault_type', models.CharField(max_length=100, verbose_name=b'Type of Fault')),
                ('bs_ip', models.GenericIPAddressField(verbose_name=b'BS IP Address')),
                ('bs_sw_version', models.CharField(max_length=100, verbose_name=b'BS Software Version')),
                ('total_affected_sector', models.IntegerField(default=0, verbose_name=b'Number of Sectors Affected')),
                ('switch_reachability', models.CharField(max_length=150, verbose_name=b'Switch Reachability')),
                ('outage_timestamp', models.DateTimeField(null=True, verbose_name=b'Outage Date And Time', blank=True)),
                ('restored_timestamp', models.DateTimeField(null=True, verbose_name=b'Restored Date And Time', blank=True)),
                ('alarm_restored_timestamp', models.DateTimeField(null=True, verbose_name=b'Alarm Restored Date And Time', blank=True)),
                ('outage_min_per_site', models.CharField(max_length=100, verbose_name=b'Outage Per Site(Min.)')),
                ('mttr_hrs', models.FloatField(verbose_name=b'MTTR Hrs')),
                ('mttr', models.CharField(max_length=150, verbose_name=b'MTTR')),
                ('outage_total_min', models.IntegerField(default=0, verbose_name=b'Outage Total(Min.)')),
                ('alarm_outage_min', models.IntegerField(default=0, verbose_name=b'Alarm Outage(Min.)')),
                ('total_affected_enterprise_ss', models.IntegerField(default=0, verbose_name=b'Number of Enterprise SS Affected')),
                ('total_affected_retail_ss', models.IntegerField(default=0, verbose_name=b'Number of Retail SS Affected')),
                ('l1_engg_name', models.CharField(max_length=200, verbose_name=b'Name of L1 Engineer')),
                ('l2_engg_name', models.CharField(max_length=200, verbose_name=b'Name of L2 Engineer')),
                ('call_assigned_to', models.CharField(max_length=200, verbose_name=b'Call Assigned To')),
                ('last_modified_by', models.CharField(max_length=200, verbose_name=b'Last Modified By')),
                ('tac_tt_number', models.IntegerField(default=0, verbose_name=b'Tac TT Number')),
                ('cause_code', models.CharField(max_length=150, verbose_name=b'Cause Code')),
                ('sub_cause_code', models.CharField(max_length=150, verbose_name=b'Sub Cause Code')),
                ('unit_replaced', models.CharField(max_length=100, verbose_name=b'Unit Replaced')),
                ('equipment_replaced', models.CharField(max_length=100, verbose_name=b'Equipment Replaced')),
                ('old_sr_number', models.CharField(max_length=128, verbose_name=b'Old Sno.')),
                ('new_sr_number', models.CharField(max_length=128, verbose_name=b'New Sno.')),
                ('alarm_observer', models.CharField(max_length=255, verbose_name=b'Alarm Observed')),
                ('delay', models.IntegerField(default=0, verbose_name=b'Delay')),
                ('delay_reason', models.CharField(max_length=255, verbose_name=b'Delay Reason')),
                ('restore_action', models.CharField(max_length=255, verbose_name=b'Action Taken to Restore the BS')),
                ('fault_description', models.TextField(null=True, verbose_name=b'Remark/Detail Fault Description', blank=True)),
                ('status', models.CharField(max_length=150, verbose_name=b'Status')),
                ('infra_provider', models.CharField(max_length=150, verbose_name=b'INFRA Provider')),
                ('site_id', models.CharField(max_length=150, verbose_name=b'Site ID')),
                ('spot_cases', models.IntegerField(default=0, verbose_name=b'Spot Cases')),
                ('fault_history', models.TextField(null=True, verbose_name=b'Fault History', blank=True)),
                ('rfo', models.CharField(max_length=200, verbose_name=b'RFO')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name=b'Uploaded At')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BSOutageMainMonthly',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('organization', models.CharField(max_length=150, verbose_name=b'Organization')),
                ('week_number', models.CharField(max_length=100, verbose_name=b'Week of the Year')),
                ('ticket_number', models.CharField(max_length=150, verbose_name=b'Trouble Ticket Number')),
                ('total_affected_bs', models.IntegerField(default=0, verbose_name=b'Number of BS Affected')),
                ('city', models.CharField(max_length=200, verbose_name=b'City')),
                ('type_of_city', models.CharField(max_length=100, verbose_name=b'Type of City')),
                ('bs_name', models.CharField(max_length=255, verbose_name=b'BaseStation Name')),
                ('bs_type', models.CharField(max_length=100, verbose_name=b'BaseStation Type')),
                ('fault_type', models.CharField(max_length=100, verbose_name=b'Type of Fault')),
                ('bs_ip', models.GenericIPAddressField(verbose_name=b'BS IP Address')),
                ('bs_sw_version', models.CharField(max_length=100, verbose_name=b'BS Software Version')),
                ('total_affected_sector', models.IntegerField(default=0, verbose_name=b'Number of Sectors Affected')),
                ('switch_reachability', models.CharField(max_length=150, verbose_name=b'Switch Reachability')),
                ('outage_timestamp', models.DateTimeField(null=True, verbose_name=b'Outage Date And Time', blank=True)),
                ('restored_timestamp', models.DateTimeField(null=True, verbose_name=b'Restored Date And Time', blank=True)),
                ('alarm_restored_timestamp', models.DateTimeField(null=True, verbose_name=b'Alarm Restored Date And Time', blank=True)),
                ('outage_min_per_site', models.CharField(max_length=100, verbose_name=b'Outage Per Site(Min.)')),
                ('mttr_hrs', models.FloatField(verbose_name=b'MTTR Hrs')),
                ('mttr', models.CharField(max_length=150, verbose_name=b'MTTR')),
                ('outage_total_min', models.IntegerField(default=0, verbose_name=b'Outage Total(Min.)')),
                ('alarm_outage_min', models.IntegerField(default=0, verbose_name=b'Alarm Outage(Min.)')),
                ('total_affected_enterprise_ss', models.IntegerField(default=0, verbose_name=b'Number of Enterprise SS Affected')),
                ('total_affected_retail_ss', models.IntegerField(default=0, verbose_name=b'Number of Retail SS Affected')),
                ('l1_engg_name', models.CharField(max_length=200, verbose_name=b'Name of L1 Engineer')),
                ('l2_engg_name', models.CharField(max_length=200, verbose_name=b'Name of L2 Engineer')),
                ('call_assigned_to', models.CharField(max_length=200, verbose_name=b'Call Assigned To')),
                ('last_modified_by', models.CharField(max_length=200, verbose_name=b'Last Modified By')),
                ('tac_tt_number', models.IntegerField(default=0, verbose_name=b'Tac TT Number')),
                ('cause_code', models.CharField(max_length=150, verbose_name=b'Cause Code')),
                ('sub_cause_code', models.CharField(max_length=150, verbose_name=b'Sub Cause Code')),
                ('unit_replaced', models.CharField(max_length=100, verbose_name=b'Unit Replaced')),
                ('equipment_replaced', models.CharField(max_length=100, verbose_name=b'Equipment Replaced')),
                ('old_sr_number', models.CharField(max_length=128, verbose_name=b'Old Sno.')),
                ('new_sr_number', models.CharField(max_length=128, verbose_name=b'New Sno.')),
                ('alarm_observer', models.CharField(max_length=255, verbose_name=b'Alarm Observed')),
                ('delay', models.IntegerField(default=0, verbose_name=b'Delay')),
                ('delay_reason', models.CharField(max_length=255, verbose_name=b'Delay Reason')),
                ('restore_action', models.CharField(max_length=255, verbose_name=b'Action Taken to Restore the BS')),
                ('fault_description', models.TextField(null=True, verbose_name=b'Remark/Detail Fault Description', blank=True)),
                ('status', models.CharField(max_length=150, verbose_name=b'Status')),
                ('infra_provider', models.CharField(max_length=150, verbose_name=b'INFRA Provider')),
                ('site_id', models.CharField(max_length=150, verbose_name=b'Site ID')),
                ('spot_cases', models.IntegerField(default=0, verbose_name=b'Spot Cases')),
                ('fault_history', models.TextField(null=True, verbose_name=b'Fault History', blank=True)),
                ('rfo', models.CharField(max_length=200, verbose_name=b'RFO')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name=b'Uploaded At')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BSOutageMainWeekly',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('organization', models.CharField(max_length=150, verbose_name=b'Organization')),
                ('week_number', models.CharField(max_length=100, verbose_name=b'Week of the Year')),
                ('ticket_number', models.CharField(max_length=150, verbose_name=b'Trouble Ticket Number')),
                ('total_affected_bs', models.IntegerField(default=0, verbose_name=b'Number of BS Affected')),
                ('city', models.CharField(max_length=200, verbose_name=b'City')),
                ('type_of_city', models.CharField(max_length=100, verbose_name=b'Type of City')),
                ('bs_name', models.CharField(max_length=255, verbose_name=b'BaseStation Name')),
                ('bs_type', models.CharField(max_length=100, verbose_name=b'BaseStation Type')),
                ('fault_type', models.CharField(max_length=100, verbose_name=b'Type of Fault')),
                ('bs_ip', models.GenericIPAddressField(verbose_name=b'BS IP Address')),
                ('bs_sw_version', models.CharField(max_length=100, verbose_name=b'BS Software Version')),
                ('total_affected_sector', models.IntegerField(default=0, verbose_name=b'Number of Sectors Affected')),
                ('switch_reachability', models.CharField(max_length=150, verbose_name=b'Switch Reachability')),
                ('outage_timestamp', models.DateTimeField(null=True, verbose_name=b'Outage Date And Time', blank=True)),
                ('restored_timestamp', models.DateTimeField(null=True, verbose_name=b'Restored Date And Time', blank=True)),
                ('alarm_restored_timestamp', models.DateTimeField(null=True, verbose_name=b'Alarm Restored Date And Time', blank=True)),
                ('outage_min_per_site', models.CharField(max_length=100, verbose_name=b'Outage Per Site(Min.)')),
                ('mttr_hrs', models.FloatField(verbose_name=b'MTTR Hrs')),
                ('mttr', models.CharField(max_length=150, verbose_name=b'MTTR')),
                ('outage_total_min', models.IntegerField(default=0, verbose_name=b'Outage Total(Min.)')),
                ('alarm_outage_min', models.IntegerField(default=0, verbose_name=b'Alarm Outage(Min.)')),
                ('total_affected_enterprise_ss', models.IntegerField(default=0, verbose_name=b'Number of Enterprise SS Affected')),
                ('total_affected_retail_ss', models.IntegerField(default=0, verbose_name=b'Number of Retail SS Affected')),
                ('l1_engg_name', models.CharField(max_length=200, verbose_name=b'Name of L1 Engineer')),
                ('l2_engg_name', models.CharField(max_length=200, verbose_name=b'Name of L2 Engineer')),
                ('call_assigned_to', models.CharField(max_length=200, verbose_name=b'Call Assigned To')),
                ('last_modified_by', models.CharField(max_length=200, verbose_name=b'Last Modified By')),
                ('tac_tt_number', models.IntegerField(default=0, verbose_name=b'Tac TT Number')),
                ('cause_code', models.CharField(max_length=150, verbose_name=b'Cause Code')),
                ('sub_cause_code', models.CharField(max_length=150, verbose_name=b'Sub Cause Code')),
                ('unit_replaced', models.CharField(max_length=100, verbose_name=b'Unit Replaced')),
                ('equipment_replaced', models.CharField(max_length=100, verbose_name=b'Equipment Replaced')),
                ('old_sr_number', models.CharField(max_length=128, verbose_name=b'Old Sno.')),
                ('new_sr_number', models.CharField(max_length=128, verbose_name=b'New Sno.')),
                ('alarm_observer', models.CharField(max_length=255, verbose_name=b'Alarm Observed')),
                ('delay', models.IntegerField(default=0, verbose_name=b'Delay')),
                ('delay_reason', models.CharField(max_length=255, verbose_name=b'Delay Reason')),
                ('restore_action', models.CharField(max_length=255, verbose_name=b'Action Taken to Restore the BS')),
                ('fault_description', models.TextField(null=True, verbose_name=b'Remark/Detail Fault Description', blank=True)),
                ('status', models.CharField(max_length=150, verbose_name=b'Status')),
                ('infra_provider', models.CharField(max_length=150, verbose_name=b'INFRA Provider')),
                ('site_id', models.CharField(max_length=150, verbose_name=b'Site ID')),
                ('spot_cases', models.IntegerField(default=0, verbose_name=b'Spot Cases')),
                ('fault_history', models.TextField(null=True, verbose_name=b'Fault History', blank=True)),
                ('rfo', models.CharField(max_length=200, verbose_name=b'RFO')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name=b'Uploaded At')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BSOutageMTTRProcessed',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('organization', models.CharField(max_length=150, verbose_name=b'Organization')),
                ('city', models.CharField(max_length=200, verbose_name=b'City')),
                ('bs_name', models.CharField(max_length=255, verbose_name=b'BaseStation Name')),
                ('rfo', models.CharField(max_length=255, null=True, verbose_name=b'RFO', blank=True)),
                ('processed_on', models.DateField(default=datetime.datetime.now, verbose_name=b'Processed Date and Time', blank=True)),
                ('time_frame', models.CharField(max_length=150, verbose_name=b'4-8 or Greater than 8 hrs')),
                ('processed_key', models.CharField(max_length=128, verbose_name=b'Key for Processing')),
                ('processed_value', models.CharField(max_length=64, verbose_name=b'Value of Processing')),
            ],
        ),
        migrations.CreateModel(
            name='BSOutageReports',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=128, verbose_name=b'Report Name')),
                ('is_processed', models.IntegerField(default=0, verbose_name=b'Report Processing Details')),
                ('process_for', models.DateField(default=datetime.datetime.now, verbose_name=b'User Tagged Report Date or Month', blank=True)),
                ('upload_to', models.FileField(upload_to=download_center.models.uploaded_file_name, max_length=512, verbose_name=b'Uploaded File')),
                ('absolute_path', models.TextField(verbose_name=b'Absolute File Path on OS')),
            ],
        ),
        migrations.CreateModel(
            name='BSOutageUptimeReport',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('organization', models.CharField(max_length=150, verbose_name=b'Organization')),
                ('city', models.CharField(max_length=200, verbose_name=b'City')),
                ('bs_name', models.CharField(max_length=255, verbose_name=b'BaseStation Name')),
                ('bs_uptime', models.CharField(max_length=150, verbose_name=b'BS Uptime')),
                ('total_uptime_min', models.CharField(max_length=150, verbose_name=b'Total Uptime(Min.)')),
                ('total_uptime_percent', models.CharField(max_length=150, verbose_name=b'Uptime in %')),
                ('report_id', models.ForeignKey(to='download_center.BSOutageReports')),
            ],
        ),
        migrations.AddField(
            model_name='bsoutagemttrprocessed',
            name='report_id',
            field=models.ForeignKey(to='download_center.BSOutageReports'),
        ),
        migrations.AddField(
            model_name='bsoutagemainweekly',
            name='report_id',
            field=models.ForeignKey(to='download_center.BSOutageReports'),
        ),
        migrations.AddField(
            model_name='bsoutagemainmonthly',
            name='report_id',
            field=models.ForeignKey(to='download_center.BSOutageReports'),
        ),
        migrations.AddField(
            model_name='bsoutagemaindaily',
            name='report_id',
            field=models.ForeignKey(to='download_center.BSOutageReports'),
        ),
        migrations.AddField(
            model_name='bsoutagefaultweekly',
            name='report_id',
            field=models.ForeignKey(to='download_center.BSOutageReports'),
        ),
        migrations.AddField(
            model_name='bsoutagefaultmonthly',
            name='report_id',
            field=models.ForeignKey(to='download_center.BSOutageReports'),
        ),
        migrations.AddField(
            model_name='bsoutagefaultdaily',
            name='report_id',
            field=models.ForeignKey(to='download_center.BSOutageReports'),
        ),
    ]
