# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import datetime
import dashboard.models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardRangeStatusDaily',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('dashboard_name', models.CharField(max_length=100, db_index=True)),
                ('device_name', models.CharField(max_length=100, db_index=True)),
                ('reference_name', models.CharField(max_length=100, db_index=True)),
                ('processed_for', models.DateTimeField()),
                ('range1', models.IntegerField(default=0)),
                ('range2', models.IntegerField(default=0)),
                ('range3', models.IntegerField(default=0)),
                ('range4', models.IntegerField(default=0)),
                ('range5', models.IntegerField(default=0)),
                ('range6', models.IntegerField(default=0)),
                ('range7', models.IntegerField(default=0)),
                ('range8', models.IntegerField(default=0)),
                ('range9', models.IntegerField(default=0)),
                ('range10', models.IntegerField(default=0)),
                ('unknown', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(default=inventory.models.get_default_org, to='organization.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardRangeStatusHourly',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('dashboard_name', models.CharField(max_length=100, db_index=True)),
                ('device_name', models.CharField(max_length=100, db_index=True)),
                ('reference_name', models.CharField(max_length=100, db_index=True)),
                ('processed_for', models.DateTimeField()),
                ('range1', models.IntegerField(default=0)),
                ('range2', models.IntegerField(default=0)),
                ('range3', models.IntegerField(default=0)),
                ('range4', models.IntegerField(default=0)),
                ('range5', models.IntegerField(default=0)),
                ('range6', models.IntegerField(default=0)),
                ('range7', models.IntegerField(default=0)),
                ('range8', models.IntegerField(default=0)),
                ('range9', models.IntegerField(default=0)),
                ('range10', models.IntegerField(default=0)),
                ('unknown', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(default=inventory.models.get_default_org, to='organization.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardRangeStatusMonthly',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('dashboard_name', models.CharField(max_length=100, db_index=True)),
                ('device_name', models.CharField(max_length=100, db_index=True)),
                ('reference_name', models.CharField(max_length=100, db_index=True)),
                ('processed_for', models.DateTimeField()),
                ('range1', models.IntegerField(default=0)),
                ('range2', models.IntegerField(default=0)),
                ('range3', models.IntegerField(default=0)),
                ('range4', models.IntegerField(default=0)),
                ('range5', models.IntegerField(default=0)),
                ('range6', models.IntegerField(default=0)),
                ('range7', models.IntegerField(default=0)),
                ('range8', models.IntegerField(default=0)),
                ('range9', models.IntegerField(default=0)),
                ('range10', models.IntegerField(default=0)),
                ('unknown', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(default=inventory.models.get_default_org, to='organization.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardRangeStatusTimely',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('dashboard_name', models.CharField(max_length=100, db_index=True)),
                ('device_name', models.CharField(max_length=100, db_index=True)),
                ('reference_name', models.CharField(max_length=100, db_index=True)),
                ('processed_for', models.DateTimeField()),
                ('range1', models.IntegerField(default=0)),
                ('range2', models.IntegerField(default=0)),
                ('range3', models.IntegerField(default=0)),
                ('range4', models.IntegerField(default=0)),
                ('range5', models.IntegerField(default=0)),
                ('range6', models.IntegerField(default=0)),
                ('range7', models.IntegerField(default=0)),
                ('range8', models.IntegerField(default=0)),
                ('range9', models.IntegerField(default=0)),
                ('range10', models.IntegerField(default=0)),
                ('unknown', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(default=inventory.models.get_default_org, to='organization.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardRangeStatusWeekly',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('dashboard_name', models.CharField(max_length=100, db_index=True)),
                ('device_name', models.CharField(max_length=100, db_index=True)),
                ('reference_name', models.CharField(max_length=100, db_index=True)),
                ('processed_for', models.DateTimeField()),
                ('range1', models.IntegerField(default=0)),
                ('range2', models.IntegerField(default=0)),
                ('range3', models.IntegerField(default=0)),
                ('range4', models.IntegerField(default=0)),
                ('range5', models.IntegerField(default=0)),
                ('range6', models.IntegerField(default=0)),
                ('range7', models.IntegerField(default=0)),
                ('range8', models.IntegerField(default=0)),
                ('range9', models.IntegerField(default=0)),
                ('range10', models.IntegerField(default=0)),
                ('unknown', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(default=inventory.models.get_default_org, to='organization.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardRangeStatusYearly',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('dashboard_name', models.CharField(max_length=100, db_index=True)),
                ('device_name', models.CharField(max_length=100, db_index=True)),
                ('reference_name', models.CharField(max_length=100, db_index=True)),
                ('processed_for', models.DateTimeField()),
                ('range1', models.IntegerField(default=0)),
                ('range2', models.IntegerField(default=0)),
                ('range3', models.IntegerField(default=0)),
                ('range4', models.IntegerField(default=0)),
                ('range5', models.IntegerField(default=0)),
                ('range6', models.IntegerField(default=0)),
                ('range7', models.IntegerField(default=0)),
                ('range8', models.IntegerField(default=0)),
                ('range9', models.IntegerField(default=0)),
                ('range10', models.IntegerField(default=0)),
                ('unknown', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(default=inventory.models.get_default_org, to='organization.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardSetting',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('page_name', models.CharField(max_length=30, verbose_name=b'Page Name', choices=[(b'rf_dashboard', b'RF Performance Dashboard'), (b'main_dashboard', b'Main Dashboard')])),
                ('is_bh', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=250, verbose_name=b'Dashboard Name', choices=[(b'latency-pmp', b'latency-pmp'), (b'packetloss-network', b'packetloss-network'), (b'down-wimax', b'down-wimax'), (b'uas', b'uas'), (b'packetloss-pmp', b'packetloss-pmp'), (b'modulation_ul_fec', b'modulation_ul_fec'), (b'down-pmp', b'down-pmp'), (b'down-network', b'down-network'), (b'availability', b'availability'), (b'latency-network', b'latency-network'), (b'ul_rssi', b'ul_rssi'), (b'topology-pmp', b'topology-pmp'), (b'temperature', b'temperature'), (b'topology-wimax', b'topology-wimax'), (b'ul_cinr', b'ul_cinr'), (b'packetloss-wimax', b'packetloss-wimax'), (b'latency-wimax', b'latency-wimax'), (b'dl_rssi', b'dl_rssi'), (b'dl_jitter', b'dl_jitter'), (b'modulation_dl_fec', b'modulation_dl_fec'), (b'ul_jitter', b'ul_jitter'), (b'latency-p2p-bh', b'latency-p2p-bh'), (b'rereg_count', b'rereg_count'), (b'dl_cinr', b'dl_cinr'), (b'rssi', b'rssi')])),
                ('dashboard_type', models.CharField(max_length=3, verbose_name=b'Dashboard Type', choices=[(b'INT', b'Numeric'), (b'STR', b'String')])),
                ('range1_start', models.CharField(max_length=20, null=True, verbose_name=b'Range1 Start', blank=True)),
                ('range1_end', models.CharField(max_length=20, null=True, verbose_name=b'Range1 End', blank=True)),
                ('range1_color_hex_value', models.CharField(max_length=100, null=True, verbose_name=b'Range-1 Color', blank=True)),
                ('range2_start', models.CharField(max_length=20, null=True, verbose_name=b'Range2 Start', blank=True)),
                ('range2_end', models.CharField(max_length=20, null=True, verbose_name=b'Range2 End', blank=True)),
                ('range2_color_hex_value', models.CharField(max_length=100, null=True, verbose_name=b'Range-2 Color', blank=True)),
                ('range3_start', models.CharField(max_length=20, null=True, verbose_name=b'Range3 Start', blank=True)),
                ('range3_end', models.CharField(max_length=20, null=True, verbose_name=b'Range3 End', blank=True)),
                ('range3_color_hex_value', models.CharField(max_length=100, null=True, verbose_name=b'Range-3 Color', blank=True)),
                ('range4_start', models.CharField(max_length=20, null=True, verbose_name=b'Range4 Start', blank=True)),
                ('range4_end', models.CharField(max_length=20, null=True, verbose_name=b'Range4 End', blank=True)),
                ('range4_color_hex_value', models.CharField(max_length=100, null=True, verbose_name=b'Range-4 Color', blank=True)),
                ('range5_start', models.CharField(max_length=20, null=True, verbose_name=b'Range5 Start', blank=True)),
                ('range5_end', models.CharField(max_length=20, null=True, verbose_name=b'Range5 End', blank=True)),
                ('range5_color_hex_value', models.CharField(max_length=100, null=True, verbose_name=b'Range-5 Color', blank=True)),
                ('range6_start', models.CharField(max_length=20, null=True, verbose_name=b'Range6 Start', blank=True)),
                ('range6_end', models.CharField(max_length=20, null=True, verbose_name=b'Range6 End', blank=True)),
                ('range6_color_hex_value', models.CharField(max_length=100, null=True, verbose_name=b'Range-6 Color', blank=True)),
                ('range7_start', models.CharField(max_length=20, null=True, verbose_name=b'Range7 Start', blank=True)),
                ('range7_end', models.CharField(max_length=20, null=True, verbose_name=b'Range7 End', blank=True)),
                ('range7_color_hex_value', models.CharField(max_length=100, null=True, verbose_name=b'Range-7 Color', blank=True)),
                ('range8_start', models.CharField(max_length=20, null=True, verbose_name=b'Range8 Start', blank=True)),
                ('range8_end', models.CharField(max_length=20, null=True, verbose_name=b'Range8 End', blank=True)),
                ('range8_color_hex_value', models.CharField(max_length=100, null=True, verbose_name=b'Range-8 Color', blank=True)),
                ('range9_start', models.CharField(max_length=20, null=True, verbose_name=b'Range9 Start', blank=True)),
                ('range9_end', models.CharField(max_length=20, null=True, verbose_name=b'Range9 End', blank=True)),
                ('range9_color_hex_value', models.CharField(max_length=100, null=True, verbose_name=b'Range-9 Color', blank=True)),
                ('range10_start', models.CharField(max_length=20, null=True, verbose_name=b'Range10 Start', blank=True)),
                ('range10_end', models.CharField(max_length=20, null=True, verbose_name=b'Range10 End', blank=True)),
                ('range10_color_hex_value', models.CharField(max_length=100, null=True, verbose_name=b'Range-10 Color', blank=True)),
                ('technology', models.ForeignKey(blank=True, to='device.DeviceTechnology', null=True)),
            ],
            options={
                'verbose_name': 'dashboard setting',
                'verbose_name_plural': 'dashboard settings',
            },
        ),
        migrations.CreateModel(
            name='DashboardSeverityStatusDaily',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('dashboard_name', models.CharField(max_length=100, db_index=True)),
                ('device_name', models.CharField(max_length=100, db_index=True)),
                ('reference_name', models.CharField(max_length=100, db_index=True)),
                ('processed_for', models.DateTimeField()),
                ('warning', models.IntegerField(default=0)),
                ('critical', models.IntegerField(default=0)),
                ('ok', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
                ('unknown', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(default=inventory.models.get_default_org, to='organization.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardSeverityStatusHourly',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('dashboard_name', models.CharField(max_length=100, db_index=True)),
                ('device_name', models.CharField(max_length=100, db_index=True)),
                ('reference_name', models.CharField(max_length=100, db_index=True)),
                ('processed_for', models.DateTimeField()),
                ('warning', models.IntegerField(default=0)),
                ('critical', models.IntegerField(default=0)),
                ('ok', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
                ('unknown', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(default=inventory.models.get_default_org, to='organization.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardSeverityStatusMonthly',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('dashboard_name', models.CharField(max_length=100, db_index=True)),
                ('device_name', models.CharField(max_length=100, db_index=True)),
                ('reference_name', models.CharField(max_length=100, db_index=True)),
                ('processed_for', models.DateTimeField()),
                ('warning', models.IntegerField(default=0)),
                ('critical', models.IntegerField(default=0)),
                ('ok', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
                ('unknown', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(default=inventory.models.get_default_org, to='organization.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardSeverityStatusTimely',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('dashboard_name', models.CharField(max_length=100, db_index=True)),
                ('device_name', models.CharField(max_length=100, db_index=True)),
                ('reference_name', models.CharField(max_length=100, db_index=True)),
                ('processed_for', models.DateTimeField()),
                ('warning', models.IntegerField(default=0)),
                ('critical', models.IntegerField(default=0)),
                ('ok', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
                ('unknown', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(default=inventory.models.get_default_org, to='organization.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardSeverityStatusWeekly',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('dashboard_name', models.CharField(max_length=100, db_index=True)),
                ('device_name', models.CharField(max_length=100, db_index=True)),
                ('reference_name', models.CharField(max_length=100, db_index=True)),
                ('processed_for', models.DateTimeField()),
                ('warning', models.IntegerField(default=0)),
                ('critical', models.IntegerField(default=0)),
                ('ok', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
                ('unknown', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(default=inventory.models.get_default_org, to='organization.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardSeverityStatusYearly',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('dashboard_name', models.CharField(max_length=100, db_index=True)),
                ('device_name', models.CharField(max_length=100, db_index=True)),
                ('reference_name', models.CharField(max_length=100, db_index=True)),
                ('processed_for', models.DateTimeField()),
                ('warning', models.IntegerField(default=0)),
                ('critical', models.IntegerField(default=0)),
                ('ok', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
                ('unknown', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(default=inventory.models.get_default_org, to='organization.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DFRProcessed',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('processed_on', models.DateField(default=datetime.datetime.now, verbose_name=b'Processed Date and Time', blank=True)),
                ('processed_key', models.CharField(max_length=128, verbose_name=b'Key for Processing')),
                ('processed_value', models.CharField(max_length=64, verbose_name=b'Value of Processing')),
                ('processed_report_path', models.TextField(verbose_name=b'Absolute File Path on OS')),
            ],
        ),
        migrations.CreateModel(
            name='MFRCauseCode',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('processed_on', models.DateField(default=datetime.datetime.now, verbose_name=b'Processed Date and Time', blank=True)),
                ('processed_key', models.CharField(max_length=128, verbose_name=b'Key for Processing')),
                ('processed_value', models.CharField(max_length=64, verbose_name=b'Value of Processing')),
            ],
        ),
        migrations.CreateModel(
            name='MFRDFRReports',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=128, verbose_name=b'Report Name')),
                ('type', models.CharField(max_length=8, verbose_name=b'Report Type', choices=[(b'MFR', b'Monthly Fault Report'), (b'DFR', b'Daily Fault Report')])),
                ('is_processed', models.IntegerField(default=0, verbose_name=b'Report Processing Details')),
                ('process_for', models.DateField(default=datetime.datetime.now, verbose_name=b'User Tagged Report Date or Month', blank=True)),
                ('upload_to', models.FileField(upload_to=dashboard.models.uploaded_file_name, max_length=512, verbose_name=b'Uploaded File')),
                ('absolute_path', models.TextField(verbose_name=b'Absolute File Path on OS')),
            ],
        ),
        migrations.CreateModel(
            name='MFRProcessed',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('processed_on', models.DateField(default=datetime.datetime.now, verbose_name=b'Processed Date and Time', blank=True)),
                ('processed_key', models.CharField(max_length=128, verbose_name=b'Key for Processing')),
                ('processed_value', models.CharField(max_length=64, verbose_name=b'Value of Processing')),
                ('processed_for', models.ForeignKey(to='dashboard.MFRDFRReports')),
            ],
        ),
        migrations.AddField(
            model_name='mfrcausecode',
            name='processed_for',
            field=models.ForeignKey(to='dashboard.MFRDFRReports'),
        ),
        migrations.AddField(
            model_name='dfrprocessed',
            name='processed_for',
            field=models.ForeignKey(to='dashboard.MFRDFRReports'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardsetting',
            unique_together=set([('name', 'page_name', 'technology', 'is_bh')]),
        ),
    ]
